### ISSUE TITLE
Sente Clojure Errors on (require)

### ISSUE THREAD

**Issue by twashing** [ptaoussanis/sente#100]
I'm getting some weird errors, when using ***sente 1.3.0***. Is there a specific version of java or clojure for which we should be using this lib? The sente's project.clj [uses clojure 1.5.0](https://github.com/ptaoussanis/sente/blob/master/project.clj#L14).

I get this error when trying to use sente 1.3.0 inside of my project.  

```
$ lein try com.taoensso/sente "1.3.0" ;; (messages below are compressed)
nREPL server started on port 51620 on host 127.0.0.1 - nrepl://127.0.0.1:51620
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.7.0-alpha1
Java HotSpot(TM) Server VM 1.7.0_72-b14

user=> (require '[taoensso.sente :as sente])
CompilerException java.lang.IllegalAccessError: have? does not exist, compiling:(taoensso/sente.clj:1:1) 
```

This error happens even when I try it outside of my project.  
```
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such var: clojure.core.cache/through, compiling:(clojure/core/memoize.clj:52:3)
               Compiler.java:6464 clojure.lang.Compiler.analyze
               Compiler.java:6406 clojure.lang.Compiler.analyze
               Compiler.java:3665 clojure.lang.Compiler$InvokeExpr.parse
               ...
                     core.clj:626 clojure.core/apply
                    core.clj:5524 clojure.core/load-libs
                  RestFn.java:137 clojure.lang.RestFn.applyTo
                     core.clj:626 clojure.core/apply
                     ...
                  RestFn.java:408 clojure.lang.RestFn.invoke
                    core.clj:5446 clojure.core/load-one
                    core.clj:5486 clojure.core/load-lib[fn]
                    core.clj:5485 clojure.core/load-lib
                  RestFn.java:142 clojure.lang.RestFn.applyTo
                     core.clj:626 clojure.core/apply
                    core.clj:5524 clojure.core/load-libs
                  RestFn.java:137 clojure.lang.RestFn.applyTo
                     core.clj:626 clojure.core/apply
                    core.clj:5607 clojure.core/require
                  RestFn.java:512 clojure.lang.RestFn.invoke
                      sente.clj:1 taoensso.sente/eval6779[fn]
                      sente.clj:1 taoensso.sente/eval6779
                      ...
                     core.clj:626 clojure.core/apply
                    core.clj:5607 clojure.core/require
                  RestFn.java:408 clojure.lang.RestFn.invoke
                 NO_SOURCE_FILE:1 user/eval6775
```

**Comment by twashing** [comment]
Oops, I take this back. You just need to include `[com.taoensso/encore "1.20.0"]` in your project as well. It's strange that that dependency is not pulled down along with sente. Oh well. 

Thanks :)

**Comment by ptaoussanis** [comment]
Hi Timothy, Sente 1.3.0 pulls in `[com.taoensso/encore "1.19.1"]` by default (which should be fine). You were probably experiencing a dependency conflict that got resolved by pulling in `encore` manually.

You can run `lein deps :tree` in future to check for possible dep conflicts like this.

Anyway, thanks for reporting + updating on this. Cheers! :-)

**Comment by twashing** [comment]
Yes, I think you're right. Thanks for pointing that out. I should've dug a bit deeper in the beginning. That's what happens in the throes of the problem stack, lol. 

Cheers :)

**Comment by yayitswei** [comment]
I just got this error as well. Oddly, it seems the order of dependencies matters in `project.clj`. 

This will produce an error:

                 [com.taoensso/timbre "3.3.1"]
                 [com.taoensso/sente "1.4.0-alpha2"]

Whereas this is fine:

                 [com.taoensso/sente "1.4.0-alpha2"]
                 [com.taoensso/timbre "3.3.1"]

Had to do `lein deps clean` in between to clear out the deps. Can @ptaoussanis comment as to why that is?

**Comment by ptaoussanis** [comment]
Hi Wei,

> This will produce an error:

Yeah, that's to be expected - this arrangement will cause a dependency conflict. Timbre imports an older version of Encore than Sente does, and Sente needs the newer version. Leiningen handles dependency conflicts as higher position > lower position rather than newer version > older version (which many users find surprising, I think).

Moving Sente above Timbre (or inserting an explicit Encore dep above Timbre) will force the correct dependency to be pulled in.

You can check for dependency conflicts by running `lein deps :tree`.

@yayitswei Does that make sense?

**Comment by yayitswei** [comment]
Yup, thanks for the clarification!

**Comment by ptaoussanis** [comment]
BTW have just added some info at https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md. Will also be adding a test to future versions of Sente that'll check for + report dependency conflicts.
