### ISSUE TITLE
1.4.0-alpha2 Error on handshake (only with :advanced compilation)

### ISSUE THREAD

**Issue by gbuisson** [ptaoussanis/sente#103]
Hi,

I'm currently testing an upgrade to Sente 1.4.0,
So far it works fine one dev, however with advanced compilation, i get these traces in my browser console straight at handshake:

app.js:1517 Unpacking: -[:chsk/handshake ["b927984c-7406-46ee-a47a-988423911983" nil]] -> [nil nil]
app.js:1517 handle-when-handshake!: nil
app.js:1517 receive-buffered-evs!: nil
app.js:1017 Uncaught Error: false is not ISeqable

the error pops, then new connection attempts are made regularly by the lib.

at first i thought maybe it's because i didn't provide a client-id, but no better if i use the one from the handshake or generate random.

the issue only appears when i compile in advanced mode, thus making it difficult to debug

Any idea ?

Cheers.

Environment:
- Immutant2 Server
- Sente 1.4.0-alpha2
- using default packer (:edn)

**Comment by tobias** [comment]
Do you see the same issue with the example app? Or when using http-kit instead of Immutant? I have very little cljs experience, but would be glad to try and recreate with the example app if you are seeing it there.

**Comment by gbuisson** [comment]
Hi, sorry i forgot to try the sample app, I will do it tomorrow  french time and report asap.
Thank you !

**Comment by ptaoussanis** [comment]
Hi, this sounds like a dependency conflict.

Please add `[com.taoensso/encore "1.20.1"]` to your project.clj dependencies _before_ any other `com.taoensso` deps. Then run `lein clean` and try again?

(You can check for dep conflicts with `lein deps :tree` btw).

If the added dep and `lein clean` don't help, please try the example app as Toby's suggested and we can go from there. Cheers :-)

**Comment by gbuisson** [comment]
Hello Peter, that was it! thank you very much!
