### ISSUE TITLE
Run example from terminal

### ISSUE THREAD

**Issue by devth** [ptaoussanis/sente#106]
I don't use emacs nor lighttable, so the instructions don't apply. I'm trying to run the example project from terminal with a `lein repl`. `load-file` doesn't work with cljx, but `require` seemed to work. I ran:

```clojure
(require 'example.my-app)
(ns example.my-app)
(start!)
```

The webserver starts and the page opens in my browser, but it can't find `main.js`. I'm guessing the cljs part isn't getting compiled? Is there a simple way to run it with `lein` or from the repl? Thanks.

**Comment by ptaoussanis** [comment]
Hi Trevor, something like this should do the trick (untested):
```clojure
lein cljx once ; cljx will produce .clj + .cljs files
lein cljsbuild once ; cljsbuild will compile .cljs -> .js
```
Then you can run `main.clj` as you like. 

Hope that helps, cheers :-)

**Comment by devth** [comment]
Thanks, Peter! For anyone else who lands here, the full instructions to run the example from terminal are:

0. `cd example-project`
0.  `lein cljx once && lein cljsbuild once && lein repl`
0. once the repl loads, run:
```clojure
(require 'example.my-app)
(in-ns 'example.my-app)
(start!)
```
