### ISSUE TITLE
example, main.js size

### ISSUE THREAD

**Issue by dxlr8r** [ptaoussanis/sente#107]
Hello, I am looking around and came across this project. I have the example running and working, but I am amazed by the size of the main.js file... The way I see it the example isn't bloated and doesn't include more than necessary, except for "Transit encoding" which I #_'ed which took of 136 926 bytes but the file is still or ~2,1MB (2 114 003 bytes).

So my question is... Is it possible to slim it somehow? I could ofcourse remove all the whitespacing (tabs, newlines, etc.) but except from that? Possible to remove some of the functions etc.?

**Comment by ptaoussanis** [comment]
Hi Simen,

You need to enable ClojureScript (Google Closure's) advanced compilation mode for production. Not sure where the best docs are for this these days, but [here's](https://github.com/clojure/clojurescript/wiki/Quick-Start#production-mode) one reference.

That'll engage Google Closure's optimizations (incl. unused code shaking) and will produce a much smaller output .js file.

Hope that helps, cheers! :-)
