### ISSUE TITLE
ReferenceError: taoensso is not defined

### ISSUE THREAD

**Issue by teaforthecat** [ptaoussanis/sente#114]
I see this error in a cljs repl when executing sente/make-channel-socket! . I'm coping the code out of the Sente readme and example project. The project I'm working on is here: https://github.com/teaforthecat/test-cljs-app/tree/sente  There is a "sente" branch with the code pasted in from the example project. I put the reproduction steps in the readme there. They are pretty simple; load a cljs repl with figwheel, execute sente code and see the error. Figwheel is working with other libraries like cljs-ajax, and I've reloaded the app a few times. I'm wondering if there is a library incompatibility I'm running into, or if there is something I missed.  If you could take a look that would be excellent. Here is the output from the repl:

```
ClojureScript:consulate.core> (let [{:keys [chsk ch-recv send-fn state]}
      (sente/make-channel-socket! "/chsk" ; Note the same path as before
       {:type :auto ; e/o #{:auto :ajax :ws}
       })]
  (def chsk       chsk)
  (def ch-chsk    ch-recv) ; ChannelSocket's receive channel
  (def chsk-send! send-fn) ; ChannelSocket's send API fn
  (def chsk-state state)   ; Watchable, read-only atom
  )

#<ReferenceError: taoensso is not defined>
ReferenceError: taoensso is not defined

```

**Comment by teaforthecat** [comment]
sorry for the noise - `lein clean` fixed it

**Comment by ptaoussanis** [comment]
Hey Chris, no problem at all - sorry for not replying earlier, was travelling.

Happy you found the solution, thanks for reporting back! Cheers :-)
