### ISSUE TITLE
Sending additional headers

### ISSUE THREAD

**Issue by jaen** [ptaoussanis/sente#116]
Hi,

I have a SPA which uses JSON Web Tokens for authentication and thus has no backend sessions (at the moment at least) from which I can recover the `user-id`. The server expects the token to be sent in an `Api-Auth` header and associates a logged-in user based on the token contents.
I want to set `user-id` based on that so I can target specific users while sending an event, but I can't seem to be able to find a way to attach the custom header to Sente handshake.

Am I missing something and there's a way to do that? If not, would it be hard to add such a feature?

**Comment by whodidthis** [comment]
Possibly related: http://stackoverflow.com/a/4361358

**Comment by ptaoussanis** [comment]
Hi Tomek!

To clarify:
Your server has some kind of mapping between authentic tokens and users, yes?
And clients know what their own token is?

If so, you should be good without needing to modify any headers. Just set the client-side `make-channel-socket!` `:client-id` opt to your user token value.

Or am I maybe missing something?

**Comment by ptaoussanis** [comment]
Closing for now, feel free to reopen if you're still having issues.

**Comment by jaen** [comment]
@ptaoussanis really sorry for dropping the ball on this issue, but RL dropped the ball on me and suddenly implementing this dropped off my radar ~~'

I'll have to be implementing something vaguely similar, so I hope you don't mind I inquire into this again I'll try to describe the issue in a clearer way this time.

I have a backend server and a SPA client. Communication goes only through Sente, there's no REST API whatsoever. Authentication is stateless with JWT.
This of course means that sign-in is done through Sente and there is no session to persist it in. From what I understand of the documentation there are functions for both setting `:client-id` in the client and `:user-id` in the server, but as far as I understand this happens only during connection set-up.

While your suggestion to use the token as `:client-id` seems like it will probably work if I understand this right (I can encode `:user-id` in the token, it's HMAC'd so I know it weren't tampered with and can extract the `:user-id` from there and use it) there's another problem I can see. It's that it works as long as I have the token beforehand.  
In the previous application, in addition to Sente, I also had a REST API, so it could serve as the authentication vector, I could set-up the connection when I already had the proper toke to put in `:client-id`. Here, where I only have Sente-based communications I see no way to alter `:user-id` for the current connection after it had already been set up.

Is just creating a "guest" connection, sending the sign-in message and then re-connecting with `:client-id` returned during log-in to extract the `:user-id` from it the only option or is there some API to update `:user-id` for current connection? If not, would it make any sense to add this, or do you think having to reconnect like that is a better approach for Sente?

If something's unclear then please do tell me, I'll try to clarify what I'm after.

Thanks in advance for help.

**Comment by danielcompton** [comment]
Relates to #135.
