### ISSUE TITLE
Sockets with large message sizes not sending

### ISSUE THREAD

**Issue by dillonforrest** [ptaoussanis/sente#117]
Hi there! Sente is working great for me right now. I've been using it for a few weeks so far! Awesome work. :) Thank you!!

I'd like to report an issue. When I try to send a large message, I get this error:

```
Chsk is closed: will try reconnect (1).
```

I believe it's not sending because my message is a large string (>260,000 characters). When I cut it in half to about 130,000 characters, it sends without warnings and my server logs the message. 

What solution would you recommend? Is my diagnosis correct? If so, is there a way to increase the permitted message size?

(I'm about to experiment with just breaking my large string into smaller strings and sending them separately!)

**Comment by ptaoussanis** [comment]
Hi Dillon, thanks for the report.

There's no intentional message size limit on Sente's end, but I don't normally send messages that size myself so it wouldn't surprise me if you're encountering a bug somewhere.

A few questions to help with diagnosis:
1. Are you overriding the default Cljs-side `make-channel-socket!` `:packer` option (e.g. to use Transit)? If you are, does it make a difference if you use the default?
2. Are you using http-kit? If you are, any idea if it makes a difference if you try Immutant instead?
3. Approximately how long does it take to transfer a payload of this size on your connection? Have you noticed any relationship between the error not/happening and the client-server connection (e.g. this error only occurs in production when communicating with a server far away, but it doesn't happen in dev when you're communicating only against localhost)?

The likeliest cause is an http-kit message size limit, but that's just a guess.

**Comment by ptaoussanis** [comment]
Did a quick search, there do seem to be a few size limits http-kit side. When you say "> 260k characters", how much bigger are you talking? Can the error be reproduced reliably?

**Comment by dillonforrest** [comment]
Hi @ptaoussanis, thanks for the prompt reply! I'll dive straight into it:

> There's no intentional message size limit on Sente's end, but I don't normally send messages that size myself so it wouldn't surprise me if you're encountering a bug somewhere.

My use case is definitely an outlier. Like I said, Sente has been perfect for everything else!

> A few questions to help with diagnosis:
> 1. Are you overriding the default Cljs-side make-channel-socket! :packer option (e.g. to use Transit)? If you are, does it make a difference if you use the default?

No, I'm doing nothing to override the default `:packer` option. Currently just using the default! :)

> 2. Are you using http-kit? If you are, any idea if it makes a difference if you try Immutant instead?

Yes, I'm using http-kit. Not sure if Immutant would make a difference, but haven't considered trying it yet.

> 3. Approximately how long does it take to transfer a payload of this size on your connection? Have you noticed any relationship between the error not/happening and the client-server connection (e.g. this error only occurs in production when communicating with a server far away, but it doesn't happen in dev when you're communicating only against localhost)?

Not sure how long the transfer takes actually. I didn't notice any delays though! Thankfully this is all in development right now! No production errors. :)

**Comment by dillonforrest** [comment]
Whoops, forgot to reply to your second message:

> Did a quick search, there do seem to be a few size limits http-kit side (e.g. a 4MB limit here). When you say "> 260k characters", how much bigger are you talking? Can the error be reproduced reliably?

I think the string was something like 261,150 characters. It was between 261,000 and 262,000 characters long. Yes, the error is reliably reproduced.

I found a workaround! Currently I'm just sending the string in 50,000-character chunks, and I wait 50ms before sending each chunk across the socket.

In my use case, this large string doesn't need to be sent quickly anyway. I just happened to be using Sente already, so I figured I'd use it to send this string across too. It's definitely not the intended use case for Sente. So, I'm gonna close this issue. Thanks so much for checking it out!! I spent several hours yesterday bashing my head on it before realizing that my message was just too big and needed to be sent in separate chunks.

**Comment by ptaoussanis** [comment]
> It's definitely not the intended use case for Sente.

It's not a _common_ use case (so far), but it's definitely not something that should be failing without an explanation. Am happy to look into this when I get a little free time; will reopen for now and get back to you when I've got some more info.

Thanks again for the report!

**Comment by dillonforrest** [comment]
My pleasure! Thanks again for the awesome contributions! Also, thanks for making such great documentation -- hard work that often goes unsung! :+1:

**Comment by ptaoussanis** [comment]
Hi Dillon, I believe this may finally be fixed with `[com.taoensso.forks/http-kit "2.1.20"]`.

Apologies for the crazy delay getting a solution!

**Comment by ptaoussanis** [comment]
Closing this for now, but please feel free to reopen if you're still experiencing problems.
