### ISSUE TITLE
Support for html5 server sent events

### ISSUE THREAD

**Issue by ioRekz** [ptaoussanis/sente#120]
I'm reading here and there that websockets can have issues with firewall.
In any case, I mostly need server to client push so I was wondering if you have thought about this.

**Comment by ptaoussanis** [comment]
Hi Jeremy, could you please rephrase this question?

**Comment by valichek** [comment]
ioRekz, if you cannot use websockets try XHR-polling, http-kit supports it.
Please^ read about it here http://www.http-kit.org/server.html#async

**Comment by ptaoussanis** [comment]
WebSockets should work fine over firewalls. Some rare issues can be overcome by using WebSockets over https (WSS). In any event, Sente will fall back to Ajax if there's any problem using WebSockets.

Closing this issue for now, feel free to reopen if I've misunderstood the question. Cheers :-)
