### ISSUE TITLE
Cannot seem to have the cljs client set the uid in the connection pool

### ISSUE THREAD

**Issue by retrogradeorbit** [ptaoussanis/sente#121]
Hi there, I have a problem:

on the client side I call sente/make-channel-socket! to initiate the connection. It generates a uuid as a unique ID and I see that event appear on the server. The id is passed through. If its a reply event I can reply.

But... When I then try to send just a server PUSH message to that id, it never arrives.

I look in connected-uids and I see:

{:ws #{:taoensso.sente/nil-uid}, :ajax #{}, :any #{:taoensso.sente/nil-uid}}

Whatever uid I send in the cljs client, the connection always comes up as id :taoensso.sente/nil-uid.

How can I get this client id to actually be correctly associated with the server side so that generic server PUSH messages to that uid will work?

Thanks!

**Comment by ptaoussanis** [comment]
Hi Crispin,

The auto-generated client-id (uuid) cannot be used for server->client push. What you need is a **user-id**. Please see the README or [here](https://github.com/ptaoussanis/sente/issues/118#issuecomment-87378277) for more info.

Hope that helps?

Cheers! :-)

**Comment by retrogradeorbit** [comment]
Ah! That link you just gave me really clears things up! Thankyou! It's all working as intended, now. 

:D

**Comment by ptaoussanis** [comment]
No problem, happy that helped :-)
