### ISSUE TITLE
conflicted with ring.middleware.format.wrap-restful-format

### ISSUE THREAD

**Issue by pkvov** [ptaoussanis/sente#123]
i found it conflicted with ring.middleware.format.wrap-restful-format.
thanks && appreciate your wonderful library
here is my ring handler
```
32  (-> handler
33      (wrap-authorization auth/auth-backend)
34      (wrap-authentication auth/auth-backend)
35      (wrap-idle-session-timeout
36       {:timeout (* 60 30)
37        :timeout-response (redirect "/")})
38      (wrap-restful-format :formats [:json-kw :edn :transit-json :transit-msgpack])
39      (wrap-defaults (-> site-defaults
40                         (assoc-in [:session :store] (memory-store session/mem))
41                         (assoc-in [:security :anti-forgery] true)))
42      ;;(wrap-internal-error :log #(timbre/error %))
43      ))
```

**Comment by ptaoussanis** [comment]
Hi @pkvov, you'll need to adjust your routing so that you're not applying unnecessary/incompatible middleware to Sente's routes (usu. one "/chsk" GET and one POST).

Does that help / make sense?

**Comment by pkvov** [comment]
thanks @ptaoussanis .  
i start from the Sente's example with the routes /chsk GET and POST. then i added middleware one by one, and found  wrap-restful-format conflicted with Sendte, and i need this middleware to help me parse the parameters send from client, and this is very common  to use Sendte with a ring stack web application.

**Comment by ptaoussanis** [comment]
The "/chsk" routes are basically an implementation detail as used by Sente. You shouldn't be applying application-level middleware to them, does that make sense?

> i need this middleware to help me parse the parameters send from client, and this is very common to use Sendte with a ring stack web application.

Sure, you can continue to use any middleware you want (incl. `ring.middleware.format.wrap-restful-format`) - just make sure to apply the middleware only to _your own application-level routes_ - Sente's implementation routes must be excluded.

The "/chsk" routes need `ring.middleware.defaults/wrap-defaults` plus any CSRF middleware you like, but nothing else (no application-level middleware).

Your own routes can have any middleware you like. Does that make sense?

You can exclude application-level middleware from Sente in several ways, the quickest/easiest might be something like `compojure.core/wrap-routes`.

**Comment by pkvov** [comment]
thanks alot @ptaoussanis , i finally understand.

do not mix Sente routes and middleware with application routes and middleware.
this post make it more clear 
http://stackoverflow.com/questions/28016968/serving-app-and-api-routes-with-different-middleware-using-ring-and-compojure

**Comment by ptaoussanis** [comment]
No problem, happy you found a solution. Thanks for sharing the link, that'll be helpful for other folks that might run into this issue.

Cheers :-)
