### ISSUE TITLE
Ability to set connection retry backoff options

### ISSUE THREAD

**Issue by CmdrDats** [ptaoussanis/sente#125]
Currently it's just a straight exponential backoff, but I see the function exp-backoff you're using : https://github.com/ptaoussanis/encore/blob/master/src/taoensso/encore.cljx#L632 has options for min/max backoff time.

I'd like to setup sente to backoff with a fairly small upper bound (since in our case we only have a few clients and they need to get back as soon as possible). It looks like these would be the places you'd have to implement it?

https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljx#L779
https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljx#L839
https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljx#L951
https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljx#L1076

Should I add it in those places and create a PR? If you'd like that, just let me know what you'd call the option names.

**Comment by ptaoussanis** [comment]
Hi there,

> Should I add it in those places and create a PR?

Sure - sounds good, thanks.

> If you'd like that, just let me know what you'd call the option names.

Let's say that cljs-side `make-channel-socket!` gets an additional optional called `:backoff-opts`? That can be a map passed as-is to `encore/exp-backoff` so something of the form `{:min _ :max _ :factor _}`, etc.

So perhaps redefine `set-exp-backoff-timeout!` as
```clojure
(defn- set-exp-backoff-timeout! [nullary-f nattempt & [opts]]
  (.setTimeout js/window nullary-f (enc/exp-backoff nattempt opts)))
```

Cheers! :-)

**Comment by ptaoussanis** [comment]
Closing this, now addressed on the dev branch.

**Comment by CmdrDats** [comment]
@ptaoussanis Thanks - Sorry I never got round to implementing the fix :/

**Comment by ptaoussanis** [comment]
No problem - happy you floated the idea.
