### ISSUE TITLE
Example project: use of default packer results in malformed data error

### ISSUE THREAD

**Issue by danielsz** [ptaoussanis/sente#131]
Hi Peter, 

If I try to use the default packer, either by uncommenting the line 
```clojure
(def packer :edn) ; Default packer (no need for Transit dep)
```
or by omitting the options argument altogether from `sente/make-channel-socket!`.

I get: 
```clojure
ExceptionInfo{:message "Malformed FlexiPacker data: [[:some/broadcast {:what-is-this \"A broadcast pushed from server\", :how-often \"Every 10 seconds\", :to-whom :taoensso.sente/nil-uid, :i 32}]]", :data {:s "[[:some/broadcast {:what-is-this \"A broadcast pushed from server\", :how-often \"Every 10 seconds\", :to-whom :taoensso.sente/nil-uid, :i 32}]]"}}
```

**Comment by ptaoussanis** [comment]
Hi Daniel, I can't reproduce this.

If you're getting a FlexiPacker error, that means that the default (:edn) packer isn't actually being used. Are you sure you've cleaned old build artefacts + rerun cljx?

**Comment by danielsz** [comment]
I don't use cljx. Also, there is no need to clean build artefacts with Boot. 

I've "untangled" the example app for the benefit of my workflow, and I bumped into that one problem. 

I suppose I will need to investigate more and report back if I can put the finger on the problem more precisely. 

Thanks!

**Comment by ptaoussanis** [comment]
Well if it's any help, the error means that the FlexiPacker is being used client-side but not server-side. If you've uncommented `(def packer :edn)` both client+server side, and you're confident that it's not a build issue, then I'm out of ideas - sorry.

The error can _only_ occur if the FlexiPacker is being used client-side; so I'd start trying to figure out why it's being used client-side when you're not expecting it to.

Cheers

**Comment by danielsz** [comment]
There you go. You've solved it for me. I was unaware that the packer configuration needs to happen both on the client-side and the server-side, which in retrospect was foolish of me.  

Sorry for the noise!
