### ISSUE TITLE
support puggable store for sente connections

### ISSUE THREAD

**Issue by bplatz** [ptaoussanis/sente#133]
For load balancing, I'm looking to implement a Redis connection store to for sente connections.

I don't see an obvious way of doing this without hacking into the source.

It would be nice to abstract sente's conn_ atom so it could utilize various pluggable stores, and I believe it would support a good load balancing solution. I think the consequence is that the buffer(s) would have to be pushed to the client-id level as multiple clients from the same user could be connected to different sente servers.

If there is an already established pattern for load balancing sente, I'd of course love to hear about it.

**Comment by ptaoussanis** [comment]
Hey there,

Load balancing is generally something that you'll want to have take place at an HTTP-request level. Is there a reason you'd prefer to avoid a traditional load-balancing strategy (e.g. nginx in front of your application servers)?

**Comment by bplatz** [comment]
I was referring not to the actual load balancing, but sente supporting its concept of publishing to a common user-id across multiple client devices in a load balanced environment.

**Comment by ptaoussanis** [comment]
You'll need to define this a little more clearly to make sure we're on the same page.

So you have 2 servers (S1, S2), and 10 users (U1, ... U10).

Your http load balancer has distributed the first five users to S1 and the next five 5 to S2
S1: (U1, ... U5)
S2: (U6, ... U10)

So you want to do what exactly in this scenario?

**Comment by bplatz** [comment]
Add in that user U1 has a web browser session connected to S1, and is also on their mobile device connected to server S2.

So I'd like to:
(chsk-send! uid [:some/message "my message"])
And have it perform as documented, even though it exists in a load balanced environment.

Or even in a single device scenario, have a background process need to send a message to U2. Is U2 connected? On what server? How to I get the message there?

I brought up Redis as an ideal place to centralize the current state of sente, however if it were implemented generically then other solutions could be plugged in.

**Comment by ptaoussanis** [comment]
Okay, gotcha.

So you'll either need to load-balance so that all of a particular user's connections end up on the same server (usu. what I'd recommend), or you'll need to maintain an index of uid->server-set.

You can maintain an index in Redis (a good choice), or anything else that you'd like.

> How to I get the message there?

How do you pass any message between servers? I.e. you'll want some kind of general-purpose server<->server messaging infrastructure. You can use the same infrastructure for coordinating cross-server Sente broadcasts.

> if it were implemented generically then other solutions could be plugged in.

As I understand your requirements, I don't think this is something that you'd want Sente to have anything to do with. There's standard, better, dedicated tools that you'll likely already have in place in a distributed environment; and they'd be perfectly well suited to use with Sente. I.e. Sente doesn't have any special/unusual requirements.

Does that make sense?

**Comment by bplatz** [comment]
If I'm not mistaken, the user's socket connection will be established before knowing the user-id, so the only way of getting them onto the same server would be to force a reconnection, and you'd be in the the business of storing an index of uid->server-set anyhow. Plus some sort of query parameter or header identifying each server, needing to be kept current, in a NGINX or HAProxy config for proper routing. Given I'm not missing something here, I think getting all user devices on a single socket server is going to be more error-prone than the alternative.

I think the unusual requirement Sente has is the core concept of a consolidated user-id to send messages to, regardless of the number of devices, across persistent socket connections. I don't have other things in my environment that have both of these "features" simultaneously and the usual tools that I'm aware of don't help much here.

I think the best solution I'm hearing to get this working in a load-balanced environment is:
- forgo the chsk-send! user-id feature of Sente (which really only works for a single server environment)
- replicate what Sente is doing with the conn_ atom in something like Redis
- set up listeners for the :uid-port/open & close events to keep active connections across the cluster current
- implement a pub-sub channel for each uid  for each server to subscribe to as needed
- implement a custom chsk-send! - like function that publishes to the pub-sub channel, not Sente itself. It will first check to see if any active clients are registered for that user.
- implement a listener for those pub-sub channels on each server which then uses the built-in chsk-send! to send to the locally connected clients (where the user-id is really the client-id, or variation thereof)

All of which I'm fine to implement and I think is the right way to best support load balancing of the Sente feature set however my desire of course would be improved native support.

If any of the steps I outline above you think could be improved, or I'm missing something else please let me know. Else feel free to close!

Thanks.

**Comment by ptaoussanis** [comment]
> If I'm not mistaken, the user's socket connection will be established before knowing the user-id

The user id is normally held in the session, so something that your load balancer may be able to access.

> I think the best solution I'm hearing to get this working in a load-balanced environment is

If you prefer to avoid by-uid load balancing, then what you've described sounds quite appropriate (and IMO entirely preferable to trying to squeeze some sort of native support into Sente itself).

One minor suggestion:

> implement a custom chsk-send! - like function that publishes to the pub-sub channel, not Sente itself. It will first check to see if any active clients are registered for that user.

No need to check first if active clients are registered (or keep that info synchronized); `chsk-send!` will noop against a uid not registered with the server.

Closing for now, best of luck! :-)

**Comment by luposlip** [comment]
How I'm trying to solve this situation myself, using different load balanced containers on AWS ECS, with Datomic as database system (if you're not aware, Datomic automatically distributes updated data to the connected containers (Datomic Peers):

1. Each container maintains a list of users connected to it (this is already there with `Sente`)
2. Whenever a user connects, a common list is maintained in Datomic
3. Whenever a user disconnects, the user is removed from the common list
4. Whenever an update from a user needs to be sent to other users, it starts by sending out the messages directly to the users connected to the _same_ container. Then the container reads the common list of connected users from Datomic. If some connected users are connected to _other_ containers, the messages for those users are stored in a common messages list (queue) in Datomic.
5. Workers on all containers regularly (say, every 15 seconds?) check this common message queue. If a message exist for a connected user, the message is sent to the user, and removed from the queue.
6. When a user disconnects/logs off, the list of waiting messages for that user is (permanently) removed from the message queue.

**Comment by ptaoussanis** [comment]
@luposlip Thanks for the info Henrik, I'm sure that'll come in handy as a reference for others. Cheers! :-)
