### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#138]
I'm aware that this is a difficult problem, but it would be nice to be able to have automated testing of Sente to ensure that everything works, particularly to explore the possible configuration space.

**Comment by danielcompton** [comment]
From the article:

> As a Pentester
> Check for Cross-Site WebSocket Hijacking attacks as soon as you notice any WebSocket based communication in the application you're analysing. As a side note, in case you already find Origin header verification present in the application, try to bypass it from victim's browser: When the server expects https://www.some-trading-application.com as the Origin, mount your attacks on https://www.some-trading-application.com.some-evil-attacker-application.com to test for obviously broken Origin header verifications.

> As a Security Consultant
> Make your clients aware of the requirement to always check Origin headers. Educate them to secure all WebSocket handshakes using random tokens (like protecting against CSRF attacks) or let them embed the authentication and/or authorization into the WebSocket protocol (avoid web session access).

> As a Developer
> Make sure you are aware of this attack scenario and know how to employ the countermeasures securely into your application (at least when you need to access the web session from the application part that uses WebSockets or when you otherwise try to transfer non-public data over that channel). Better try to avoid accessing the web session from the server-side WebSocket counterpart and separately handle authentication and/or authorization using tokens or similar techniques within your WebSocket protocol.

**Comment by ptaoussanis** [comment]
Hi Daniel,

> particularly to explore the possible configuration space.

Could you expand on what you mean by this exactly?

**Comment by danielcompton** [comment]
There are several different configuration options that Sente takes when making Channel Sockets, on the client and server, e.g. packer, and chsk-type. At the time I was thinking about testing them all combinatorially, but I don't think this would be necessary if there were tests on each interface.

**Comment by ptaoussanis** [comment]
It's been my general experience that we get better (easier + more accurate) QA for Sente by running the reference example against target server/s & browser/s.

I.e. my inclination/preference would usu. be beefing up the reference example to exercise more edge cases before trying to write traditional unit tests.

Would be happy to look over a PR though if you had something specific in mind that you felt would be better handled by a unit test?

**Comment by ptaoussanis** [comment]
Closing this for now, please feel free to reopen if you'd like to continue the discussion :-)
