### ISSUE TITLE
Sente server hanging

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#146]
Occasionally I'll observe Sente server appear to hang, and not respond to web socket messages from clients. This seems to only happen under very high message load. In the logs I can see that it is unpacking the messages on the server, so they are definitely being received, but not processed by my message handlers. Initial inspection of the chsk-recv queue showed messages in the queue.

My working hypothesis is that something is happening in the router go-loop which is causing the go loop to crash. I've added `:trace-evs? true` for logging, but haven't been able to reproduce the issue since I added this.

Has anyone seen this issue before and can help diagnose it further?

**Comment by ptaoussanis** [comment]
> Has anyone seen this issue before and can help diagnose it further?

I haven't, sorry.

> My working hypothesis is that something is happening in the router go-loop which is causing the go loop to crash.

That sounds like a reasonable place to start, though it shouldn't actually be possible to crash the router loop with a faulty handler.

To help diagnose, I might suggest creating your own router (duplicate the code from `start-chsk-router!`) and add some logic to detect+log if a message ever comes in but doesn't finish handling w/in a prescribed time window. You might also want to check your HTTP logs.

There's a lot of things that could cause a response to hang; first step would be checking logs to identify which system's the last to touch the event.

**Comment by ptaoussanis** [comment]
Hey @danielcompton, any update on this? Are you running Sente with Immutant?

**Comment by danielcompton** [comment]
Hey I'm using Sente with HTTP Kit so I don't think it's related to #150. Putting logging in showed some events were hanging while being processed. I put in a 5 second timeout to kill these long operations and log them. I haven't dug in too deeply to see exactly what the issue is yet. It seemed like an exception was being thrown somewhere and crashing the whole thing. I'll report back with more results when I have them.
