### ISSUE TITLE
Tomcat support

### ISSUE THREAD

**Issue by yatesco** [ptaoussanis/sente#148]
Has anyone had a go at providing a Tomcat adapter? Is this technically feasible and are there are pointers on how to do this?

Thanks!

**Comment by ptaoussanis** [comment]
Hi Colin,

There's no Tomcat adapter that I'm aware of. You can see [here](https://github.com/ptaoussanis/sente/issues/102) for examples/instructions on how to create one. Assuming Tomcat has the necessary hooks [not sure if it does?] - should be quite straightforward.

Before putting in the effort, I would caution you to check that your version of Tomcat actually supports the necessary amount of connection concurrency. Last I looked, Tomcat struggled with high persistent connection counts.

Cheers! :-)

**Comment by yatesco** [comment]
Thanks, I shall have a look :).

**Comment by ptaoussanis** [comment]
Closing this for now, please feel to reopen if you've got follow-up questions.

**Comment by yatesco** [comment]
Thanks Peter - as ever, real life got in the way of me looking at this.

**Comment by ptaoussanis** [comment]
No problem, understood :-) Feel free to open a PR at any stage and we can chat further. Cheers! :-)
