### ISSUE TITLE
Switching to reader conditionals and 1.7

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#149]
What are your thoughts/plans for updating Sente to 1.7 and using cljc? I'm not sure how far back/how long you want to support older versions of Clojure for?

**Comment by ptaoussanis** [comment]
Hey Daniel,

I like to try keep back-compatibility for at least 1 Clojure version whenever possible unless there's a compelling reason to break. Did you have something specific in mind?

Current plan is to move to .cljc sometime after Clojure 1.8, possibly. Likeliest reason to abandon that plan would be an important breaking change in ClojureScript which needs Clojure 1.7+.

Does that help / answer your question?

**Comment by danielcompton** [comment]
Yeah, definitely, thanks!

**Comment by danielcompton** [comment]
Now that 1.8 has been out for a while, would you be interested in updating to use reader conditionals?

**Comment by ptaoussanis** [comment]
W/in the next few months potentially, sure. May I ask: is there any reason for urgency? Now that the ref. example is split (no longer uses .cljx), this seems like a strictly implementation detail, no?

Not against it if there's a reason; just want to prioritise efforts. A conversion will realistically be at least an hour or two of someone's time.

**Comment by danielcompton** [comment]
I'm happy to do the work. I find cljx a bit hard to work with in Cursive, and symbol resolution in our app doesn't work well with CLJX files. There may be a few PRs coming up, and this would make it easier for me.

**Comment by ptaoussanis** [comment]
Okay, I'm on board if we target Sente v1.10, i.e. after v1.9 final is out? ETA: maybe ~2 weeks?

**Comment by ptaoussanis** [comment]
Apologies for the delay; haven't had any time to work on this during my trip. Will be back on Monday + should have a new release cut shortly after.

**Comment by ptaoussanis** [comment]
Resolved by #242
