### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by danielsz** [ptaoussanis/sente#15]
When I restart http-kit in my development process after having called `sente/make-channel-socket!, I see an error on STDOUT.

``` java
ri Mar 28 22:44:12 IDT 2014 [nREPL-worker-5] ERROR - increase :queue-size if this happens often
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@122c00b3 rejected from java.util.concurrent.ThreadPoolExecutor@6e1f117[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 7]
```

How should I go about gracefully shutting down all channel sockets with sente?

Graceful shutdown functionality will also be handy when [componentizing](https://github.com/stuartsierra/component) sente or integrating it in Stuart Sierra's [reloaded](http://thinkrelevance.com/blog/2013/06/04/clojure-workflow-reloaded) workflow.

**Comment by kgxsz** [comment]
Hi,

Was there ever any resolution to this issue? I'm trying to use the component workflow with sente and http-kit, but when reloading the server, I see:

```
[nREPL-worker-1] ERROR - increase :queue-size if this happens often
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6bfab899 rejected from java.util.concurrent.ThreadPoolExecutor@5b18eb8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 146]
```

I've played around with stopping the chsk-router before stopping http-kit, and the other way around, I've also included a timeout with http-kit's stopping function. But no dice.

Any ideas?

Thanks.
