### ISSUE TITLE
http-kit-adapter is not recognized as a valid adapter

### ISSUE THREAD

**Issue by timothypratley** [ptaoussanis/sente#152]
1.5.0
1.6.0-RC1

    (println "TYPE" (type http-kit-adapter)
             (satisfies? interfaces/IAsyncNetworkChannelAdapter http-kit-adapter))

TYPE taoensso.sente.server_adapters.http_kit.HttpKitAsyncNetworkChannelAdapter false

Caused by: java.lang.AssertionError: Condition failed in `taoensso.sente:?` [pred-form, val]: [((fn* [p1__3274#] (satisfies? interfaces/IAsyncNetworkChannelAdapter p1__3274#)) web-server-adapter), taoensso.sente.server_adapters.http_kit.HttpKitAsyncNetworkChannelAdapter@3e8eea59]

am I missing something?

**Comment by ptaoussanis** [comment]
Hi Timothy,

Is this possibly a REPL or class generation issue? http-kit-adapter _does_ implement interfaces/IAsyncNetworkChannelAdapter so if `satisfies?` is failing it seems likely the class generation's getting out of sync.

Have you tried the reference example?

**Comment by timothypratley** [comment]
Thanks Peter - yes removing my target directory resolved it :blush:

**Comment by ptaoussanis** [comment]
No problem, it's an easy issue to run into - cheers! :-)
