### ISSUE TITLE
No :client-id when using ajax long polling

### ISSUE THREAD

**Issue by akhudek** [ptaoussanis/sente#155]
When using ajax, the incoming request has: 

:client-id unnecessary-for-non-lp-POSTs

is there a reason the client-id isn't sent here? It would be nice to have the client-id on all incoming messages regardless of whether via websockets or ajax.

**Comment by ptaoussanis** [comment]
Hey Alexander, no particular reason - just that client-ids were originally an implementation detail and not needed here.

PR welcome! (Please add a comment above that the client-id here is just for use by the user + isn't required for Sente's implementation).

Cheers :-)

**Comment by akhudek** [comment]
Ok, thanks, I'll prepare one.

**Comment by ptaoussanis** [comment]
Hey there, I hope you don't mind- just took care of this myself quickly so that I could include it while cutting a release for #156

Thanks again for bringing this to my attention!

Change is in `[com.taoensso/sente "1.7.0-alpha3"]`, now on Clojars. Cheers :-)
