### ISSUE TITLE
[Perf] Cache Transit readers and writers

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#161]
Looking at [transit.cljx](https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/packers/transit.cljx#L36-L47) it seems like a new Transit reader and writer is created every time we call `pack` or `unpack`. Is there a reason why we've gone this route rather than creating a single writer and reader in each `FlexiPacker` instance? I'm aware it would be more tricky to write, but wondered if you'd tried this and it didn't work out for some reason.

**Comment by ptaoussanis** [comment]
Good catch Daniel, no reason - just lack of familiarity with Transit.

Indeed, this might be the reason the transit performance numbers have always looked so poor. Will fix this in a min.

**Comment by danielcompton** [comment]
A few notes I thought of when looking at this:

* You'll need to [.reset](https://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayOutputStream.html#reset()) the output stream after each `.pack`.
* I'm not sure how efficient it will be to reset the OutputStream each time, because I think it will start from a 0 size, not a buffer size of (say) 512 bytes. This means writing even moderately sized messages will cause it to grow several times.
* I think I would have found it more intuitive to create a Transit reader and writer myself rather than passing writer-opts and reader-opts to `->TransitPacker`. However then you have the issue of passing the input and output streams too, so perhaps the way it is is good.

**Comment by danielcompton** [comment]
Also http://the-paper-trail.org/blog/535/ is a good read on BAOS.

**Comment by danielcompton** [comment]
I had a look at Transit-clj source and [saw](https://github.com/cognitect/transit-clj/blob/master/src/cognitect/transit.clj#L331-L351) `read-handler-map` and `write-handler-map` which look like they are intended to be used for our purpose. I've asked a question on the [transit-format](https://groups.google.com/forum/#!forum/transit-format) mailing list for guidance on this issue as well.

**Comment by ptaoussanis** [comment]
Step 1 will be checking what the actual clj and cljs side construction costs are for the reader + writer, everything will depend on that.

I wouldn't get too concerned yet about specific influences on the total performance (like BAOS) until we've got a clear picture of where we're actually spending most of our time in practice.

Planning to cut a 1.7 pre-release later today. Will just cache the client-side reader/writer construction for now since that's trivial and won't hurt (it might well not help either; no idea yet what the construction costs are like).

On the server-side: will need some time to look at the Transit impl. We can maybe target Sente 1.8+ for that.

**Comment by danielcompton** [comment]
These are the recommendations from Tim Ewald - https://groups.google.com/d/msg/transit-format/RuJgGwSEVoo/6_Q3pnN4CAAJ

> In the Clojure implementation (which layers on the Java implementation), you have to make a separate reader or writer per stream you are working with (this is how the underlying JSON and msgpack processors work). So if you are writing data to different files, for instance, you'd make a new writer for each one. You could use the same writer over time if you want to write multiple chunks of transit data to a file. However, only one thread should be using a given reader or writer at one time, so coordinate accordingly. Calling write-handler-map or read-handler-map, caching the result, and passing it to each new reader or writer is the fastest way to manage handlers, but the difference isn't huge if you don't have a lot of custom handlers with long tag names.

**Comment by ptaoussanis** [comment]
Thanks! Will try investigate when I'm on Sente again. Appreciate all the assistance lately!

**Comment by ptaoussanis** [comment]
Update: don't use Transit myself + won't have time to investigate, so PRs welcome if anyone wants to take this on.

**Comment by ptaoussanis** [comment]
Prepping a 1.9 pre-release for later today, will try take a look at this while I'm at it.

**Comment by ptaoussanis** [comment]
Addressed in v1.9, though I'll note that I wasn't able to detect any practical improvements in perf. Could conceivably be noticeable for someone with lots of custom readers/writers though?
