### ISSUE TITLE
Documentation suggestion: clarify event-msg keys

### ISSUE THREAD

**Issue by prbroadfoot** [ptaoussanis/sente#164]
I wrote my own functions before realizing event-msgs had keys like `:id` `:?data` `:uid` etc. I think it would be worth listing those out in the documentation.

**Comment by danielcompton** [comment]
There is some documentation in the ns docstring https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljx#L16. Would this have been helpful, or is there more that you would like. I don't quite understand you would be writing if you didn't know there were keys in the event-msgs. Could you elaborate on this?

**Comment by ptaoussanis** [comment]
@danielcompton I think he probably meant just documenting more of the map keys in the table at https://github.com/ptaoussanis/sente#server-side-api (is that correct @prbroadfoot?)

If so, done! Thanks for the suggestion :-)

**Comment by prbroadfoot** [comment]
Yep thanks, looks good :+1:
