### ISSUE TITLE
sente/reconnect doesn't reset backoff-ms attempt number when chsk is closed

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#167]
From my testing, it seems like when calling `sente/reconnect` from a closed chsk, the backoff-ms attempt number isn't reset. The use case for this is displaying to the user the number of seconds before reconnecting, but giving them the option to reconnect faster if they want to. Currently, they can click a reconnect button, but if the channel socket is closed then nothing will happen, and Sente will try to reconnect on it's normal schedule.

Is this understanding correct, and is this a bug?

**Comment by ptaoussanis** [comment]
Hey Daniel,

Your understanding's correct - though the behaviour's not _technically_ a bug. `chsk-reconnect!`'s currently documented as: "Drops connection, allows auto-reconnect. Useful for reauthenticating after login/logout."

i.e. `chsk-reconnect!` was originally added as a quick hack as a way of dropping an existing connection to allow it to come back up. Didn't have in mind to allow it to speed up reconnect attempts of already-dropped connections, though that's a totally reasonable expectation from the name.

Would be happy for a PR to adopt the behaviour you're describing (+ update the docstring). Might not be an obvious/easy way to do this btw, so feel free to leave this to me if it's looking like it might be tricky.

Can try take a look at this myself at the weekend. Thanks for the report btw, the current behaviour's definitely surprising.

**Comment by danielcompton** [comment]
I'll have a look tomorrow with clearer eyes, but I think this might be part of the solution (also a note to self):

```clj
(reset! nattempt_ 0)
(.clearInterval js/window @kalive-timer_)
```

**Comment by ptaoussanis** [comment]
> but I think this might be part of the solution

The `nattempt_` looks good, but note that the keep-alive timer and backoff timer's are different. The backoff timer isn't currently accessible for cancelling; it's just an ephemeral thing created in `set-exp-backoff-timeout!`.

So we may need to add a new `backoff-timer_` atom (like `kalive-timer_`) that we _do_ track to allow cancelling.

**Comment by lfn3** [comment]
So I've taken a swing at this, and what I went with is adding the connect! fn to the record and using that directly while clearing the interval timer. This means the timer gets reset but the number of attempts doesn't (which seems desirable?).

Does that sound good to you guys?

**Comment by danielcompton** [comment]
Open a PR and we can take a look :)

**Comment by ptaoussanis** [comment]
Fixed in the SNAPSHOT I'm busy uploading now...
