### ISSUE TITLE
Server keeps disconnecting client

### ISSUE THREAD

**Issue by plt6356** [ptaoussanis/sente#169]
I'm trying to integrate Sente into my existing Clojure/ClojureScript application. I got the broadcast-every-ten-seconds example to work on the server, but the broadcast never makes it to the client, because the client keeps getting disconnected two seconds or so after the channel is opened. Here's what the server-side log looks like:

```
"Event: %s" [:chsk/uidport-open]
"Unhandled event: %s" [:chsk/uidport-open]
Broadcasting server>user: {:ws #{}, :ajax #{"a0a1b578-a21b-4a63-8107-a98432d9eaae"}, :any #{"a0a1b578-a21b-4a63-8107-a98432d9eaae"}}
"Event: %s" [:chsk/uidport-close]
"Unhandled event: %s" [:chsk/uidport-close]
Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
"Event: %s" [:chsk/uidport-open]
"Unhandled event: %s" [:chsk/uidport-open]
Broadcasting server>user: {:ws #{}, :ajax #{"a0a1b578-a21b-4a63-8107-a98432d9eaae"}, :any #{"a0a1b578-a21b-4a63-8107-a98432d9eaae"}}
"Event: %s" [:chsk/uidport-close]
"Unhandled event: %s" [:chsk/uidport-close]
Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
```

I can get the broadcast to show up if I manually go to https://localhost/chsk?client-id=a0a21484-2ece-4285-9ac1-1e1b762b90d2 and hit "Refresh" enough times, so the broadcast is being sent; the connection to the client just keeps getting closed. Is this a problem you've encountered before? Thanks

**Comment by ptaoussanis** [comment]
Hi there,

Some extra info that would be helpful for debugging:

* What version of Sente are you running?
* What web server are you using?
* Do you see the same behaviour when you run the default reference example?
* Do you see the same behaviour when you run the reference example with your particular web server?

**Comment by plt6356** [comment]
Hey, thanks. I'm running Sente 1.6.0 and HTTP-Kit 2.1.19.

I couldn't run the reference example because of compilation errors; I unfortunately don't remember exactly what they were, but IIRC it looked related to cljx being deprecated. I'll dig around for the exact error message when I have some more time tomorrow morning.

**Comment by plt6356** [comment]
Okay, here are the steps I followed for the reference example:

git clone https://github.com/ptaoussanis/sente
cd sente/example-project/src/example
emacs ./my_app.cljx &
cd ../..
lein start-dev

(lein then prints a large number of warnings, which Github won't let me attach because "Something went really wrong, and we can’t process that file", so here's a pastebin: http://pastebin.com/Q7dtJ3jX)

(Switch to the Emacs window)
C-x 3 to open a second window
M-x cider-connect, host localhost, port 51499

Emacs starts the Cider REPL, but prints a warning before the REPL prompt, saying:

WARNING: The following required nREPL ops are not supported: 
format-code format-edn ns-path refresh
Please, install (or update) cider-nrepl 0.9.1 and restart CIDER
WARNING: CIDER's version (0.9.1) does not match cider-nrepl's version (0.8.2)

(I could just edit the project.clj file to update the cider-nrepl version number, but here I tried to run the code exactly as-is for debugging purposes)

C-x o to return to my_app.cljx window
M-x cider-load-current-buffer
Emacs "No match" error, so I try:
M-x cider-load-buffer

At this point I think there's a compilation error, and line 27 and below of my_app.cljx gets red squiggly underlines. A stack trace appears in the Cider REPL, which I've copy-pasted here: http://pastebin.com/hATAm6pt

**Comment by ptaoussanis** [comment]
Sorry I haven't been able to assist with this, have my hands incredibly full atm. Basically: you shouldn't be seeing disconnects, and that's not currently a known issue with 1.6 and/or http-kit.

The likelihood is that something's configured incorrectly. The way I'd go about diagnosing that would be to first get the ref example working on your side, then you can do a diff with the ref example to see what changes you've made that may be having this effect.

Your stack trace indicates that your environment is failing to handle cljx forms correctly. Not sure what the specific Cider issue is that you're seeing here or if that might be the cause, would need to dig/Google.

In principle the ref example should just work using the default deps and the instructions at the top of the main ns.

Sorry I can't be of more help atm. Am considering moving Sente v1.8 to cljc which will hopefully help simplify tooling issues in future.

**Comment by plt6356** [comment]
Okay, thanks. For now, I'll try and dig around for another library to use. Am happy to help debug further when you have time, just let me know what else I could do to diagnose the errors.

**Comment by danielcompton** [comment]
@plt6356 debugging steps we need to be able to help further:

1. Get the demo application running (try just running in the terminal, not using Cider)
2. Test the demo application frontend against your server
3. Compare what is different between your app and the demo app
4. Paste client and browser side logs showing the issue in a gist somewhere.

**Comment by plt6356** [comment]
@danielcompton Hey, I think I've isolated the problem. I'm using nginx reverse-proxy for HTTPS, since HTTP Kit doesn't support encryption (http://www.http-kit.org/migration.html), and that seems to be causing issues. Here are the steps I followed to replicate:

git clone https://github.com/ptaoussanis/sente
cd sente/example-project/
emacs ./project.clj &

(add line to bottom of project.clj saying ":main example.my-app")

lein build-once
lein run

(At this point everything seems to work fine)

Go to src/example/my_app.cljx in Emacs
Edit line 320 from "(or port 0)" to "(or port 9090)"
Edit line 322 from "uri (format "http://localhost:%s/" port)]" to uri (format "https://localhost/" port)]
(I'm using the default nginx config from http://www.http-kit.org/migration.html here, which specifies port 9090)
Save, do lein run again

Now it starts connecting and disconnecting, with the successive :chsk/uidport-open and :chsk/uidport-close messages from earlier. Strangely, this only happens about half the time, I'm not sure why - the intermittency threw me for a bit. If I refresh the browser (pointing to https://localhost/) ten times, five times it'll work fine, and the other five I'll get the connect and disconnect errors.

Here's the Javascript console log (from one of the refreshes where it didn't work): https://gist.github.com/plt6356/6e8d7219e48edba59115

**Comment by ptaoussanis** [comment]
Just a quick note to mention that I use Sente myself with http-kit behind an https nginx reverse proxy w/o any problems.

You sure you have nginx configured correctly for WebSockets, etc.?

**Comment by ptaoussanis** [comment]
E.g. http://nginx.org/en/docs/http/websocket.html

**Comment by ptaoussanis** [comment]
> Strangely, this only happens about half the time, I'm not sure why - the intermittency threw me for a bit

Ref example randomly chooses Ajax or WebSockets at 50/50 probability

**Comment by plt6356** [comment]
@ptaoussanis Great, that fixes things with WebSockets. My own app still had problems with Ajax, but that turned out to be a CSRF issue - ring-anti-forgery was using an __anti-forgery-token param while the Ajax requests were using a :csrf-token param. Everything seems to be working now, so I'll close this out.

**Comment by ptaoussanis** [comment]
No problem, cheers! :-)
