### ISSUE TITLE
Bizarre interaction between Timbre and Sente

### ISSUE THREAD

**Issue by kenrestivo** [ptaoussanis/sente#175]
If I set log level in CLJS to (taoensso.timbre/set-level! :debug), sente works. 

If I set log level to :info, :warn, or :error, then sente does not work.

I'm still digging out the details, but this was kind of a surprise.

**Comment by ptaoussanis** [comment]
Hi Ken, you'll need to provide more details - e.g. what do you mean by "then sente does not work"?

Also, output from `lein deps :tree` might be helpful.

**Comment by kenrestivo** [comment]
More specifically, sente gets as far as establishing a handshake, so make-channel-socket! seems to be executing, but no messages go out the socket, which I'm doing at IWillMount in Om. It's a silent failure, my guess is there's some interaction between om and sente and timbre. This is with no optimization (dev mode) so I don't think it's closure getting confused.

The whole project is here http://github.com/kenrestivo/djdash if you want to see what's going on, and the calls which appear to either not be happening at all or failing silently are here: https://github.com/kenrestivo/djdash/blob/master/cljs-src/djdash/core.cljs#L414  Apologies in advance if I'm doing something dumb there.

It's a bit of a Heisenbug too, since turning on logging to see what's going on makes the problem go away.

**Comment by kenrestivo** [comment]
Nevermind, pilot error. Timbre doesn't execute code that is wrapped in a log level that's not relevant. I was wrapping important calls in debug. Not too surprising that they didn't execute unless that log level was reached.

So, I was doing something dumb. Fixed. Sorry for the noise.

**Comment by ptaoussanis** [comment]
No problem, thanks for confirming.
