### ISSUE TITLE
Interoperation with Websocket Input from Javascript

### ISSUE THREAD

**Issue by Ninerian** [ptaoussanis/sente#177]
Hello,

I just playing around with sente to get into websockets. I managed to get a small prototype working. It uses Clojure and ClojureScript. Now I want to connect via an external javascript app. 

My first attempts without sente, only with immutable websockets where successful. I could connect to the websocket port and communicate with it. 

What I want is an solution, to show the connected websocket clients in an ClojureScript app. But the clients are running by javascript. Is this possible?

**Comment by ptaoussanis** [comment]
So you want a Sente server running Clojure and clients that connect to that via Javascript? Would be possible if you reimplemented Sente's entire client in pure Javascript but not sure why one would want to do that exactly- have I misunderstood? There'd certainly be no easy way outside of a full Javascript reimplementation...

**Comment by Ninerian** [comment]
Thanks for your answer. I thought so. I now use the WAMP Protocol, which gives me the functionality, I want.
