### ISSUE TITLE
Segment message into chunks - optional "onProgress" callback/event

### ISSUE THREAD

**Issue by Frozenlock** [ptaoussanis/sente#178]
This has two purposes.

-----

Firstly, like #117, I can't send anything bigger than a few hundreds kb.
`http-kit` will fail catastrophically and `sente` will lose the connection.

In this case I know this is an `http-kit` [bug](https://github.com/http-kit/http-kit/issues/191). (It appears to have some PRs to solve this issue, but the project looks somewhat abandoned...)

Anyhow, segmenting the messages into smaller chunks would allow to bypass this limitation.

-----

Secondly, if the messages are segmented into chunks, it gives the opportunity to run an optional callback or launch an event at every chunk. One could then use this to closely follow and control the state of longer communications. 

Here is an example callback function:

```clj

(fn chunk-completed-callback
  [{:keys [completed-chunk total-chunks]}] ;; completed-chunk: 10, total-chunks: 35
  (if (= @instruction :stop)
    :drop-event ;; returning a certain keyword could cancel the download/upload
    (swap! download-state
           assoc
           :done completed-chunk))) ;; let the user know how far in the process he is.
```

**Comment by danielcompton** [comment]
This would increase the complexity of both client and server side Sente code. It's certainly one solution, but I wonder if there is a more elegant way of achieving this? Fixing the bug in httpkit would be another way.

In your example callback function, is that running on the client or server?

Not saying no, just opening a discussion :)

**Comment by Frozenlock** [comment]
Fixing the bug in http-kit should be done, but that still leaves the second feature lacking (chunks callback).

The example is client-side. (with some Reagent hints... `download-state`)
Tho it would be nice to have it server-side too.

The other possibility I see is to wrap the sending function and make a receiving event, which will re-dispatch once the message is reconstructed. The downside of this is that each user needs to re-implement it. The packing/unpacking will also have to happen twice. (The user needs to pack before the message can be segmented.)

**Comment by ptaoussanis** [comment]
Hey there, sorry for the delay responding - have been travelling.

Will try look into this w/in the next few days + get back to you!

**Comment by ptaoussanis** [comment]
Hi there,

> Firstly, like #117, I can't send anything bigger than a few hundreds kb.

Could you possibly try again using `[com.taoensso.forks/http-kit "2.1.20"]`?

> Secondly, if the messages are segmented into chunks, it gives the opportunity to run an optional callback or launch an event at every chunk. One could then use this to closely follow and control the state of longer communications.

Re: adding this as a feature (vs just working around the http-kit bug)- I'm not sure I see the utility to be honest (at least relative to the complexity cost).

Generally speaking- any data transfers large enough to benefit from chunking should probably be made via Ajax anyway (to benefit from HTTP caching, etc.). Sente's ideal data transfers are usually pretty small.

To clarify: you can still benefit from Sente's features as a coordination mechanism for larger transfers. E.g. the server does an async push to the client to signal the client to initiate an Ajax request for a large payload, etc.

HTTP's well designed for large transfers like this and starting to try to reimplement things like HTTP caching (or chunking) over WebSockets sounds to me like a bit of a bad (and unnecessary) path to start heading down.

Sente works great together with standard HTTP features; you can use each for its strengths. Does that make sense / address your use case?

**Comment by Frozenlock** [comment]
> Generally speaking- any data transfers large enough to benefit from chunking should probably be made via Ajax anyway (to benefit from HTTP caching, etc.).

In this case it was an upload. I'm not sure there's much benefit in HTTP for this.

> Sente works great together with standard HTTP features; you can use each for its strengths. Does that make sense / address your use case?

Yes. I was hoping to use a single endpoint (Sente's), but all in all in looks like adding a POST will be easier to maintain.

**Comment by ptaoussanis** [comment]
>  I'm not sure there's much benefit in HTTP for this.

Well, HTTP uploads will get you fully-baked upload progress for one :-) May also be more reliable.

> Yes. I was hoping to use a single endpoint (Sente's), but all in all in looks like adding a POST will be easier to maintain.

Just to clarify: the updated http-kit should work for your large uploads now if you prefer, just minus the HTTP-style progress.
