### ISSUE TITLE
Using Sente with Apache proxy

### ISSUE THREAD

**Issue by giorgio-v** [ptaoussanis/sente#183]
I opened this [issue](https://github.com/http-kit/http-kit/issues/241). I thought it could be useful to let you know, but feel free to close this if you think it’s not related to Sente and, if so, sorry for the noise.

**Comment by ptaoussanis** [comment]
Hi Giorgio,

So just to clarify: you're running Sente v1.6.0 or v1.7.0-RC1 using the http-kit server, and you're running it behind an Apache proxy.

You've also tried behind an nginx proxy.

Using either proxy, you're having trouble getting Sente to work with websockets - even with the [Reference example project](https://github.com/ptaoussanis/sente/tree/master/example-project).

For both proxies, you seem to have problems only with websockets (i.e. Ajax works fine).

Is all that correct?

If so, sounds like you might need to configure your proxy to correctly handle (proxy) websocket requests.

In the case of nginx, this will mean using a recent (ish) version of nginx and following the directions at http://nginx.org/en/docs/http/websocket.html. For Apache, I'm not sure (sorry)- but there's probably examples somewhere.

Does that make sense / help?

**Comment by giorgio-v** [comment]
That’s correct. I haven’t tried with the example project, yet. Some more data points / clarifications:
- With Apache, after a minute or so, the communication starts successfully; not so, with Nginx.
- I am not very knowledgable with Nginx, so I may very well be missing something. On the other hand, I basically copied the example from the http-kit web site.
- Looking around, it seems that some (most?) of the problems with WebSocket are solved by just using SSL. Is that your experience as well?

So, my current plan is this:
- Use a workaround (it’s the first demo of the first iteration, no biggie)
- Test with SSL (with Apache, first)
- Test with the sample project

**Comment by ptaoussanis** [comment]
Hi Giorgio,

Should work fine with or without SSL. Haven't ever used Apache with WebSockets myself, but nginx definitely works as a WebSockets reverse proxy and should do fine with the linked instructions.

To debug, I'd start by trying the reference example project (which should definitely work)- then try put your proxy in front of it and get that working. My first guess would be that your proxy isn't configured correctly to support WebSockets.

If you can get the reference example project working behind your proxy and your own project isn't working, then you know it's an application level issue and you can start looking for differences between the reference example and your own application.

Hope that helps! :-)

**Comment by giorgio-v** [comment]
I’ll do that as soon as I finish the workaround

**Comment by giorgio-v** [comment]
I forgot to add that I’m using version 1.6.0

**Comment by giorgio-v** [comment]
I get the same behavior with https://github.com/danielsz/sente-system + Apache. In the beginning it was erratic, but then I saw this https://github.com/ptaoussanis/sente/blob/master/example-project/src/example/my_app.cljx#L174 :smile:

**Comment by giorgio-v** [comment]
And the same goes with nginx with this configuration (probably broken, at this point?):
```
user   www  www;
worker_processes  1;

#error_log  /var/log/nginx/error.log;
#error_log  /var/log/nginx/error.log  notice;
#error_log  /var/log/nginx/error.log  info;

#pid        /var/db/nginx/nginx.pid;

events {
    # After increasing this value You probably should increase limit
    # of file descriptors (for example in start_precmd in startup script)
    worker_connections  1024;
}

http {
    include       /opt/local/etc/nginx/mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    upstream http_backend {
        server 192.168.1.16:3019;  # http-kit listen on 8090
        # put more servers here for load balancing
        # keepalive(resue TCP connection) improves performance
        keepalive 32;  # both http-kit and nginx are good at concurrency
    }

    server {
        location / {
            proxy_pass  http://192.168.1.16:3019;

            # tell http-kit to keep the connection
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;

            access_log  /var/log/nginx/xxxx.access.log;
        }
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   share/examples/nginx/html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443;
    #    server_name  localhost;

    #    ssl                  on;
    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_timeout  5m;

    #    ssl_protocols  SSLv2 SSLv3 TLSv1;
    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers   on;

    #    location / {
    #        root   share/examples/nginx/html;
    #        index  index.html index.htm;
    #    }
    #}

}

```

**Comment by giorgio-v** [comment]
And this works:
```
user   www  www;
worker_processes  1;

#error_log  /var/log/nginx/error.log;
#error_log  /var/log/nginx/error.log  notice;
#error_log  /var/log/nginx/error.log  info;

#pid        /var/db/nginx/nginx.pid;

events {
    # After increasing this value You probably should increase limit
    # of file descriptors (for example in start_precmd in startup script)
    worker_connections  1024;
}

http {
    include       /opt/local/etc/nginx/mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    server {
        listen 80;

        # host name to respond to
        server_name dev-aim-node3.local;

        location / {
            # switch off logging
            access_log off;

            # redirect all HTTP traffic to localhost:8080
            proxy_pass http://192.168.1.16:3000;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # WebSocket support (nginx 1.4)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }


}
```

I guess I can close it now?

**Comment by giorgio-v** [comment]
Thank you, Peter, really appreciate your help.

**Comment by ptaoussanis** [comment]
No problem, happy to hear you got it working :-)
