### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by danielsz** [ptaoussanis/sente#184]
I don't know what importance to attribute to the following warnings I'm seeing when compiling, so I thought I'd report them and leave that for you to judge:

```clojure
Dec 06, 2015 11:57:44 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /home/danielsz/.boot/cache/tmp/home/danielsz/clojure/twitterfu-unified/52r/8ego4h/main.out/taoensso/sente.js:1223: WARNING - unreachable code
}catch (e34747){if((e34747 instanceof Error)){
 ^

Dec 06, 2015 11:57:44 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /home/danielsz/.boot/cache/tmp/home/danielsz/clojure/twitterfu-unified/52r/8ego4h/main.out/taoensso/sente.js:1963: WARNING - unreachable code}catch (e34848){if((e34848 instanceof Error)){
 ^

Dec 06, 2015 11:57:44 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /home/danielsz/.boot/cache/tmp/home/danielsz/clojure/twitterfu-unified/52r/8ego4h/main.out/taoensso/sente.js:1989: WARNING - unreachable code
}catch (e34850){if((e34850 instanceof Error)){
 ^

Dec 06, 2015 11:57:44 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
```

**Comment by ptaoussanis** [comment]
Hi Daniel, I believe these are Closure compiler warnings + not anything to worry about.

What version of ClojureScript are you using? I've seen warnings like this come + go with different ClojureScript releases; each time I've dug they've turned out to be spurious. Will make a note to double check next time I'm on Sente though.

**Comment by danielsz** [comment]
Sure. 
My Clojurescript dependency reads like this:

```clojure
 [org.clojure/clojurescript "1.7.145"]
```

I plan to upgrade soon. Will report if anything of interest happens.

Thank you, @ptaoussanis!

**Comment by ptaoussanis** [comment]
Okay, investigated: warning was good; - in this case noting a potential performance optimization. Thanks for the report, hadn't seen this yet since I was on an older version of ClojureScript.

**Comment by danielsz** [comment]
Awesome!

Sente is central to my stack, so glad to hear it.
