### ISSUE TITLE
Reflection warnings on example project

### ISSUE THREAD

**Issue by codonnell** [ptaoussanis/sente#185]
I've cloned `master` and `v1.7.0` and tried to run the example project, but I get a bunch of reflection errors when I do `lein start-dev`, which you can see here: http://pastebin.com/CdLsHgzU. (`lein build-once` doesn't throw any warnings/errors.) I've tried removing my .lein/profiles.clj and deleting my maven cache, but neither had any effect.

Not sure what information is relevant here, but here's some:
leiningen version: `Leiningen 2.5.3 on Java 1.7.0_91 OpenJDK 64-Bit Server VM`
OS: Ubuntu 15.10

Let me know if you'd like me to provide any further information; I'd be happy to.

**Comment by ptaoussanis** [comment]
Hi Christopher,

These warnings aren't generated by Sente but by some of its dependencies. I'd also note that none of these reflections is worrying; they all happen in tooling where the cost of reflection doesn't mean much and where you actually often need to be reflecting to get stuff done.

Appreciate the check though :-)

**Comment by codonnell** [comment]
Hi Peter,

Thanks for your response. I wasn't able to `eval-buffer` in emacs and assumed with all of the warnings that the server wasn't working. In fact, I can just `require` the namespace and `(start!)` and everything works perfectly. I feel pretty silly. Thank you for the work you've put into this great project!

**Comment by ptaoussanis** [comment]
No problem, always good to check! Sente's example project enables reflection warnings as a matter of hygiene, it's possible you're just not used to seeing reflection warnings :-)
