### ISSUE TITLE
Getting sente up and running on Luminus project

### ISSUE THREAD

**Issue by favetelinguis** [ptaoussanis/sente#186]
I have found that there are not any turtorials setting up basic working instances of sente on luminus projects. Im trying to do just that in a project at: https://github.com/favetelinguis/sente-reagent-httpkit-luminus-base
However im just getting started myselfe with web development in Clojure and am having trouble getting things to work. Im able to send a message from the client but the message seems to never arive at the server where im logging all incoming messages. I would be very hapy if someone with more experience could have a look at the project and see if they can spot what is the problem. 

One of the big questions I have is wich middleware should and should-not be included, I have used http://yogthos.net/posts/2015-06-11-Websockets.html as a guide on what should be excluded, i have also included the middleware outlined in the sente getting started guide.

Any input is much apricated and I hope the project will be of help to someone else then me.

**Comment by ptaoussanis** [comment]
Hi Henrik, have you taken a look at Sente's [example project](https://github.com/ptaoussanis/sente/tree/master/example-project)? Might be a good place to start, should answer these kinds of questions for you :-)

Best of luck! Just let me know if you still run into any issues.

**Comment by favetelinguis** [comment]
Thanks for the reply, im starting to understand some about sente but still there are much I dont understand, below are some debugging information, maby you can help me expain if things are looking ok.

I added a watcher function on connected-uuids as such:
(add-watch connected-uids :watcher
  (fn [key atom old-state new-state]
    (timbre/info "-- Atom Changed --")
    (timbre/info "key" key)
    (timbre/info "atom" atom)
    (timbre/info "old-state" old-state)
    (timbre/info "new-state" new-state)))

And this is the output i get:
15-Dec-20 08:33:29 UnknownHost INFO [zwoop.routes.websockets] - -- Atom Changed --
15-Dec-20 08:33:34 UnknownHost INFO [zwoop.routes.websockets] - key :watcher
15-Dec-20 08:33:34 UnknownHost INFO [zwoop.routes.websockets] - atom clojure.lang.Atom@6890cc43
15-Dec-20 08:33:34 UnknownHost INFO [zwoop.routes.websockets] - old-state {:ws #{}, :ajax #{}, :any #{}}
15-Dec-20 08:33:34 UnknownHost INFO [zwoop.routes.websockets] - new-state {:ws #{:taoensso.sente/nil-uid}, :ajax #{}, :any #{:taoensso.sente/nil-uid}}

Lots of nil-uid and UnknownHost here, cant be good???

I also have set up a basic go-loop to log any incoming messages that is started in my app init:
(defn start-router! []
  (timbre/info "start-router called")
  (go-loop []
    (when-let [msg (<!! ch-chsk)]
      (timbre/info "Recived: " msg))
    )
  )

However no messages are printed even thogh I can see in Chrome that messages are send on the websocket.

Any recomendations on what to do next to find the problem?

**Comment by favetelinguis** [comment]
Strange start-router! code is hidded for me and i can only see it if i edit the message. Everything look fine for others?

**Comment by ptaoussanis** [comment]
Hi Henrik,

> Strange start-router! code is hidded for me and i can only see it if i edit the message. Everything look fine for others?

You need to wrap your code segments in a ````clojure <your-code>```` Clojure block.

> Lots of nil-uid and UnknownHost here, cant be good???

UnknownHost isn't a problem, just means your local environment doesn't have a hostname configured. The `nil-uid is also expected for users/clients that haven't had a uid assigned. Please see the example project and [FAQ](https://github.com/ptaoussanis/sente#what-is-the-user-id-provided-to-the-serveruser-push-fn) for more info.

> However no messages are printed even thogh I can see in Chrome that messages are send on the websocket.

Please see the example project for an example of how to setup a router, etc.

Let me know if anything there is unclear? Best of luck, cheers :-)
