### ISSUE TITLE
HTTP requests are incorrectly responded with server broadcasts

### ISSUE THREAD

**Issue by martinhynar** [ptaoussanis/sente#188]
Hi, I noticed interesting behavior on this setup: haproxy - 2 backend apps with liberator-based REST and sente-backed UI (ajax only). I added there a broadcaster that send some update to all connected clients every few seconds:

```
(defn start-broadcaster! [connected-uids chsk-send!]
  (go-loop []
    (doseq [uid (:any @connected-uids)]
      (chsk-send! uid
                  [:server/broadcast
                   {:reason  :update
                    :to-whom uid}]))
    (<! (timeout timeout_))
    (recur)))
```

I can't see any error on server side, haproxy log shows nice 200-OK-responses, also on UI side there were no problems, but on REST client side sometimes responses are containing data from that broadcast instead of the one expected.

I have no evidence to say that sente is culprit, rather I wanted to share this behavior somewhere to wider audience.

**Comment by ptaoussanis** [comment]
Hi there,

> on REST client side sometimes responses are containing data from that broadcast instead of the one expected.

Sorry, don't follow this - could you possibly rephrase this and/or show an example?

Assuming you're trying to debug something, have you tried the [reference example project](https://github.com/ptaoussanis/sente/tree/master/example-project) to see if you can reproduce there?
