### ISSUE TITLE
how to send ring request with client id from javascript

### ISSUE THREAD

**Issue by mgrabmair** [ptaoussanis/sente#190]
I am writing a larger database server application that exposes services via sent to my own Clojure(script) applications but I need to make it usable through Javascript & Ajax for our collaborators. My basic jQuery test case below ...

```
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
$(document).ready(function(){
        $("button").click(function(){
            $.ajax({
                type: "GET",
                url: "http://127.0.0.1:3001/chsk", 
                data: {
                "clientId" : "foo"
                },
                dataType: 'jsonp',
                success: function(result){
                $("#div1").html("it worked ...");
                }});
            });
        });
</script>
</head>
<body>

<div id="div1"><h2>Let jQuery AJAX Change This Text</h2></div>

<button>Get External Content</button>

</body>
</html>
```

... produces a server-side error because of a missing client id:

```
Wed Jan 20 03:54:29 CET 2016 [worker-1] ERROR - GET /chsk
clojure.lang.ExceptionInfo: Client's Ring request doesn't have a client id. Does your server have the necessary keyword Ring middleware (`wrap-params` & `wrap-keyword-params`)? {:ring-req {...  :session/key "18e46b42-d213-41c6-a378-a11d847362fc", :query-params {"callback" "jQuery111308303150818683207_1453258468398", "clientId" "foo", "_" "1453258468399"}, :content-type nil, :character-encoding "utf8", :uri "/chsk", :server-name "127.0.0.1", :query-string "callback=jQuery111308303150818683207_1453258468398&clientId=foo&_=1453258468399", :body nil, :multipart-params {}, :scheme :http, :request-method :get, :session {:ring.middleware.anti-forgery/anti-forgery-token "..."}}}
```

Naming the client id "client-id" will not work because json does not accept the hyphen in there. 

What am I doing wrong? I am not really fluent in Javascript or jQuery, so there may be an obvious solution I am missing.

**Comment by danielcompton** [comment]
Hi @mgrabmair, the Sente client is designed to be used from ClojureScript more than plain JavaScript. While it might be possible to make this work, you're probably going to have to do some work. There's a few options I can see here:

1. Get your collaborators to use ClojureScript too. Probably not really an option though :)
2. Write a ClojureScript wrapper around Sente to expose the functions that you'd need. This would create a Sente client for you and manage the connections, client id, e.t.c.
3. Do your collaborators need to call the Sente chsk server, or could you create a new endpoint for them to call directly? If they're not going to be using web sockets, it might make more sense to make a new endpoint.

Just some thoughts.

**Comment by mgrabmair** [comment]
Thanks Daniel. 

I may try creating a new route, but the amount of data that needs to be sent from client to server may be prohibitively large (on the order of a couple of megabytes). I am lacking experience to assess whether this is a practical solution.

However, I very much like the idea of a Clojurescript wrapper that exposes just enough functions to Javascript so that it can be framework-agnostic and runs a proper socket connection in the background. It also would have the benefit that I only need to write the code once for my own application and then just put a JS callable varnish on top of it.

Thanks, this was very helpful!

**Comment by danielcompton** [comment]
Sente isn't really designed for large payloads. While 1MB is probably still fine, a separate endpoint is likely to be a better option (I think).

**Comment by mgrabmair** [comment]
I just set up a new endpoint using Ring/Compojure and it works so far. I learned quite a bit from this. Thanks again!

**Comment by ptaoussanis** [comment]
Hey there,

Just to expand on something Daniel correctly pointed out (thanks again @danielcompton!)- 

> Sente isn't really designed for large payloads. While 1MB is probably still fine, a separate endpoint is likely to be a better option (I think).

For large transfers, would generally suggest just using Ajax since that way you get the usual HTTP caching, etc. Sente has an `ajax-call` function which you might find handy if you're just looking for a simple Ajax API in these kinds of cases (larger payloads, etc.).

**Comment by mgrabmair** [comment]
Thanks for the information. It's really useful for me as my experience in Javascript-based web  development is limited and fairly outdated. I really like working with Sente but I have to understand the situation it was born into ;)
