### ISSUE TITLE
mistake in landing page example

### ISSUE THREAD

**Issue by shaulid** [ptaoussanis/sente#197]
this line should also be added to existing project to use the given example:

[taoensso.sente.server-adapters.http-kit :refer (sente-web-server-adapter)]
(taken from the first full example)

**Comment by shaulid** [comment]
Sorry, I found it's there:
;; [taoensso.sente.server-adapters.http-kit      :refer (sente-web-server-adapter)]
but it is commented so my eyes somehow skipped it.

**Comment by ptaoussanis** [comment]
No problem, thanks for the update :-)
