### ISSUE TITLE
Which HTTP server should I choose?

### ISSUE THREAD

**Issue by docent** [ptaoussanis/sente#200]
Hi there, I'm planning to use sente on Heroku, and I'm not sure which HTTP server should I go with.

I am apprehensive of http-kit because as I see there some unfixed critical issues, i.e. [#148](https://github.com/http-kit/http-kit/issues/148). 

Immutant seems to heavy for me, so I seem to be left with two options:
- Wait for issues in http-kit to be fixed
- Use nginx-clojure and try to make it run on Heroku (not sure how complicated this is)

Any advice would be really welcome!

**Comment by tobias** [comment]
@docent - I'm curious about what seems heavy about Immutant? You can use `org.immutant/web` all by itself, and it just wraps [Undertow](http://undertow.io/), which is a pretty light server. Are you concerned about memory footprint? disk footprint? the number of dependencies?

**Comment by ptaoussanis** [comment]
@docent Hi Michal- any of the three should be suitable for production in most cases, I believe. Also, they're pretty easy to switch between so I'd encourage you to maybe just pick one and try. If you run into problems in testing, you can try another w/o much hassle.

Re:  [#148](https://github.com/http-kit/http-kit/issues/148) - that definitely needs addressing. It's unfortunately blocked on http-kit's author atm so can't say when it'll be fixed. Anecdotally, have not experienced the problem myself so not sure how wide spread it actually is.

**Comment by docent** [comment]
@tobias, indeed it seems more modular in version 2. I was initially put off by the presence of JBoss-affiliated libraries (such as Infinispan) but if you're saying it is possible to use it without them, I might as well give it a shot, especially that it has an example for Heroku. Thanks.

@ptaoussanis seems that the problem is mostly reproducible under high load. Better safe than sorry I guess :) I'll start with Immutant and if the bug gets fixed at some point, I might switch.

Thanks for your suggestions!

**Comment by ptaoussanis** [comment]
No problem, and that sounds good :-) Closing but please feel free to reopen if you have any follow-up questions.
