### ISSUE TITLE
websocket on remote server ? 

### ISSUE THREAD

**Issue by jdkealy** [ptaoussanis/sente#202]
I'm having load balancing issues and thought I could perhaps create a dedicated web socket server. 

I thought I could perhaps specify the host and port in the client cljs. 

```
(let [{:keys [chsk ch-recv send-fn state]}
      (sente/make-channel-socket! "http://localhost:3001" ; 
       {:type :auto ; e/o #{:auto :ajax :ws}
       })]
  (def chsk       chsk)
  (def ch-chsk    ch-recv) ; ChannelSocket's receive channel
  (def chsk-send! send-fn) ; ChannelSocket's send API fn
  (def chsk-state state)   ; Watchable, read-only atom
  )
```

this results in 
ws://localhost:3000/http://localhost:8080/chsk?client-id=2e8eef8c-3d2f-43bd-b17a-1ab3742194a0' failed: Error during WebSocket handshake: Unexpected response code: 404

As I'm new to websockets in general, A: would this be an ok approach and B: would there be a way to do this with sente ?

**Comment by theasp** [comment]
You can specify the host using the `:host` option, in the same map where you have `:type :auto`:
``` clojure
    :host           ; Server host (defaults to current page's host)
```

In your code you are specifying the path to the chsk relative to the root of the host, which is why it's trying that malformed URL.

The URL that sente will use is derived using:
``` clojure
(defn- get-chsk-url [protocol chsk-host chsk-path type]
  (let [protocol (case type :ajax protocol
                            :ws   (if (= protocol "https:") "wss:" "ws:"))]
    (str protocol "//" (enc/path chsk-host chsk-path))))
```

**Comment by ptaoussanis** [comment]
@theasp Thanks Andrew!

Closing for now, please feel free to reopen if you're still having issues.
