### ISSUE TITLE
Handling multiple client connections to different Sente servers

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#203]
It seems like there is no impediment to using Sente to create multiple independent Sente connections to different websocket servers, as `make-channel-socket-client!` returns a channel socket, and there is no state defined in the taoensso.sente namespace. Are there any gotchas I need to watch out for?

**Comment by ptaoussanis** [comment]
Hey Daniel, no gotchas that I can think of - should work as you expect. You can create multiple simultaneous chsk clients to different servers or to the same server.

**Comment by danielcompton** [comment]
Coolio, thanks!
