### ISSUE TITLE
Detect and / or avoid multiple connections from the same browser

### ISSUE THREAD

**Issue by giorgio-v** [ptaoussanis/sente#204]
I’m investigating the possibility of limiting the sessions from any given client to one or, at least, being aware of the fact. My understanding is that there is no way to do this, but I could be completely wrong.

**Comment by danielcompton** [comment]
@giorgio-v you would need to provide additional information in the initial websocket creation ([`:params`](https://github.com/ptaoussanis/sente/blob/v1.8.0-beta1/src/taoensso/sente.cljx#L1020)). You'd then need to maintain some identity across tabs. A cookie might be useful here.

**Comment by giorgio-v** [comment]
Ah thank you! Really useful. :)
