### ISSUE TITLE
ERROR - required "taoensso.sente" namespace not provided yet goog.require('taoensso.sente');

### ISSUE THREAD

**Issue by SlightlyCyborg** [ptaoussanis/sente#205]
SEVERE: /Users/collinbell/Projects/t-413/face/target/cljsbuild-compiler-0/face/control.js:4: ERROR - required "taoensso.sente" namespace not provided yet goog.require('taoensso.sente');
Any idea on why this would be happening?

**Comment by danielcompton** [comment]
Have you tried lein clean? Where is this happening? We're going to need more info to help debug this.

**Comment by ptaoussanis** [comment]
Thanks for handling this @danielcompton-

@SlightlyCyborg: I'd add only that `goog.require` errors are often a sign that there's something off with how you're compiling and/or pulling in your ClojureScript output (your :optimizations level, etc.). That's all a bit beyond the scope of a Sente but there's more info at the [ClojureScript Quick-Start guide](https://github.com/clojure/clojurescript/wiki/Quick-Start) 

You may also like to try Sente's reference example project to see one way of configuring your project.

Good luck, cheers! :-)

**Comment by SlightlyCyborg** [comment]
Thanks for the quick response. I am sorry to have cluttered up your issues here as this is a general clojurescript issue. The problem I realized was that I killed cljsbuild mid compile which left sente.js in the target completely empty. A clean was all I needed.

**Comment by ptaoussanis** [comment]
No problem, happy you've got it solved :-)
