### ISSUE TITLE
relative paths in make-channel-socket-client!

### ISSUE THREAD

**Issue by Sohalt** [ptaoussanis/sente#206]
I would like to be able to specify a relative path in `make-channel-socket-client!` as the first argument.

I have an application with an URL scheme like `/game/:id/` and create a new channel for each game instance. I now would like the clients running under `/game/:id/` to connect to `/game/:id/chsk` without having to look up the location myself in the client.

I am not sure whether I am using sente as intended.
Maybe the idiomatic way to solve this problem would be to have a single application wide channel and have the game instances send their id with each event, although that would move the routing of the events to the appropriate game state into the event handler of that single channel.
Any comments on this would be much appreciated.

**Comment by danielcompton** [comment]
Hi @Sohalt, on the server, a channel socket corresponds to a ring handler. You specify `path` as the first argument to `make-channel-socket-client!`. In theory I think you could mount your ring handler to a path where the path takes a parameter. I'm not sure exactly what the outcome would be there, but you might be able to use this option to create one go loop per game.

**Comment by Sohalt** [comment]
Not sure if I understand you correctly, but I think that is already what I have set up.
Currently my server side setup looks something like this:
```clojure
(defroutes app-routes
  ; other routes…
  (context "/game/:id" [id]
    ; other routes…
    (GET "/ws" ring-req ((get-in @handlers [id :ajax-get-or-ws-handshake-fn]) ring-req))
    (POST "/ws" ring-req ((get-in @handlers [id :ajax-post-fn]) ring-req)))
   ; other routes…
)
```
where `handlers` is an atom containing a map from ids to maps with the sente handlers.

Now on the client I the relevant code currently looks like this:
```clojure
(defn path [] (-> js/window .-location .-pathname))

(let [{:keys [chsk ch-recv send-fn state]}
      (sente/make-channel-socket-client! (str (path) "/chsk") {:type :auto})]
  (def chsk       chsk)
  (def ch-chsk    ch-recv) ; ChannelSocket's receive channel
  (def chsk-send! send-fn) ; ChannelSocket's send API fn
  (def chsk-state state)   ; Watchable, read-only atom
  )
```
This works ok, but my complaint is, that I have to explicitly build the absolute path myself from `window.location.pathname + "/chsk"` whereas I would like to be able to simply specify a relative path to `sente/make-channel-socket-client!` by providing a first argument without a leading slash like `(sente/make-channel-socket-client! "chsk" {:type :auto})`.

**Comment by theasp** [comment]
Hi @Sohalt, I'm not sure I see a downside to creating the absolute path the way you currently are.  Having Sente convert to an absolute path would push more logic into Sente, and wouldn't map well to having a non-browser based client.

I am actually going to adopt your approach for something I am developing.  Thanks for sharing it.

**Comment by Sohalt** [comment]
My initial thought was that maybe the WebSocket standard allowed for relative paths when establishing a connection from JavaScript. Because that seems not to be the case I agree with you that this would push unnecessary logic into sente. Additionally I start to think more and more that my approach is not very idiomatic, but for now I'm sticking with it till I have a better understanding of what the problems might be.
