### ISSUE TITLE
js/window and Node.js

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/sente#210]
The previous issues and original issue creator all seem to be 404'ing atm (?):
https://github.com/ptaoussanis/encore/issues/21
https://github.com/ptaoussanis/sente/issues/209

Not sure if that's a temporary glitch or not - certainly wasn't an intentional delete from my end.

In any case, please feel free to follow up here in the meantime if anyone has any feedback. 

Question was: is it possible to run Sente with a Node.js server given that Sente's code base makes use of `js/window`? Are there any special steps that need to be taken? And/or could/should Sente make any changes to help smooth things over for Node users?

I don't use Node myself so have no clue on any of this. Pinging @theasp, @matthiasn for advice (no urgency).

Thanks!

**Comment by danielcompton** [comment]
https://github.com/ptaoussanis/encore/issues/21 is showing up for me now.

**Comment by theasp** [comment]
Hi Peter,

There must be something going on here I don't understand.  What part of Sente uses js/window for the server?

**Comment by ptaoussanis** [comment]
Okay, the earlier issues are accessible again so looks like it was a GitHub glitch - will close here to continue the discussion at https://github.com/ptaoussanis/sente/issues/209
