### ISSUE TITLE
CSRF defaults no longer work

### ISSUE THREAD

**Issue by timothypratley** [ptaoussanis/sente#211]
upgrading from
[ring/ring-defaults "0.1.5"]
to
[ring/ring-defaults "0.2.0"]
Prevents Sente from finding the CSRF token

**Comment by ptaoussanis** [comment]
Hi Timothy, thanks for the report. Could you provide any other details? Are you getting a warning? Was there a breaking change in ring-defaults 0.2.0?

**Comment by timothypratley** [comment]
I'm just really confused right now o_O

Short story is started a new project which is very similar to another project,
but am getting "WARN [taoensso.sente:719] - SECURITY WARNING: no CSRF token available for use by Sente" in the new one but not in the old one.
Only difference I could see is the ring-defaults version,
but it was a red herring sorry for the noise.

I need to take a fresh look at this in the morning...
will update with more info later

**Comment by ptaoussanis** [comment]
No problem, just let me know if there turns out to be something I can assist with.

**Comment by timothypratley** [comment]
Thanks! :)

I finally have a real clue now...
It is something to do with having a session.
My routes look like this:

```
(defroutes routes
  (GET "/" req (response/content-type
                 (response/resource-response "public/index.html")
                 "text/html"))
  (GET "/status" req (str "Running: " (pr-str @(:connected-uids channel-socket))
                          "::" (pr-str req)))
  (GET  "/chsk" req ((:ajax-get-or-ws-handshake-fn channel-socket) req))
  (POST "/chsk" req ((:ajax-post-fn channel-socket) req))
  (route/resources "/")
  (route/not-found "Nnt found"))
```

Loading up /index.html does not establish a session it seems.
If I hit the /status endpoint, the first time it has an empty session, the second time it has a CSRF token, and from then I can use sente without the warning.

So not really a Sente problem at all, just a session thing which I don't understand yet.

**Comment by ptaoussanis** [comment]
> Loading up /index.html does not establish a session it seems.

Not sure if there's other context that might be missing (?), but please note that from this snippet alone there's nothing here in your index route that would set a session.

If you want `/` to set a session, you'd need/want some middleware or a `:session` key as part of the `/` response. Does that make sense?

In case it's handy, I'd also point to the [Sente reference example](https://github.com/ptaoussanis/sente/tree/master/example-project).

**Comment by timothypratley** [comment]
Yup that make sense.

I was surprised that the GET to /chsk doesn't cause ring to attach a session with an anti-forgery token, whereas a call to /status does cause it to attach one (at least that's what it seems like, though I must be wrong about this).

The full context is here just for reference.
https://github.com/timothypratley/snakelake/blob/master/src/snakelake/server/routes.clj
