### ISSUE TITLE
AJAX channel not working with CORS

### ISSUE THREAD

**Issue by timothypratley** [ptaoussanis/sente#212]
Code is here: https://github.com/timothypratley/snakelake/blob/master/src/snakelake/server/routes.clj

Routes are wrapped in CORS, and correctly attach "Access-Control-Allow-Origin" header:

```
Request URL:http://localhost:3000/chsk?_=1458367729937&client-id=4d0631a7-8e9e-4586-897d-5a749b1dc103&handshake%3F=true
Request Method:OPTIONS
Status Code:200 OK
Remote Address:[::1]:3000
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:X-Requested-With
Access-Control-Allow-Methods:DELETE, GET, POST, PUT
Access-Control-Allow-Origin:http://localhost:3449
```

But the sente socket fails when using :ajax

```
XMLHttpRequest cannot load http://localhost:3000/chsk?_=1458367723978&client-id=4d0631a7-8e9e-4586-897d-5a749b1dc103&handshake%3F=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3449' is therefore not allowed access.
core.js:165 WARN [taoensso.sente:946] - Chsk is closed: will try reconnect (1)
```

```
(defn get-chsk-url
  "Connect to a configured server instead of the page host"
  [protocol chsk-host chsk-path type]
  (let [protocol (case type :ajax protocol
                            :ws   (if (= protocol "https:") "wss:" "ws:"))]
    (str protocol "//" config/server chsk-path)))

(defonce channel-socket
  (with-redefs [sente/get-chsk-url get-chsk-url]
    (sente/make-channel-socket! "/chsk" {:type :ajax})))
```

**Comment by ptaoussanis** [comment]
Hi Timothy,

Could you confirm that neither of the following are helpful in your case?:
https://github.com/ptaoussanis/sente/issues/130
https://github.com/ptaoussanis/sente/issues/137

Could you also please provide the version of Sente that you're running? Thanks! :-)

**Comment by timothypratley** [comment]
Hi Peter,

I'm using [com.taoensso/sente "1.8.1"]

{:type :ajax :ajax-opts {:with-credentials? true}} didn't seem to help... but the fact that someone had success with this suggests I need to think about it more deeply and build a smaller example.

**Comment by ptaoussanis** [comment]
Hi Timothy, sorry for not responding to this yet - I don't use CORS myself so would need to dig + just have my hands a bit full atm.

**Comment by timothypratley** [comment]
Hi Peter,

Sorry for not being clear... Please don't waste your time looking into it, I was just curious if it was supported or if anyone had tried it. Thanks for the links they were helpful.

I am not that interested in AJAX seeing Websocket support seems great these days. I was just trying to understand how it all works. Realistically I don't think it is a good idea to be doing what I was trying to do (AJAX channel over CORS), the motivation was simply to use Heroku as a channel server, but use a static host such as github pages as the frontend. Which actually works great for WebSockets, but I wasn't having much luck with AJAX.

If I ever do return to this in earnest I'll make a minimal example before bugging you, promise!

Thanks for making a great library, I really want to see more people use it because I've found it super helpful in both work and fun projects. And thanks for answering even the most cryptic questions helpfully :)


Regards,
Timothy

**Comment by ptaoussanis** [comment]
>  I was just curious if it was supported or if anyone had tried it.

Ahh, gotcha- I believe so, but would need to dig to make sure and/or identify possible problems in your specific case.

> Thanks for making a great library, I really want to see more people use it because I've found it super helpful in both work and fun projects. And thanks for answering even the most cryptic questions helpfully :)

You're very, very welcome- thanks for saying so! And zero problem re: questions :-)

Will wait on you to reopen this if you'd like more input later. Cheers!
