### ISSUE TITLE
Websockets not working behind AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by DCWoods** [ptaoussanis/sente#222]
Hi, I'm not sure whether this is the right place to raise this issue, but I've been trying to get this working for a month with no success, and despite using all my googling ability I haven't found anyone with the same setup or problem.

I'm trying to use sente in my app, which is running in a docker container in a multi-container docker environment on AWS Elastic Beanstalk.  Nginx is running as a reverse proxy in a second container. Because the Elastic Beanstalk load balancer strips out the client information I have enabled proxy protocol on the ELB, and I think this is the source of the problem, but I haven't figured out how to fix it.

I've got the sente reference project working in this configuration, and the ajax connections work fine, but the websockets connections fail. My modified reference project is [here](https://github.com/DCWoods/sente-example), along with instructions on the changes I've made to get it working. My best attempt to get it working can be seen live [here](http://sente-example-env.ap-southeast-2.elasticbeanstalk.com).

I've tried every nginx configuration I can think of or find suggested anywhere. I've tried compiling http-kit from source so I can stick logging messages everywhere. I've even tried recompiling nginx into a docker container myself, with slightly modified c source code to capitalise the "Upgrade" connection header (didn't work).  All I can think is that the websocket connection needs some header that is getting modified or stripped somewhere along the way, or possibly one of the stages is forcing the connection closed at some point.

At this point I'm going insane, and I would appreciate any help or suggestions to get sente working.

**Comment by ptaoussanis** [comment]
Hi David,

Have no particular experience with Beanstalk + have my hands very full atm so can't be of much help there. Have you tried confirming that your nginx config works correctly on a local/non-Beanstalk instance?

i.e. would start debugging by confirming that your nginx config is correct in principle, then start adding in extra layers one by one till you can see what's breaking your websockets.

Best of luck, sorry I couldn't be more assistance!

**Comment by DCWoods** [comment]
I figured out what was wrong... needed to add `:proxy true` to the ring site defaults. I've updated my example, which is working in this configuration now: [https://github.com/DCWoods/sente-example](https://github.com/DCWoods/sente-example)

**Comment by ptaoussanis** [comment]
Hey David, happy to hear you managed to solve this - thanks for following up! 

PR would be very welcome to add your project to https://github.com/ptaoussanis/sente#example-projects
