### ISSUE TITLE
Baked in example project not working

### ISSUE THREAD

**Issue by Latros** [ptaoussanis/sente#223]
Unsure whether this is something wrong with my machine or not, but when I clone the repo, `cd` into `example_project`, and run `lein start` as recommended, I get...

https://gist.github.com/Latros/18f52ed98504b1d3e3c7c329c1c5a371

**Comment by ptaoussanis** [comment]
Hi Sam,

The example project is working on my side; would suggest checking your Lein version, profiles, and any plugins/middleware/etc.

Cheers :-)

**Comment by Latros** [comment]
You're absolutely right, thanks @ptaoussanis ! My lein profile was all messed up and I just happened to mess it up right before trying out Sente. Thanks again! Sente is great so far :)

**Comment by ptaoussanis** [comment]
No problem, best of luck :-)
