### ISSUE TITLE
Sente works with react-native! [TODO: add a small example project]

### ISSUE THREAD

**Issue by glittershark** [ptaoussanis/sente#229]
I just got it working and I'm really excited. Not an issue, just wanted to share my excitement with you (and let you know in case you want to advertise it in the README)

**Comment by ptaoussanis** [comment]
Hi Griffin,

Heh heh, not at all- that's the best kind of issue! ;-) And thanks for the confirmation.

Would love to accept a PR at some point if you felt like linking to a small example project, etc. at https://github.com/ptaoussanis/sente#example-projects?

**Comment by glittershark** [comment]
Don't see why not! I'll do that this weekend if I have time

**Comment by ptaoussanis** [comment]
Awesome, thank you! Looking forward to checking it out myself too :-)

**Comment by TerjeNorderhaug** [comment]
Congratulations on getting Sente to work with react-native! Looking forward to check out the example project.

**Comment by TerjeNorderhaug** [comment]
I also got it working. Had to change the project dependencies though:

[com.taoensso/encore "2.53.0"]                                                                              
[com.taoensso/sente "1.9.0-SNAPSHOT" :exclusions [com.taoensso/encore]]

**Comment by ptaoussanis** [comment]
@TerjeNorderhaug Thanks for the confirmation Terje. Please note that master (snapshot) is likely unstable though; would recommend using one of the tagged releases (latest is 1.8.1).

Just travelling atm, but will cut a 1.9 alpha next week when I'm settled again.

**Comment by ptaoussanis** [comment]
Have officially reopened this in case anyone feels like adding an example project for react-native.

Thanks, cheers! :-)

**Comment by TerjeNorderhaug** [comment]
Verified `[com.taoensso/sente "1.9.0-beta1"]` works with React Native. No longer needs `:exclusions`.

**Comment by carlhu** [comment]
How do you set the `host` and `protocol` for `sente/make-channel-socket-client!` in this react native situation?

**Comment by TerjeNorderhaug** [comment]
`(sente/make-channel-socket-client!` "127.0.0.1:1337/chsk" {:type :auto :packer :edn})`

Note that host is without `http://`.

**Comment by carlhu** [comment]
Thank you, Terje. But then, how does one specify https or http?
