### ISSUE TITLE
:user-id-fn (takes request, returns an identity string) 

### ISSUE THREAD

**Issue by amakurin** [ptaoussanis/sente#233]
Hi! I've made a system with some universal scheme for uids. In that system i'm using non-string uids. Actually a vector of [user-id session-id client-id].  User-id can be empty, if session is unauthenticated. I did not find any reasons to not to use vectors as uids, and system works fine. Have you anything to say against my approach? and if not - it would be really nice if you'll not restrict uid's type to string-only in future, cuz it is really convenient to use semantical uids without parsing strings all the time. Thanks in advance!

**Comment by jwr** [comment]
While redesigning my app, I just realized that my sente uids will no longer map 1:1 to actual user ids in the application. Multiple sessions per user will need separate identifiers. So I am in a similar situation and I think the request sounds reasonable.

**Comment by danielcompton** [comment]
I had a quick look at the code for this a few days ago, and I couldn't find anything to suggest it wouldn't work. Try it out and report back what happens.

**Comment by jwr** [comment]
I just tried it and it does work. It doesn't seem to solve my problem (I need to be able to distinguish multiple authenticated sessions from a single user in a single browser), but it does work.

I think @amakurin asked not to restrict this in the future, which I second.

**Comment by danielcompton** [comment]
> (I need to be able to distinguish multiple authenticated sessions from a single user in a single browser)

What do you mean by this? How and when are you wanting to distinguish the sessions? You can look at the `uid` on every Sente message you get sent to find the user, and you can go rummaging through `connected-uids` if you want more control?

**Comment by jwr** [comment]
I do need more control — I have to be able to distinguish every ClojureScript client app. But as you explained in https://github.com/ptaoussanis/sente/issues/233 this is possible.

Coming back to the original topic, my `uid` is now a vector of `[uid client-id]` so that I can use `send-fn` to address each client separately. This seems to work well, and it means that like @amakurin I'd like to be able to use non-string uids in the future.

**Comment by ptaoussanis** [comment]
Daniel is correct, a user id can be anything you'd like it to be (incl. a vector). Just mod your `:user-id-fn` accordingly.

> @jwr: I think @amakurin asked not to restrict this in the future, which I second.

Hi Jan, Alexey. No plans to change this behaviour, it can be considered stable. Okay to close this issue?

**Comment by ptaoussanis** [comment]
Closing for now, please feel free to reopen if you still have any questions. Cheers :-)
