### ISSUE TITLE
Server-side push to a single client

### ISSUE THREAD

**Issue by jwr** [ptaoussanis/sente#235]
I have an application where I need to be able to tell Sente sessions apart. If a user opens multiple tabs in a single browser, each tab will run a separate instance of a ClojureScript app, and I would like to be able to address each one using server-side push. However, it seems the current push is per-uid only, which pushes to all sessions under that uid.

I tried extending the uid with additional data (see https://github.com/ptaoussanis/sente/issues/233), but I can't make it work, because multiple tabs in a single browser share session data.

Sente does have the notion of a client-id, but doesn't seem to expose it. I'd like to be able to use it — the way I think of it, I'm currently using `uid`, and I'd like to have a pair `[uid client-id]` that addresses not just the particular `uid`, but a given sente session (ClojureScript app instance) for a given `uid`.

Is this possible? Am I missing something obvious?

**Comment by danielcompton** [comment]
This is totally possible. Provide a `:user-id-fn` to `sente/make-channel-socket` on the server. You'll get the ring request as an argument and you need to return a uid. The client-id is a URL param, so you can get it from the ring request. You might need to add some middleware to parse the param first.

Then you can return whatever value makes sense for you from that.

**Comment by jwr** [comment]
Thank you! `:user-id-fn` is exactly what I needed. I used:

```
(fn [req]
  (if-let [id (get req :identity)]
    [id (get-in req [:params :client-id])]
    :taoensso.sente/nil-uid))
```

and this, together with using `:uid` from incoming events instead of `(get-in ring-req [:session :uid])`, solved the problem for me. I can now address each client individually, while still keeping the authentication as it was before.

So, it turns out I *was* missing something obvious. Thanks for your help!

**Comment by ptaoussanis** [comment]
Thanks a lot @danielcompton!

@jwr Okay to close this?

**Comment by ptaoussanis** [comment]
Closing for now, please feel free to reopen if you still have any questions. Cheers :-)
