### ISSUE TITLE
Requesting a pair of eyes on the generic-node adapter implementation

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/sente#237]
@theasp @whamtet Hi Andrew, Matthew-

Made some changes to the adapter interface recently, and updated the generic-node implementation to match. When one of you has time, may I request that you check for any obvious problems? Have zero experience with the node API; not even certain what docs to check.

In particular, I've made some comments at
https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/server_adapters/generic_node.cljs#L56 and
https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/server_adapters/generic_node.cljs#L63

Updated interface requirements are at https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/interfaces.cljx.

Thanks a lot, cheers! :-)

**Comment by theasp** [comment]
Matthew wrote those bits so I am not too sure, but a quick check does show that `:chsk/uidport-open` never gets sent for AJAX or WS using express.

```
INFO [example.server:295] - Web server is running at `http://localhost:4000/`
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
DEBUG [example.server:238] - Unhandled event: [:chsk/uidport-open :taoensso.sente/nil-uid]
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{}, :any #{:taoensso.sente/nil-uid}}

[Reloaded tab here]

DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}

[I closed the tab here]

DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
DEBUG [example.server:262] - Broadcasting server>user: {:ws #{:taoensso.sente/nil-uid}, :ajax #{:taoensso.sente/nil-uid}, :any #{:taoensso.sente/nil-uid}}
```

**Comment by ptaoussanis** [comment]
@theasp Great, thanks for checking. Is this with the project at https://github.com/theasp/sente-nodejs-example?

Also, with the goal of finding the appropriate docs - could you (or Matthew) possibly just give a quick overview of how the node adapter here works?

At https://github.com/theasp/sente-nodejs-example/blob/master/project.clj for example, I see that you're pulling in both Express and Dog Fort?

So node is the underlying API, Express a library on top of that? Where does Dog Fort sit?

Re: the generic node adapter -
I can see the generic-node adapter is dealing directly with a Ring map with `websocket` or `response`+`body` fields.

The `websocket` field is described at https://github.com/websockets/ws, is that correct?
And the `response` and `body` fields at https://nodejs.org/api/http.html?

Thanks!

**Comment by theasp** [comment]
@ptaoussanis, yes that is the project.  :)

Yes, both express and dogfort are libraries on top of node's built in HTTP server, which have their own middleware and routing.  Dogfort provides an API more like ring.
