### ISSUE TITLE
Adding slf4j-timbre causes sente to fail.

### ISSUE THREAD

**Issue by currentoor** [ptaoussanis/sente#240]
I added this dependency to the example project in this repo (in sente 1.8.1). We used this as per recommendation in timbre README to capture logs from a Java library.
https://github.com/fzakaria/slf4j-timbre
Version 0.3.2.

https://github.com/ptaoussanis/timbre#a-pure-clojurescript-logging-library

By simply adding it as a dependency I get this error for client->server messages
```
 Bad ev-msg: {:ch-recv #object[clojure.core.async.impl.channels.ManyToManyChannel 0x651eda4d "clojure.core.async.impl.channels.ManyToManyChannel@651eda4d"], ...
```
However server->client messages appear to work.

I think it's more likely that this bug is in sl4j-timbre, but I figured you'd have more insight since you know sente and timbre.

Edit:
I see this was discussed here and they fixed it in release 0.3.0.
https://github.com/fzakaria/slf4j-timbre/issues/8

So it might be a regression.

**Comment by danielcompton** [comment]
Can you run `lein deps :tree` to print all of your dependencies?

**Comment by ptaoussanis** [comment]
@currentoor Hi, I believe this should be resolved by pulling in `[com.taoensso/timbre "4.5.1"]`.

Context: https://github.com/fzakaria/slf4j-timbre/issues/20

**Comment by ptaoussanis** [comment]
Assuming this is resolved, closing.
