### ISSUE TITLE
Transit encoding issue with namespace qualified keyword, with Clojure 1.9.0-alpha8 (and above)

### ISSUE THREAD

**Issue by settinghead** [ptaoussanis/sente#241]
I recently bumped my Clojure version to `1.9.0-alpha8`, and my my websocket server stopped sending correctly-formatted websocket frames.

I'm using namespace qualified keyword in my map, and got `chsk/bad-package` error.

Further investigation in Chrome suggests that the frame is sent in incorrect format. For example, `{::some.namespace/foo 1}` becomes `{#:some.namespace {:foo 1}}`. 

I suspect this might have to do with this commit: 
https://github.com/clojure/clojure/commit/6d48ae372a540903173be2974b66b8911371e05d#diff-3a5dca122734225f3f60263876401aebR605

However, I haven't yet figured out if this is a bug with Sente, with transit-clj or with Clojure language itself. 

I'll look into it further when I have time. Meanwhile, any insight into the issue would be welcome.

**Comment by settinghead** [comment]
OK I solved the problem. It turns out that the next version of Clojure/Script will use a different format for namespace qualified keywords in maps: 
http://clojure.org/reference/reader#_maps

The error occurred because I was using latest alpha version of Clojure, but not with latest version of ClojureScript (the latest change is not yet released and is only on the master branch).

Upgrading to the latest master branch version of ClojureScript solved my issue.

**Comment by ptaoussanis** [comment]
@settinghead Thanks for looking into this and coming back with the conclusion, much appreciated!
