### ISSUE TITLE
PR request: a react-native example project

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/sente#248]
Sente's been [reported](https://github.com/ptaoussanis/sente/issues/229) to work with React Native.

But it's currently difficult to ensure that we don't accidentally [break support](https://github.com/ptaoussanis/sente/issues/247) since we don't have a reference example to test against.

First step to getting more stable support would be to have a reference example that we can test against.

This isn't something I'll be able to do myself, so  **PRs welcome**.

Steps:

1. Fork the current [reference example](https://github.com/ptaoussanis/sente/tree/master/example-project) to your own repo.
2. Modify for React Native support (incl. build scripts or instructions, etc.).
3. Submit a PR to add a link to your repo [here].(https://github.com/ptaoussanis/sente/tree/master/example-project)

Thanks!

**Comment by tiensonqin** [comment]
@ptaoussanis Sorry for the late response, I've released the Ios and Android code for Lymchat, 
https://github.com/tiensonqin/lymchat

Client part mainly in this module:
https://github.com/tiensonqin/lymchat/blob/master/src/lymchat/ws.cljs

Server part:
https://gist.github.com/tiensonqin/06845f40e39315fac3b3a3419ba51964

Sorry for not providing a complete reference example.
Hope other people can help with this.

**Comment by ptaoussanis** [comment]
That's great, thank you! Please feel free to submit a PR with a [link](https://github.com/ptaoussanis/sente#example-projects) to your project.

Cheers! :-)
