### ISSUE TITLE
holding connection open in chrome extension, or retry/fallback to ajax when sending on closed connection?  

### ISSUE THREAD

**Issue by paultopia** [ptaoussanis/sente#249]
Hi there, 

So this is a bit of puzzling behavior.  I'm trying to use Sente to handle communication between a Chrome extension and a server (right now just running on localhost).  

In the architecture of Chrome extensions, there's a persistent background page that (supposedly) [is persistent while the extension is running](https://developer.chrome.com/extensions/background_pages) --- which I take to mean that it should have persistent websockets connections too.  

However, whenever I load a different page in the user-facing front-end, it looks like sente loses the WS connection on the background script.  

I'm not sure whether this is a Sente issue or a Chrome issue, but my guess is it's a Sente issue, because it looks like the background page is maintaining persistent state across these socket openings and closings (see the "foo" business in the console snippet below), which is consistent with the background page not reloading.  

As you can also see from the snippet, the uid is staying the same across these close/open exchanges (I'm just using the ring client id as user-id-fn), which I guess rules out the supposition that something bizarre is going on in that department.  

(This might have something to do with Cente, or websockets in general, not playing nicely with Chrome's message-passing API (?) --- it looks like the socket is only closing when I load a page that generates a message from the content script, embedded in user-facing pages, to the background script.)

Do you know how I might convince it to hold the connection open?  Or, alternatively, to retry failed messages when the socket is closed/fall back to ajax?  Right now, it doesn't look like the data I'm trying to send is getting to the server at all.  

thanks!
 

```
WARN [taoensso.sente:800] - Chsk is closed: will try reconnect (1)
background.js:797 state changed: {:type :ws, :open? false, :uid "b3c3ef7d-275c-42e5-9a7b-d37165f604c2", :csrf-token nil}
background.js:708 WARN [taoensso.sente:719] - SECURITY WARNING: no CSRF token available for use by Sente
background.js:797 state changed: {:type :ws, :open? true, :uid "b3c3ef7d-275c-42e5-9a7b-d37165f604c2", :csrf-token nil}
background.js:797 connection established: ["b3c3ef7d-275c-42e5-9a7b-d37165f604c2" nil]
var foo = "meow"
undefined
foo
"meow"
background.js:708 WARN [taoensso.sente:800] - Chsk is closed: will try reconnect (1)
background.js:797 state changed: {:type :ws, :open? false, :uid "b3c3ef7d-275c-42e5-9a7b-d37165f604c2", :csrf-token nil}
background.js:708 WARN [taoensso.sente:750] - Chsk send against closed cask.
background.js:708 WARN [taoensso.sente:719] - SECURITY WARNING: no CSRF token available for use by Sente
background.js:797 state changed: {:type :ws, :open? true, :uid "b3c3ef7d-275c-42e5-9a7b-d37165f604c2", :csrf-token nil}
background.js:797 connection established: ["b3c3ef7d-275c-42e5-9a7b-d37165f604c2" nil]
foo
"meow"

```

**Comment by danielcompton** [comment]
It is possible Sente is doing something here, but I think it is unlikely? (but I could be wrong!). There's no explicit logic in Sente that would cause disconnections like this to happen. A test to check on this would be to make a basic WebSocket connection to something like https://www.websocket.org/echo.html and see if you get the same behaviour. A brief search didn't find any local websocket echo clients you can run.

> Or, alternatively, to retry failed messages when the socket is closed/fall back to ajax?

You can check if the connection is open before attempting to send a message, although you should always be able to handle closed connections, even if you check, as it may not be apparent that a connection is closed until you try to send something.

**Comment by paultopia** [comment]
thanks @danielcompton ---just checking for open connection seems like a fairly easy fix.  am I right in guessing from a combination of the example project and that js console log that open connection status is stored as `(:open @chsk-state)`?

**Comment by danielcompton** [comment]
Yep, that's the one.

**Comment by ptaoussanis** [comment]
Daniel's response is spot-on: there's no logic in Sente that'd intentionally cause disconnects like this. Am not familiar with the Chrome extensions API, but the suggestion to try a simple non-Sente WebSocket example should be a good starting point.

Cheers :-)

**Comment by ptaoussanis** [comment]
Will assume this is resolved, closing for now.
