### ISSUE TITLE
Include `:ever-opened?` in state object

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#253]
The `:ever-opened?` key is useful for understanding the state of our app and whether we have ever connected, however it only appears once the socket has been opened. This means that if I want to check for `:ever-opened?` I need to actually check if the `:ever-opened?` key doesn't exist in the state map. This is ok, but feels a little bit awkward, and the intent of the code isn't immediately clear.

Thoughts?

**Comment by ptaoussanis** [comment]
Hey Daniel, not sure I follow.

What prevents you from checking `(:ever-opened? <state>)` to see if you've ever connected? It'll be truthy iff the channel socket has ever connected. Am I missing something?

Cheers :-)

**Comment by danielcompton** [comment]
When I upgraded Sente to the newest version that passes old and new states in `:chsk/state` I hit a bug where I was incorrectly destructuring the values. I had a cond and one step was checking for `(not (:open? new-state))`. `new-state` was nil, and `(:open? nil)` returns nil which meant that nothing under that `cond` line was run.

I've got a similar cond here. If I did `(not (@state :ever-opened?))` then I can't distinguish between `:ever-opened?` being false, and me introducing a bug where I'm passing the ratom wrong.

```
(cond
        (not (contains? @state :ever-opened?))
        (throw (ex-info ...)

        (false? (:open? @state))
        (throw (ex-info ...))
     ....
)
```

Adding `:ever-opened?` would be more explicit, and I could code more safely against it.

**Comment by ptaoussanis** [comment]
Just my 2c (this is a little subjective), but I would normally recommend against tests like `(false? _)` unless the intention is to specifically distinguish between nil and false.

Using explicit boolean checks when testing for general truthiness can be a code smell IME and might imply that what you really want to do is to first branch on the non/existance of the state that you're checking against.

I.e. something like

```
(cond
  (not state) then1 ; We don't have any state, checking for keys is meaningless
  ;; From here on we have a state, so can depend on its key contract
  (not (:ever-opened? state)) then2 ; nil, false, or non-existant value all equally meaningful
...)
```

In any event, I wouldn't mind a PR that initializes `:ever-opened?` to false; I would just caution in general against the pattern of assuming that a falsey value will be initialized to any particular kind of falsey (i.e. nil vs false vs non-existant).

Hope that makes some sense?

**Comment by danielcompton** [comment]
Sure, makes sense. I do have a nil? up above the cond which would catch that kind of stuff normally, but I wanted to put my belt and suspenders on too. Definitely know what you mean about nil checks though. Will take a look at putting a PR together. Thanks!

**Comment by ptaoussanis** [comment]
No problem,

> Will take a look at putting a PR together. Thanks!

No need, just did it myself quickly. Cheers :-)

**Comment by danielcompton** [comment]
Thanks!
