### ISSUE TITLE
Exception from receive-buffered-evs!

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/sente#261]
On Sente master, I get this exception:

`Error: Assert failed: (not= (namespace id) "chsk")`

which occurs when a `:chsk/ws-ping` gets through to an assert that no `chsk` events should hit.

<img width="663" alt="screenshot of safari technology preview 8-09-16 4-36-59 pm" src="https://cloud.githubusercontent.com/assets/811954/18337201/8b720e04-75e2-11e6-8552-8ac9862117a8.png">

<img width="641" alt="screenshot of google chrome 8-09-16 4-37-50 pm" src="https://cloud.githubusercontent.com/assets/811954/18337206/9880a880-75e2-11e6-8b99-de76d7d62df9.png">

It's simple to remove the assert, but I'm not sure if that's the best route long term for this.

**Comment by ptaoussanis** [comment]
Hi Daniel,

Sorry, GitHub master was lagging behind my local version - forgot to push an update that addressed this. Should be good now.

**Comment by ptaoussanis** [comment]
BTW `[com.taoensso/sente "1.11.0-alpha4"]` should also be okay if you want a cut release, that's what I'm currently using.

**Comment by ptaoussanis** [comment]
Just noticed those screenshots btw, that's very handy! How did you include those?

**Comment by danielcompton** [comment]
That's using [dirac](https://github.com/binaryage/dirac), which adds a CLJS debugger for Chrome. It's really slick, and makes life a lot easier. It also adds a REPL in the devtools. Setup looks like it's hard, but it's really just methodically following the steps.

<img width="348" alt="screenshot of google chrome 8-09-16 5-08-03 pm" src="https://cloud.githubusercontent.com/assets/811954/18337681/d157bcd0-75e6-11e6-919d-8ead9f328888.png">

<img width="401" alt="screenshot of google chrome 8-09-16 5-07-27 pm" src="https://cloud.githubusercontent.com/assets/811954/18337676/c33a2f70-75e6-11e6-934c-563d2bb30564.png">
