### ISSUE TITLE
How to emulate sente's protocol?

### ISSUE THREAD

**Issue by arichiardi** [ptaoussanis/sente#262]
Hello @ptaoussanis, I was trying to benchmark my sente app and I was wondering if I can somehow emulate the messages sent back and forth. I guess I would need to know the protocol for the handshake at the very basic. Is there a place I can find that (also in the code, and I can contribute it back in some format)?

An alternative would be for me to override sente, disabling it altogether and use the immutant websocket so that I can at least have some kind of "comparable" benchmark.

I don't even know if I am approaching the problem in the correct way and I open to suggestions.

Thanks a lot for your work (it is nice to write this in every issue I think :smile:),
Andrea.

**Comment by ptaoussanis** [comment]
Hi Andrea,

> Thanks a lot for your work (it is nice to write this in every issue I think 😄),

Heh heh, thank you :-)

> I was trying to benchmark my sente app and I was wondering if I can somehow emulate the messages sent back and forth.

Hmm, how clear are you on precisely what you want to benchmark?

Unless you have something else very specific in mind, a decent general idea might be to just write a util to execute real, synthetic Sente events (e.g. `[:my-app/fetch-booking-info {:search-criteria _])`, using the normal Sente API. Just generate events from a script instead of from user input.

This'd be the easiest thing to implement and give you a high-level overview of ~realistic app performance as users would see it.

Your performance numbers would include:
* Application performance (time taken to respond to app-level channel socket requests)
* Sente performance (any overhead that Sente might introduce over your web server)
* Web server performance (e.g. WebSocket handling, etc.)

If you setup your benchmarks to run over the net (perhaps even through a proxy), you could also cover things like your server + CDN latency, etc.

That'd be a decent place to start. If the numbers are too slow, you can then do further tests to figure out which component is bottlenecking. In almost all cases, times will be dominated by:

1) The application if it's hitting the db and not being cached well
2) Network latency

Web server benchmarks are rarely interesting from a performance perspective IMO, esp. for real applications. The cost to generate a response usually so-far outweighs the cost of the web server responding that it's rarely even worth thinking about. Depends on the use case though, of course.

Hope some of that was helpful?

**Comment by arichiardi** [comment]
Oh definitely helpful, thanks!

I was thinking exactly that: to reproduce the protocol and the `:chsk` messages...

A thing I do is for example to save the uuids I receive during the first handshake in some atom. So I need to spec the messages first. I will report back my digging.

**Comment by ptaoussanis** [comment]
Sorry, you're losing me a little though: why would you need to reproduce the protocol or think at all about the handshake, etc.? None of that seems relevant or necessary for benchmarking, unless I'm missing something?

Keep in mind that anything falling under protocol or handshake stuff is likely an implementation detail and therefore subject to breaking changes w/o notice. Would avoid depending on implementation details unless you have a very clear reason for wanting to do that.

**Comment by arichiardi** [comment]
Sorry for the delay..I was dragged into other tasks...just for clarify what I am thinking of, now I do something like:

```
:chsk/uidport-open (fn [{:keys [uid send-fn]}]
                        (swap! ws/clients ws/register-uid uid send-fn))
:chsk/uidport-close (fn [{:keys [uid]}]
                         (swap! ws/clients ws/deregister-uid uid))
```

So that why to emulate the real scenario behavior I was thinking I need to send those two events as well because basically they setup a map with client + augmented info that I need to send when I react to the other messages.

I guess for a normal "opened connections" benchmark I will just need to send anything and try to flood the target with messages until I know what is the limit. For more "behavioral" benchmark (if they make sense, which I will decide with your help as well :smile:) I guess I need a more complicated interaction.

**Comment by arichiardi** [comment]
If I may add another question...I didn't quite understand yet is why the following works this way:

```
$ wscat -c ws://localhost:3000
connected (press CTRL+C to quit)
disconnected
```

Compare with:

```
wscat -c ws://echo.websocket.org
connected (press CTRL+C to quit)
> test
< test
>
```

It is probably due to my being not familiar enough with sente and I apologize in advance :pray:

**Comment by arichiardi** [comment]
About the latter, let me investigate with debug on first :+1:

**Comment by arichiardi** [comment]
So the about the above, I am trying now a better `wscat -c ws://localhost:3000/chsk` and from what I see I need to pass a `client-id` (at least) or I will receive:

```
Wed Sep 14 14:49:49 PDT 2016 [http-kit-5] ERROR - GET /chsk
clojure.lang.ExceptionInfo: Client's Ring request doesn't have a client id. Does your server have the necessary keyword Ring middleware (`wrap-params` & `wrap-keyword-params`)? {:ring-req {:remote-addr "127.0.0.1", :params {}, :route-params nil, :headers {"connection" "Upgrade", "host" "localhost:3000", "sec-websocket-key" "x3JJHMbDL1EzLkh9GBhXDw==", "sec-websocket-version" "13", "upgrade" "websocket"}, :async-channel #object[org.httpkit.server.AsyncChannel 0x6a05b8f4 "/127.0.0.1:3000<->/127.0.0.1:36726"], :server-port 3000, :content-length 0, :form-params {}, :websocket? true, :query-params {}, :content-type nil, :character-encoding "utf8", :uri "/chsk", :server-name "localhost", :query-string nil, :body nil, :scheme :http, :request-method :get}}
	at clojure.core$ex_info.invokeStatic(core.clj:4724)
	at clojure.core$ex_info.invoke(core.clj:4724)
	at taoensso.sente$make_channel_socket_server_BANG_$fn__46767.invoke(sente.cljc:571)
	at booma.api$routes$fn__46181.invoke(api.clj:37)
	at bidi.ring$eval47608$fn__47609.invoke(ring.clj:20)
	at bidi.ring$eval47587$fn__47588$G__47578__47597.invoke(ring.clj:12)
	at bidi.ring$make_handler$fn__47617.invoke(ring.clj:37)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__47826.invoke(keyword_params.clj:35)
	at ring.middleware.params$wrap_params$fn__47786.invoke(params.clj:64)
	at booma.middleware$wrap_log_request$fn__47833.invoke(middleware.clj:29)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by arichiardi** [comment]
Confirming with Wireshark that the client is indeed sending the `client-id`:

```
GET /chsk?*my-custom-data-here*&client-id=bd5ee0f2-dc22-47b5-98ab-618711f34b45 HTTP/1.1
Host: localhost:3000
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://localhost:3000
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2824.0 Safari/537.36
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,fr-FR;q=0.6,fr;q=0.4
Cookie: ...
Sec-WebSocket-Key: Nl49IiqBKuyC/x5FVHrqwA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

So ok, I don't know how/where I can share this info now :D

**Comment by ptaoussanis** [comment]
Hi Andrea, so just to confirm: is this issue now resolved? If not, could you clarify what info you're still looking for? Thanks!

**Comment by arichiardi** [comment]
I think it is solved yes,by adding the `client-id`  I can now recreate prod messaging and see if it makes sense (or not) to benchmark different event exchanges between client and server. Closing but thanks a lot for the prompt answers!

**Comment by ptaoussanis** [comment]
No problem, thanks for following up (and for the related PR)- cheers! :-)
