### ISSUE TITLE
Add reason why an event is a bad-event

### ISSUE THREAD

**Issue by arichiardi** [ptaoussanis/sente#266]
Just putting this here, more like an enhancement.

At the moment we receive a `bad-event` event when `sente` cannot [validate](https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljc#L116) the incoming event.

It would be great if there was the reason why it did not validate in the payload. It could be in the form of an `ex-info` directly and even be `clojure.spec`-ed. It is a pretty straightforward spec to create.

I am willing to help on this if you are ok with it (with or without `clojure.spec`).

**Comment by arichiardi** [comment]
Here is the spec from my code for you to double check:

```
(s/def ::sente-ev-id (s/and keyword? #(namespace %)))
(s/def ::sente-event (s/and vector?
                            #(#{1 2} (count %))
                            (s/cat :ev-id ::sente-ev-id :?ev-data any?)))
```

**Comment by ptaoussanis** [comment]
Hi Andrea,

Thanks for this! Am potentially up for a change to the `bad-event` wrapping to include the validation failure cause, though I'd like a little time to think about it since it'd need to be a breaking change. Just have my hands very full atm, so trying to batch open-source work.

Re: the implementation- would prefer avoiding c.spec here since we already have the validation info we need.

Will take a look at this next time I'm on Sente, thanks again - cheers :-)

**Comment by arichiardi** [comment]
No problem about time, I found that I can deal with it with the spec above in the event handler function.

An idea, as it does not have to be breaking: at the moment `sente` passes the `ws-msg` in its entirety to the handler function anyways. We could add a `:ex-info` or `:ex` key there that contains the exception.

**Comment by ptaoussanis** [comment]
> An idea, as it does not have to be breaking: at the moment sente passes the ws-msg in its entirety to the handler function anyways. We could add a :ex-info or :ex key there that contains the exception.

Okay, think we're talking about different things. Could you possibly clarify where exactly you're running into malformed events that you'd like more info on?

The server doesn't throw for malformed events, it just wraps them as `[:chsk/bad-event _]` or `[:chsk/bad-package _]` so that you can handle them as you like.

And your server shouldn't be allowed to send malformed events.

Are you talking about trying to send malformed events from the client to the server?

**Comment by mariusz-jachimowicz-83** [comment]
I was testing sente example from v `1.8.1`. I have noticed that there is `Bad server ev-msg ` when I add
```clojure
[com.fzakaria/slf4j-timbre "0.3.2"   :exclusions [org.clojure/clojure com.taoensso/timbre com.taoensso/encore]]
   [org.slf4j/slf4j-api "1.7.14"]
   [org.slf4j/log4j-over-slf4j "1.7.14"]
   [org.slf4j/jul-to-slf4j "1.7.14"]
   [org.slf4j/jcl-over-slf4j "1.7.14"]
```
I noticed thet in this situation
```clojure
; used inside server-event-msg? for debugg
a (warnf "--- props")
b (warnf "%s" (enc/chan?       ch-recv))
c (warnf "%s" (ifn?            send-fn))
d (warnf "%s" (enc/atom?       connected-uids))
e (warnf "%s" (map?            ring-req))
f (warnf "%s" (enc/nblank-str? client-id))
g (warnf "%s" (event?          event))
h (warnf "%s" (or (nil? ?reply-fn) (ifn? ?reply-fn)))
```
results in
```
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:141] - --- props
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:142] - nil
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:143] - true
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:144] - true
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:146] - true
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:147] - true
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:148] - true
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:149] - true
16-09-19 17:11:24 starter-clojure WARN [taoensso.sente:175] - nil
```
When `slf4j-timbre` is not used then all are true.  
Do you know why this is happening?

This is whole msg:  
```
Bad server ev-msg: {:ch-recv #object[clojure.core.async.impl.channels.ManyToManyChannel 0x4eadd14c "clojure.core.async.impl.channels.ManyToManyChannel@4eadd14c"], :send-fn #object[taoensso.sente$make_channel_socket_server_BANG_$send_fn__16699 0x3a24c823 "taoensso.sente$make_channel_socket_server_BANG_$send_fn__16699@3a24c823"], :connected-uids #object[clojure.lang.Atom 0x3bcfd34e {:status :ready, :val {:ws #{:taoensso.sente/nil-uid}, :ajax #{}, :any #{:taoensso.sente/nil-uid}}}], :client-id "e037250e-2982-4a1c-88f9-6d61b8a85c29", :ring-req {:cookies {"ring-session" {:value "5c6cc7a2-2409-40c1-b599-85baecc6b8f0"}}, :remote-addr "127.0.0.1", :params {:client-id "e037250e-2982-4a1c-88f9-6d61b8a85c29"}, :flash nil, :route-params {}, :headers {"origin" "http://localhost:52805", "host" "localhost:52805", "upgrade" "websocket", "user-agent" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0", "cookie" "ring-session=5c6cc7a2-2409-40c1-b599-85baecc6b8f0", "connection" "keep-alive, Upgrade", "pragma" "no-cache", "sec-websocket-key" "+StaO2VqMYKa+GzgD/En9Q==", "accept" "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "accept-language" "en-US,en;q=0.5", "sec-websocket-version" "13", "accept-encoding" "gzip, deflate", "cache-control" "no-cache"}, :async-channel #object[org.httpkit.server.AsyncChannel 0x4ab4ef0b "/127.0.0.1:52805<->/127.0.0.1:54911"], :server-port 52805, :content-length 0, :form-params {}, :compojure/route [:get "/chsk"], :websocket? true, :session/key "5c6cc7a2-2409-40c1-b599-85baecc6b8f0", :query-params {"client-id" "e037250e-2982-4a1c-88f9-6d61b8a85c29"}, :content-type nil, :character-encoding "utf8", :uri "/chsk", :server-name "localhost", :query-string "client-id=e037250e-2982-4a1c-88f9-6d61b8a85c29", :body nil, :multipart-params {}, :scheme :http, :request-method :get, :session {:ring.middleware.anti-forgery/anti-forgery-token "qnWy7uaUUd/fWij6SVhfhB4XDxQidQUQIyDCtPI/rBCFNcqvf1V2Uy+a5zwvL4ojTkyWz/E9MzRLKUp4"}}, :event [:chsk/ws-ping], :?reply-fn nil, :uid :taoensso.sente/nil-uid}
```

**Comment by arichiardi** [comment]
@ptaoussanis You are right, I can handle it there and therefore this might not an issue at the moment, but in order to understand why sente treats a data payload as `bad-event` I had to spec the `validate-event` and check, which now returns correctly what is wrong, in code:

```
...
:chsk/bad-event (fn [{:keys [event]}]
                     (let [[_ real-bad-event] event]
                       (bus/>! (->> real-bad-event
                                     (bs/valid-or-ex-info ::events/sente-event)
                                     (events/sente->bad-event real-bad-event)))))
...
```

Apart from the `bus` thing, the `valid-or-ex-info` is a wrapper around `spec/valid?` and `spec/explain-data`.

Of course my `spec` is just a temporary workaround because if `sente`'s `validate-event` changes, I need to adapt it. So what I meant above was, let's maybe have a public function (the same `validate-event` maybe?) that client code can call in order to produce the reason why `sente` tagged an event as `bad-event` or `bad-package`.

**Comment by arichiardi** [comment]
@mariusz-jachimowicz-83 it looks your problem might be worth a separate issue

**Comment by ptaoussanis** [comment]
@mariusz-jachimowicz-83 Yes, please post this as a separate issue - thanks!

**Comment by ptaoussanis** [comment]
@arichiardi Hi Andrea,

Before discussing possible solutions, would prefer to start out with a clear description of the particular problem we're looking at. Sorry if I've missed this, but could you possibly clarifying where you're actually running into malformed events? On the server, or on the client? Both? Do we know how the malformed events are being generated?

Are we talking about malformed events that are hitting your router, or malformed events that are being passed to `chsk-send!` and therefore throwing an assertion error?

Thanks, cheers! :-)

**Comment by arichiardi** [comment]
Hey Peter yes no problem ;)

I am talking about handling messages on the server side. As we know, client code can be buggy / malicious code can come from the net / messages can get corrupted etc etc (exaggerating here a bit)

The use case: as a sente server, I would like to be able to understand why an event from the client is deemed as `bad-event`/`bad-package`.

I stripped all the solutions away from this description. Also, keep in mind this is more for completeness and robustness as many servers might just discard the malformed events and you might rightly think that it is kind of useless to generate this info. I kind of maybe agree it is useless in production, but for benchmarking and integration tests it might be a life saver ;)

Thank you Peter!

**Comment by ptaoussanis** [comment]
Apologies for the delay on this, have not forgotten - will take a look before cutting the next stable release.

**Comment by ptaoussanis** [comment]
Hi Andrea,

Have made a simple change to help with this: `sente/validate-event` is now public and returns a more helpful result for failing validations.

This improves the error messages automatically thrown by `assert-event`.

Didn't make any change to the `[:chsk/bad-event _]` form yet since that'd be breaking. Instead, you can just catch these events and pass the invalid event to `sente/validate-event` if you want to get more details.

Does that help / seem reasonable?

**Comment by ptaoussanis** [comment]
Closing for now for triage but please feel free to reopen if you'd like to suggest any changes, etc. :-)

**Comment by arichiardi** [comment]
I will try it out, now the event is threaded through a spec (which I can contribute as well if you say so :smile:). I'll report back Peter and thanks a lot!
