### ISSUE TITLE
sente/make-channel-socket! breaks when loaded from a file:// url

### ISSUE THREAD

**Issue by glittershark** [ptaoussanis/sente#271]
I use [doo](https://github.com/bensu/doo) to run my cljs unit tests, some of which require a namespace that runs `sente/make-channel-socket!` at the top level. However, as of https://github.com/ptaoussanis/sente/commit/a13fac99594288d85b3df4dbd1b4021f0e93b990 sente throws an exception on any protocols that aren't `http` or `https`. Since doo loads code via a `file:` protocol this means my tests are (basically unavoidably) breaking since the upgrade to a version of sente with that commit.

**Comment by ptaoussanis** [comment]
Hi Griffin,

Your `doo` link doesn't work there, so I'll assume you're talking about this?: https://github.com/bensu/doo

The behaviour with a13fac9 was intentional, but I didn't realise that anyone might have use for a non http/s protocol. I.e. the earlier support was unintentional :-)

Will update to officially bring back support. Thanks for the report!

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/sente "1.11.0-alpha5"]` to Clojars.

Please feel free to close if that resolves the issue? Cheers!

@danielcompton Btw thanks for the title change.

**Comment by glittershark** [comment]
Oops. Yes, that was the intended link

**Comment by glittershark** [comment]
Now I'm getting this mess (in phantomjs):
```
Wrong url scheme for WebSocket file:///0/chsk?client-id=d3be2883-52c3-4938-b777-0616838ca8e8
#error {:message "Invariant violation in `taoensso.timbre:?`. Test form: `(string? ?msg-fmt)` with failing input: `Error: SYNTAX_ERR: DOM Exception 12`", :data {:*?data* nil, :elidable? true, :dt #inst "2016-09-26T23:44:21.494-00:00", :val #object[Object Error: SYNTAX_ERR: DOM Exception 12], :ns-str "taoensso.timbre", :val-type #js {:prototype #js {:SECURITY_ERR 18, :ABORT_ERR 20, :INUSE_ATTRIBUTE_ERR 10, :WRONG_DOCUMENT_ERR 4, :HIERARCHY_REQUEST_ERR 3, :QUOTA_EXCEEDED_ERR 22, :NO_MODIFICATION_ALLOWED_ERR 7, :VALIDATION_ERR 16, :URL_MISMATCH_ERR 21, :NOT_FOUND_ERR 8, :NOT_SUPPORTED_ERR 9, :NETWORK_ERR 19, :DOMSTRING_SIZE_ERR 2, :TYPE_MISMATCH_ERR 17, :NO_DATA_ALLOWED_ERR 6, :SYNTAX_ERR 12, :INDEX_SIZE_ERR 1, :INVALID_MODIFICATION_ERR 13, :INVALID_CHARACTER_ERR 5, :INVALID_STATE_ERR 11, :NAMESPACE_ERR 14, :INVALID_ACCESS_ERR 15}, :SECURITY_ERR 18, :ABORT_ERR 20, :INUSE_ATTRIBUTE_ERR 10, :WRONG_DOCUMENT_ERR 4, :HIERARCHY_REQUEST_ERR 3, :QUOTA_EXCEEDED_ERR 22, :NO_MODIFICATION_ALLOWED_ERR 7, :VALIDATION_ERR 16, :URL_MISMATCH_ERR 21, :NOT_FOUND_ERR 8, :NOT_SUPPORTED_ERR 9, :NETWORK_ERR 19, :DOMSTRING_SIZE_ERR 2, :TYPE_MISMATCH_ERR 17, :NO_DATA_ALLOWED_ERR 6, :SYNTAX_ERR 12, :INDEX_SIZE_ERR 1, :INVALID_MODIFICATION_ERR 13, :INVALID_CHARACTER_ERR 5, :INVALID_STATE_ERR 11, :NAMESPACE_ERR 14, :INVALID_ACCESS_ERR 15}, :?err nil, :*assert* true, :?data nil, :?line nil, :form-str "(string? ?msg-fmt)"}}
```
Which I'm assuming has something to do with the fact that sente is now trying to connect to a websocket with a `file://` protocol.

**Comment by ptaoussanis** [comment]
> Which I'm assuming has something to do with the fact that sente is now trying to connect to a websocket with a file:// protocol.

Okay, so going to need some assistance in understanding exactly what your requirements are :-) Was under the impression all you needed was to pass through a "file:" protocol?

Let's step back for a moment- could you show me:
1. What `host` and `protocol` opts are you providing to `make-channel-socket-client!`?
2. What would you like your chsk URIs to look like for Ajax and for WebSocket requests?

Thanks

**Comment by ptaoussanis** [comment]
Quick heads-up that I'd like to try cut the next release first free moment I have in the next few days. If you can get the necessary info to me by then, will include the changes in that release. Cheers :-)

**Comment by ptaoussanis** [comment]
Assuming this can be closed? Please feel free to reopen if it's still an ongoing issue. Cheers! :-)
