### ISSUE TITLE
issue with ajax-lite - post form not working properly

### ISSUE THREAD

**Issue by MichaelStephan** [ptaoussanis/sente#273]
Hello,

seems like some issue sneaked into sente 1.10.0. When using ajax-lite (post with form data) the actual request sent to the remote server is wrong. When looking into https://github.com/ptaoussanis/encore/blob/master/src/taoensso/encore.cljx the issue seems to be  related with the implementation of coerce-xhr-params:

```
(fn [uri params]
            (cond
              (js-form-data? params) [uri params :form-data]
              ;; TODO Any other params types we want to support?
              (and    (exists? js/FormData) (rsome js-file? (vals params)))
              (let [form-data (js/FormData.)]
                (doseq [[k v] params] (.append form-data k v))
                [uri form-data :form-data])
              :else (url-encode uri params)))
```

adaptive-encode falls back to url-encode when passing in a normal hash-map. When using js/FormData directly the invocation of coerce-xhr-params fails as (map-keys name params) cannot be invoked on a native js object. 

My proposal is to us transform a hash-map directly into js/FormData. If you agree I can provide a fix.

Best regards,
Michael

**Comment by ptaoussanis** [comment]
Hi Michael, thanks for the report!

To clarify: you're trying to provide a `js/FormData` `params` arg to `ajax-lite` and it's failing?

Would you please try `[com.taoensso/encore "2.82.2-alpha1"]` and let me know if that does the trick? Thanks

**Comment by MichaelStephan** [comment]
Hello,

actually I tried to post two variables: username and password. The issue was when passing in {:username "x" :password "y"} ajax-lite took the params and put them into the query string. Therefor I tried to switch to js/FormData as I also saw this option in your code. I will try 2.82.2-alpha1 now

**Comment by MichaelStephan** [comment]
meanwhile I retried and seems the issue is not fixed. find along my code

**Comment by MichaelStephan** [comment]
(defn login [username password]
  (e/ajax-lite "/login"
                   {:method :post
                    :headers {}
                    :params {:username username
                             :password password}}
                   (fn [{:keys [?status]} ajax-resp]
                     (println ?status))))

when calling the func the actual request sent is forwarded to http://localhost:3449/login?username=a&password=c. The parameters are not sent in the body as I would expect with a POST

**Comment by ptaoussanis** [comment]
Hi there,

> actually I tried to post two variables: username and password. The issue was when passing in {:username "x" :password "y"} ajax-lite took the params and put them into the query string.

In future please try provide these kinds of details, since they help me understand what you're trying to achieve and can help cut down on wasted effort :-)

Just have my hands quite full today, will try swing back around to this at the weekend.

Thanks for the follow-up! Cheers :-)

**Comment by ptaoussanis** [comment]
Should be resolved now with `[com.taoensso/encore "2.83.3"]`, thanks again for the report!

Cheers :-)

**Comment by MichaelStephan** [comment]
Thanks for the quick fix.
