### ISSUE TITLE
Upgrading to 1.10.0 leads to invariant violation for chsk/ws-ping

### ISSUE THREAD

**Issue by kenbier** [ptaoussanis/sente#274]
Invariant violation in taoensso.sente:?` [pred-form, val]: [(vector? clj), :chsk/ws-ping]	

After upgrading:
sente 1.8.1 => 1.10.0
truss 1.1.1 => 1.3.6
encore 2.36.2 => 2.82.1

It looks like the error is coming from [`receive-buffered-evs!`](https://github.com/ptaoussanis/sente/blob/v1.10.0/src/taoensso/sente.cljc#L839). Which is strange because it seems that `:chsk/ws-ping` should never reach that function.

Perhaps related to #261?

**Comment by ptaoussanis** [comment]
Hi Kenneth,

Are you certain that your client+server versions of Sente are in sync? Sounds like your client might be building with stale artifacts.

Would recommend clearing out your `./target` dir and rebuilding to see if that solves the problem.

Cheers :-)

**Comment by kenbier** [comment]
@ptaoussanis I am using [boot](https://github.com/boot-clj/boot#features), so I don't think stale artifacts are the issue.

> Artifacts can never be stale–there is no need for a clean task.

**Comment by ptaoussanis** [comment]
And you're otherwise certain that you're using the same versions of Sente on the client and server?

**Comment by kenbier** [comment]
@ptaoussanis I am not certain. Our deploy process does involves cutting over between two web server instances, so it is possible there were some temporary mismatches between the sente versions.

Its been ~24 hours since deploy and we are still seeing errors in prod. Maybe thats not enough time to be certain though. I'll reopen if the issue persists.

**Comment by ptaoussanis** [comment]
No problem. Just to be clear how the error you're seeing could happen:

1. v1.10.0 server sends out a new ping format
2. If it's received by an old (pre v1.10.0) client, you'll see the warning here

If you've got old clients out in the hands of users, you may need to signal old clients to refresh when the server gets a major version bump.

Anecdotally, it's not unusual for user clients to go weeks or more without a refresh unless you prompt them to.

Will try add client/server version identifiers to v1.11.0 to make these kinds of problems a little easier to identify.

Hope that helps / makes sense?

**Comment by kenbier** [comment]
@ptaoussanis Makes perfect sense, thanks! That is actually what I suspect is happening. 

We do expire client tokens on a weekly basis, and on expiration we do force a refresh. So hopefully this issue goes away next week.

**Comment by ptaoussanis** [comment]
Thanks for the confirmation. 

On the bright side, the error is safe to ignore and shouldn't otherwise interfere with normal client or server operations. If you're logging these errors, you may just want to suppress the particular invariant violation.
