### ISSUE TITLE
Websocket authentication example

### ISSUE THREAD

**Issue by ccherng** [ptaoussanis/sente#279]
The Luminus framework uses by default in memory sessions. This is used to store an :identity key in the session that can be used to verify the user's identification and thus prevent for example POST
delete requests on data that the user shouldn't be allowed to delete. The book "Web Development with Clojure" illustrates this. And it also shows how to use Websockets using Sente. But how can one using the Luminus framework send data from the client to the server over a Websocket and verify the identity of the user like in the POST request above using Sente. A small example of this would be useful.

**Comment by danielcompton** [comment]
Have you read the README? This addresses this, at least partially?

**Comment by cc-placed** [comment]
So by printing out the full argument to handle-message! in (sente/start-chsk-router! ch-chsk handle-message!) each time after fiddling around with how :uid is set my guess is that this :uid can be set based on some user authenticated data set in the http session at channel creation time.

**Comment by ptaoussanis** [comment]
Not familiar with the Luminus framework, sorry - but am guessing that between the README and [example project](https://github.com/ptaoussanis/sente/tree/master/example-project) there should be enough info help?

Will assume I can close this but please free to reopen if you're still having trouble.

Cheers :-)
