### ISSUE TITLE
URL handling when creating socket channel is odd

### ISSUE THREAD

**Issue by pupeno** [ptaoussanis/sente#280]
I'm developing an Electro application, so, the source for the JavaScript and the endpoint are different, which means just this doesn't work:

```clojure
(sente/make-channel-socket! "/chsk" {:type     :auto})
```

I tried this, which I think should work, but it didn't (I'm hardcoding the URL here for simplicity's sake, in my app, it comes from a function that knows to connect to different end points depending on whether it's running in production, testing, dev, etc mode):

```clojure
(sente/make-channel-socket! "http://localhost:3000/chsk" {:type :auto})
```

I think making that work would be great. Digging down in the API, it looked like it experts the URL components, which is not as straightforward as a string but ok. I expected it would be something like:

```clojure
(sente/make-channel-socket! "/chsk"
                            {:type :auto
                             :protocol "http"
                             :host "localhost"
                             :port "3000"})
```

but instead it was this:

```
(sente/make-channel-socket! "/chsk"
                            {:type :auto
                             :protocol "http:"
                             :host "localhost:3000"})
```

which is very counter-intuitive. Why does the protocol contain a colon? why is the host containing the port as well?

**Comment by danielcompton** [comment]
> why is the host containing the port as well?

The term `host` in common usage encapsulates both `hostname` and `port`. See http://bl.ocks.org/abernier/3070589 for a visual explanation of this.

> Why does the protocol contain a colon?

The API doc specifies that you should provide either `:http` or `:https`. Internal implementation details of browser APIs mean that the window.location.protocol returns `"https:"` which is what Sente uses under the covers. Your `"http:"` fell through and happened to work, but isn't part of the API.

> I expected it would be something like...

There is a pretty good docstring on `make-channel-socket-client!` which explains what is required.

**Comment by ptaoussanis** [comment]
Hi @pupeno, sorry for the delayed response. (And thanks for the help fielding questions Daniel!).

Assuming this can be closed? Please feel free to reopen if you're still experiencing any issues.
