### ISSUE TITLE
How does the CSRF token work with Sente?

### ISSUE THREAD

**Issue by alvatar** [ptaoussanis/sente#283]
I can't make the warning concerning CSRF disappear. I've tried adding both site-defaults and/or wrap-anti-forgery with no luck:

```
(def app
  (-> app-routes
   (wrap-defaults site-defaults) ; default behavior adds anti-forgery
   (wrap-session {:cookie-attrs {:max-age 3600}
                  :store (cookie-store {:key "ahY9poQuaghahc7I"})})))
```

What is the procedure by which I can configure this?

**Comment by alvatar** [comment]
In theory the default included with site-defaults will generate a CSRF token with any POST request, but I can see only a GET request being performed by Sente to /chsk.

**Comment by f-f** [comment]
I'm currently experiencing the same issue ATM. It was working correctly until a week ago though, and I didn't change any dependency. My Chrome has been updating though, so the issue could be there.

**Comment by f-f** [comment]
@alvatar `(wrap-defaults site-defaults)` should add the anti-forgery middleware, but it doesn't.
So as a quick fix for this I added the following middlewares: `wrap-keyword-params wrap-params wrap-anti-forgery wrap-session`.
HTH

**Comment by alvatar** [comment]
Thanks @f-f !

**Comment by ptaoussanis** [comment]
Hi folks, sorry for the delayed response! Have you tried checking out the [example project](https://github.com/ptaoussanis/sente/tree/master/example-project)?

**Comment by timothypratley** [comment]
I think this is the same thing going on as here: https://github.com/ptaoussanis/sente/issues/318
@f-f @alvatar are you serving a file? if so please be aware that `wrap-default` will bypass all other middleware. the way I work around this is `(wrap-defaults app-routes (dissoc site-defaults :static))` and provide a `(route/resources "/")` handler. But I think this is a problem with ring that should be changed.
