### ISSUE TITLE
possibility  using socket.io on client side?

### ISSUE THREAD

**Issue by mogadanez** [ptaoussanis/sente#284]
does it possible in theory ?

**Comment by danielcompton** [comment]
socket.io is a complete protocol + websocket layer. Sente and socket.io both cover roughly the same design space, so you couldn't really run one over the other. Does that make sense?

**Comment by ptaoussanis** [comment]
Hi @mogadanez, Daniel is correct - Socket.io and Sente serve a similar purpose but are entirely different protocols with no intended API compatibility. Sorry!
