### ISSUE TITLE
Unexpected log messages from sente

### ISSUE THREAD

**Issue by jwr** [ptaoussanis/sente#290]
I'm using timbre to do client-side logging, where log message are passed back to the server over a sente channel. This works very well and is extremely useful.

I've encountered a problem, however, with logging messages from `taoensso.sente` itself. These seem to occur in case of network problems, but strangely include no message, just the data content of my server response (e.g. the first and only item in `vargs` is what was passed to `:?reply-fn` on the server). The level is always `warn`.

The net result is that my server-side code logs those, with the `taoensso.sente` namespace, and the messages are sometimes fairly large.

For the moment I intend to blacklist `taoensso.sente` in timbre appender configuration, but that just patches over the real problem, and I don't even know what the real problem is.

I would also suggest that perhaps instead of making sente dependent on timbre it might be better to make sente accept a logging function. Sente doesn't do very complex logging, so a single function could work well, and this would let users choose how they want to approach logging without introducing a dependency.

I'm sorry for the vague report, but I'm not sure what the problem really is, and yet I still wanted to provide this information, perhaps it makes immediate sense to someone.

**Comment by ptaoussanis** [comment]
Hi Jan, sorry for the delayed response!

Can try look at this next time I'm doing batched work on Sente. In the meantime, any updates on the issue?

**Comment by jwr** [comment]
No worries. No updates, but it isn't anything urgent. Having thought about this some more, I think my suggestion still stands: I'd much rather pass a logging function to sente than have it depend on timbre.

**Comment by ptaoussanis** [comment]
> No worries. No updates, but it isn't anything urgent.

Okay, thanks for the confirmation.

> Having thought about this some more, I think my suggestion still stands: I'd much rather pass a logging function to sente than have it depend on timbre.

In principle, I agree with you. The idea of trying to offer pluggable logging without incurring any unnecessary dependencies is a good one.

The trouble is that logging's a tough thing to make both pluggable without dependencies, and flexible. By flexible I mean support for things like logging levels (which the lib - Sente in this case - would need to be aware of at an API level), and elision (which would mean the need for macros).

Already we'd be stalled: what we're looking for just isn't possible by passing in a function.

So we much choose between:

1. Sacrifice flexibility in exchange for cutting a dependency.
2. Introduce a dependency to keep flexibility.

In this case, I'd argue that the flexibility has significant value. Also, the dependency (Timbre) is small, and basically already just a minimal API scaffold/interface to get pluggable support for whatever logging facilities you'd prefer to use. It's ~equivalent to tools.logging, but pure Clojure and more flexible.

I'll note: Timbre's picked up more bloat than I'd like (bundled appenders and profiling in particular), but they're not part of the core which is indeed rather minimal. Have started the process to split off the inessentials, but realistically this is for aesthetics more than any practical reason. A few hundred lines of unused+unrun code is vanishingly insignificant compared to what's being compiled each time you run your JVM (let alone Clojure) app :-)

**Comment by jwr** [comment]
I have not seen the problem for several months now. Not sure what caused it or what caused it to disappear -- many dependencies changed since.

I hear your arguments about logging flexibility. I'd still rather cut some flexibility in order to eliminate this dependency and (more importantly) not have Sente do things other than handle network protocols, but I definitely understand your point of view. And there are lots of things more important than this :-)

Thanks for your time, and I believe the issue can be closed.
