### ISSUE TITLE
Pedestal adapter

### ISSUE THREAD

**Issue by quartz55** [ptaoussanis/sente#292]
I've been trying to figure out how to create an adapter for Pedestal so I can take leverage of its interceptor model + routing but I've had no success. I've tried reading source code on other Sente adapters and web sockets on Pedestal (for Immutant) but I can't figure out how to fit it in the interceptor chain. For now I have something similar to the docs on the server setup but with the routes defined in pedestal instead of compojure.

Can provide source code if anyone would find it useful.

_Sorry if I shouldn't be posting this here, couldn't find any other place_

**Comment by ptaoussanis** [comment]
Hi there, sorry for the delay replying!

Not sure I follow what your question is exactly?

I'm not personally familiar with Pedestal, and afaik there aren't any other Pedestal adapters currently available - so unfortunately can't assist there.

If you (or someone else) would like to create a Pedestal adapter, I'm afraid you'd need to figure out the specifics by looking at the Pedestal docs and examples of other Sente adapters.

**Comment by pedroteixeira** [comment]
hi @quartz55, did you manage to be it working? know of any source code examples?
