### ISSUE TITLE
No item 1 in vector of length 1 after upgrading to 1.11.0

### ISSUE THREAD

**Issue by laforge49** [ptaoussanis/sente#294]
Client side error. Any hints would be appreciated. 

Thanks!

Bill la Forge

```
ERROR [taoensso.sente:1549] - Chsk router `event-msg-handler` error: [:chsk/recv [:chsk/ws-ping]]
Error: No item 1 in vector of length 1
taoensso.timbre.appenders.core.console_appender.cljs$core$IFn$_invoke$arity$variadic	@	core.cljs:152
(anonymous)	@	timbre.cljs:479
(anonymous)	@	core.cljs:6326
cljs.core.PersistentArrayMap.cljs$core$IKVReduce$_kv_reduce$arity$3	@	core.cljs:6326
cljs$core$_kv_reduce	@	core.cljs:611
cljs$core$reduce_kv	@	core.cljs:2418
taoensso.timbre._log_BANG_.cljs$core$IFn$_invoke$arity$10	@	timbre.cljs:418
taoensso$timbre$_log_BANG_	@	timbre.cljs:338
(anonymous)	@	sente.cljc:1549
(anonymous)	@	sente.cljc:1523
(anonymous)	@	sente.cljc:1536
(anonymous)	@	sente.cljc:1529
taoensso$sente$_start_chsk_router_BANG__$_state_machine__24464__auto____1	@	sente.cljc:1529
taoensso$sente$_start_chsk_router_BANG__$_state_machine__24464__auto__	@	sente.cljc:1529
cljs$core$async$impl$ioc_helpers$run_state_machine	@	ioc_helpers.cljs:35
cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped	@	ioc_helpers.cljs:39
(anonymous)	@	async.cljs:490
(anonymous)	@	async.cljs:188
(anonymous)	@	channels.cljs:61
cljs$core$async$impl$dispatch$process_messages	@	dispatch.cljs:19
channel.port1.onmessage
```

**Comment by laforge49** [comment]
Code can be found here: https://github.com/rolonicArk/simpleArk

Reverted to 1.10.0 and the error went away.

**Comment by laforge49** [comment]
Dependencies:

                  [org.clojure/clojure                       "1.9.0-alpha14"  :scope "provided"]
                  [org.clojure/core.async                    "0.2.395"]
                  [org.clojure/clojurescript "1.9.473"]
                  [org.clojure/data.priority-map "0.0.7"]
                  ;[org.clojure/google-closure-library "0.0-20160609-f42b4a24"]
                  ;[org.clojure/google-closure-library-third-party "0.0-20160609-f42b4a24"]
                  [org.clojure/tools.reader  "1.0.0-beta4"]
                  [org.clojure/tools.nrepl   "0.2.12" :scope "test"]
                  [danlentz/clj-uuid                         "0.1.6"]

                  [adzerk/boot-test                          "1.1.2"         :scope "test"]
                  [adzerk/boot-cljs          "1.7.228-1"]
                  [adzerk/boot-cljs-repl     "0.3.3" :scope "test"]
                  [adzerk/boot-reload        "0.4.12" :scope "test"]
                  [com.google.guava/guava "19.0"]
                  ;[com.google.javascript/closure-compiler "v20160315"]
                  ;[com.google.javascript/closure-compiler-externs "v20160315"]
                  [ring/ring-core            "1.6.0-beta5"]
                  [ring/ring-defaults        "0.2.1"]
                  [com.cemerick/piggieback   "0.2.1" :scope "test"]
                  [weasel                    "0.7.0" :scope "test"]
                  [compojure                 "1.6.0-beta1"]

                  ;[hoplon/boot-hoplon        "0.3.0"]
                  [hoplon                    "6.0.0-alpha17"]

                  [pandeiro/boot-http        "0.7.3"]
                  [http-kit                  "2.2.0"]

                  [com.taoensso/sente        "1.11.0"]
                  [com.rpl/specter           "0.13.2"]

                  [com.andrewmcveigh/cljs-time "0.4.0"]

**Comment by laforge49** [comment]
I was looking through issue 277 and I'll note that I am not using slf4j, encore or timbre.

**Comment by danielcompton** [comment]
Are you able to strip things right back to the minimal Sente reference example and start adding dependencies and code back in until the error reoccurs?

**Comment by laforge49** [comment]
I've no idea. I did the sente integration a long time back. And that sounds like a whole lot of work.

I noticed most things work fine. I just get this seemingly spurious error when I execute my logoff and also at startup.

I just have no idea where to start, as the traceback does not touch my code.

**Comment by laforge49** [comment]
Hmm. Even going back to 1.10 I am getting a variety of errors. Sigh.

I had to update to the latest clojure/clojure script because of a reader bug involving keyword namespaces. But then I went on a rampage. :-(

**Comment by laforge49** [comment]
Adding the following code fixed it:


(defmethod event-msg-handler :chsk/ws-ping
  [{:as ev-msg :keys [id]}]
  )
