### ISSUE TITLE
Example project not working on Windows

### ISSUE THREAD

**Issue by tmbb** [ptaoussanis/sente#297]
When I try to play with the example project the server loads fine, but the javascript doesn't load at all.
I know that a ``target/main.js`` file is being generated, but when go to: ``http://localhost:55336/main.js``, content of the served file is this:

```
../../target/main.js
```
This fails (obviously) with a javascript syntax error. I'm running the project as is, with no customizations at all. I am using:

OS: Windows 10 64 bits

```
> leiningen -version
Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM
```
```
> java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

The broswers in which I tested this were Firefox 52 and Microsoft Edge 38.14393.0.0.

**Comment by eigin** [comment]
How do you run the project? `lein start`?

**Comment by tmbb** [comment]
Yes

**Comment by tmbb** [comment]
Update: cljs compilation works fine on linux. However, in linux, `public/main.js` is a symlink to `target/main.js`. This is probably not very portable to windows. I wonder if this is the cause?
(I could just not care and develop under a linux VM on windows, but the cljs compiler is already quite slow and running it inside a VM wold probably make it slower)

**Comment by ptaoussanis** [comment]
Hi there,

Sorry for the delayed response. This indeed looks like an issue with the symlink not working correctly on Windows. If there's demand, would be open to review a PR that removes the need for the symlink.

Cheers!

**Comment by tmbb** [comment]
Sorry for my late response too. It's not really needed, I guess. I can always spin a linux VM to run this if necessary. Thanks!

**Comment by laforge49** [comment]
Happy to report that sente full example works "virtually unmodified" on windows 10.

1. Be sure developers mode is set so that the mklink command will work.
2. use mklink to change the link from ../../target to ..\..\target in resources/public.

**Comment by laforge49** [comment]
to ". . \ . . \ target"

**Comment by laforge49** [comment]
OK. I've reworked the full example for v1.11.0 to work with boot. And by adding a .cljs.edn file, I was able to eliminate the symbolic link, which means everything runs fine on windows 10 now as well as linux.

See https://github.com/laforge49/sente-boot/

**Comment by clartaq** [comment]
Doesn't work on macOS either.

Also won't even compile with Java 9 without adding ` :jvm-opts ["--add-modules" "java.xml.bind"]
` to the project file.

**Comment by clartaq** [comment]
Disregard. 
Working now (with `:jvm-opts ["--add-modules" "java.xml.bind"]`). Re-cloned, added line to `project.clj` and it works. The symlink was broken before.

**Comment by ptaoussanis** [comment]
@clartaq No problem, thanks for following up 👍

**Comment by ptaoussanis** [comment]
@laforge49 Thanks for the extra info Bill (and for the linked example!). Apologies about the delay replying.

**Comment by ptaoussanis** [comment]
Closing this since @laforge49's examples are now correctly linked from the README's [list of examples](https://github.com/ptaoussanis/sente#example-projects) 👍
