### ISSUE TITLE
On namespace reload, `:uid` key is set to nil.

### ISSUE THREAD

**Issue by venantius** [ptaoussanis/sente#298]
Hey there!

First of all, I'm loving this library and am looking forward to doing some really cool stuff with it. So thanks for the investment in making it.

Next: I've been running into an issue in development where the `:uid` key will be set to nil right after reloading a server-side namespace.

As far as I can tell, this should never happen: my handshake endpoint should always inject a random UUID into the session key, as follows:

```clojure
(defn add-random-uid
  [req]
  (assoc-in req [:session :uid] (str (java.util.UUID/randomUUID))))

(defroutes my-app-routes
  ;; <other stuff>

  ;;; Add these 2 entries: --->
  (GET  "/chsk" req (add-random-uid (ring-ajax-get-or-ws-handshake req)))
  (POST "/chsk" req (add-random-uid (ring-ajax-post req)))
  (route/resources "/")
  (route/not-found "<h1>Resource not found</h1>"))
```

In practice what happens is that after I reload this namespace into the REPL and then refresh the client-side page, the client gets a `:taoensso.sente/nil-uid` UID. If I refresh the page a second time (without otherwise changing any state on the client or server), I'll get a UUID set properly. 

And, just as a somewhat related note, if I reload the server-side namespace and then trigger a Figwheel reload (by saving a client-side cljs file), the first refresh client-side does give me the right UUID.

Any thoughts on what's going on here and how to avoid it? My suspicion is that since I call `make-channel-socket!` in the same namespace as my defroutes, something weird is going on when those get reloaded (and re-def'd) - but that's just a theory and I don't have anything concrete to back it up.

Cheers!

**Comment by ptaoussanis** [comment]
Hey there,

> First of all, I'm loving this library and am looking forward to doing some really cool stuff with it. So thanks for the investment in making it.

You're very welcome, thanks for saying so!

> If I refresh the page a second time (without otherwise changing any state on the client or server), I'll get a UUID set properly.

Silly question, but have you tried reversing the middleware order? I.e. `add-random-uid` _before_ `ring-ajax-get-or-ws-handshake`, etc.?

The problem you're describing could be the result of you setting up the appropriate session only _after_ the Sente handshake is completed. For the user-id to be properly set, you'll want the session to be ready _before_ the handshake. If that makes sense?

**Comment by venantius** [comment]
Ah, marvelous, that works. Cheers!

**Comment by ptaoussanis** [comment]
Great, no problem :-)
