### ISSUE TITLE
When used in the same project that uses namespaced maps, error: "Reader tag must be a symbol"

### ISSUE THREAD

**Issue by levitanong** [ptaoussanis/sente#303]
e.g.
```clj
#:ns{:foo "bar"
     :baz "derp"}
```
The above only compiles if sente is not a dependency. Once sente is added to `build.boot` (haven't checked with leiningen) the following error will show:

`Reader tag must be a symbol`

I'm guessing it has something to do with the clojure version.

**Comment by danielcompton** [comment]
Can you provide a minimal example? I think that syntax only works in Clojure 1.9, but it's surprising that adding Sente as a dependency causes this.

**Comment by levitanong** [comment]
Got it, working on a demo repo.

**Comment by levitanong** [comment]
https://github.com/levitanong/sente-demo

**Comment by danielcompton** [comment]
I took a look at your project and could reproduce the issue. The smallest minimal change I could make to stop it from happening was to put Clojure and ClojureScript higher in the boot dependencies list than Sente. My uninformed speculation is that Boot is taking Sente's CLJS dependency, not your explicit one that is lower on the list. I'm not really sure as I don't know much about boot, but I don't know if this is a Sente issue? Maybe talk to the Boot folks?

**Comment by nha** [comment]
@levitanong  You could try ignoring clj/cljs sente dependency version: `[sente "X.Y.Z" :exclusions [org.clojure/clojure org.clojure/clojurescript]]`

**Comment by levitanong** [comment]
Welp, that seems to work. Thanks, @danielcompton and @nha!
