### ISSUE TITLE
An updated/alternative integration with boot

### ISSUE THREAD

**Issue by laforge49** [ptaoussanis/sente#304]
I've redone sente-boot to work with sente v1.11.0:

https://github.com/laforge49/sente-boot/

Feel free to add it to your examples on the sente readme. :-)

**Comment by laforge49** [comment]
Note that by adding a .cljs.edn file, a symbolic link to main.js is no longer needed. So the code should run equally well on linux and windows 10.

**Comment by laforge49** [comment]
See also https://github.com/laforge49/sente-boot-reagent

**Comment by danielcompton** [comment]
I've added them. Thanks for this!
