### ISSUE TITLE
Bad package (only under advanced compilation)

### ISSUE THREAD

**Issue by danielsz** [ptaoussanis/sente#306]
Hi Peter, 

Weird error that creeps up under advanced compilation only. 
``` shell
2017-06-22_07:54:36.80789 17-06-22 07:54:36 asher DEBUG [taoensso.sente:208] - Bad package: [[:twitter-fu/api {:complete-registration? true}] #object[String 69bf1b]] (clojure.lang.ExceptionInfo: Invalid number format [69bf1b] {:type :reader-exception})
```
The event being sent is a map that contains a custom tag. Data readers are provided to handle it, and it works fine when compiling cljs with no optimizations. 

Under advanced compilation, I most often see this message (but not always). 

The code for the serializer is [here](https://github.com/danielsz/maarschalk/blob/dc39519fcf3ffd9c3684eda938c7ba2ecf231955/src/maarschalk/serializers.cljc). 
The data reader is [here](https://github.com/danielsz/maarschalk/blob/dc39519fcf3ffd9c3684eda938c7ba2ecf231955/src/data_readers.clj). 

I'm stumped. Any idea how to debug this? Thank you!

**Comment by danielcompton** [comment]
What is the data that is actually being sent? I would try by removing Sente from the equation and just use the serialiser Sente is using to see if this continues?

**Comment by danielsz** [comment]
That is good advice. I think it's unlikely `sente` has anything to do with it.

**Comment by danielsz** [comment]
Turned out to be the `output-wrapper` compiler option not being set to `true`. This is a landmine, and we'll try to change this in our build tools.

Sorry for the noise.

https://github.com/boot-clj/boot-cljs/wiki/Troubleshooting
https://github.com/boot-clj/boot-cljs/issues/64
