### ISSUE TITLE
Had to remove a dependency to start example project 

### ISSUE THREAD

**Issue by vadim0x60** [ptaoussanis/sente#314]
In order to start the example project, I had to remove `[com.cemerick/austin "0.1.6"]` from `project.clj`. Otherwise, I get
`Caused by: java.io.FileNotFoundException: Could not locate cemerick/piggieback__init.class or cemerick/piggieback.clj on classpath.`

**Comment by vadim0x60** [comment]
Here's my `profiles.clj`:

`{:user-global {
    :plugins [[lein-try "0.4.3"] [lein-ancient "0.6.10"] [lein-beanstalk "0.2.7"] [lein-exec "0.3.7"]]
    :dependencies [[org.clojure/tools.trace "0.7.9"] [morse "0.2.7"]]
 }
 :user [:user-global]
 }`

**Comment by ptaoussanis** [comment]
Thanks for the report Vadim! Closing this since I'm about to push the solution provided by @theasp with #315.
