### ISSUE TITLE
ajax-resp is vectors, not map

### ISSUE THREAD

**Issue by sova** [ptaoussanis/sente#316]
client:
```
(sente/ajax-lite "/login"
              {:method :post
               :headers {:X-CSRF-Token (:csrf-token @chsk-state)}
               :params  {:email (:email @f9-login-input-atom)
                         :password (:password @f9-login-input-atom)}}
(fn [ajax-resp]
                (.log js/console (:?content ajax-resp))
```
returns: ["email" "v@v.v"] ["password" "vvv]  and not the expected {:email "v@v.v" etc}

server:
```
`  (POST "/login" request
    (let [fp (:form-params request)
          email (:email fp)
          pw    (:password fp)]
        {:status 200
         :headers {"Content-Type" "text/html"}
         :body fp}))`
```

`(:email fp)` returns nil.  is this because of xhr-coerce ?

Am I using this wrong?

**Comment by sova** [comment]
So I learned that if in clojure in {:maps with :keys ""} you can actually use anything for the "key" as long as it is unique.

This means that even though sente/ajax-lite strips away the forward-leading colons :from :keywords it is still possible to access the data just like in a map:

```
(def map {"email"  "h@h.h"
                 "pass"    "hhh"})
```

Submitted username and password (on the serverside) can be gotten by  `(get map "email") ` and `(get map "pass")` for the example above.

I always thought I was messing something up in Sente trying to do HTTP POST /login  but it turns out I was missing this very special caveat in the ajax-lite call.

Is it intended to work this way?  Anyway, I am super happy I got this working.  Perhaps I'll add something to the readme, we could really make things a lot friendlier for newer users.

**Comment by theasp** [comment]
Hi @sova,

The server is returning data of type `text/html` which won't be interpreted as something `ajax-lite` will parse, like JSON.  Using a map for the body of your response in this case is not going to do what you want as it will eventually be converted into a string.  A map in Clojure is usable as a sequence, which will return each key value pair from the map as vectors, which will be the result you see. If you want to transfer data to/from the server to the client when posting to this URL you will need to use appropriate middleware (like `ring-middleware-format`), and probably remove the `Content-Type` header as well.

Also keep in mind that when transferring data using JSON (or forms), you will see keywords converted to strings as well, i.e. `:email` will become `email`.  On the server side the `keywordize-params` middleware can make everything a keyword, but on the client side you will probably want to use `clojure.walk/keywordize-keys` if `ajax-lite` doesn't do it for you.
