### ISSUE TITLE
`chsk-send!` function overloads not working properly

### ISSUE THREAD

**Issue by ignorabilis** [ptaoussanis/sente#324]
Hi,

We are having an issue with `chsk-send!` with versions `1.11.0` & `1.12.0` (not tested with previous versions).

So basically this works and we get the request on the server:
```
(sockets/chsk-send!
      [ws-handler ws-data]
      timeout
      (fn no-op []))
```

and this one does not:
```
(sockets/chsk-send!
      [ws-handler ws-data])
```

The setup is as per the documentation:
```
(let [{:keys [chsk ch-recv send-fn state]}
        (sente/make-channel-socket! "/chsk" {:type :auto})]
    (def chsk chsk)
    (def ch-chsk ch-recv)
    (def chsk-send! send-fn)
    (def chsk-state state))
```

**Comment by ptaoussanis** [comment]
Hi Ivan!

Only had a chance to skim this. Seems quite strange; the 2-argument variation just [calls through](https://github.com/ptaoussanis/sente/blob/d29165be586f63aa3e5ae6a2c7428c750076098d/src/taoensso/sente.cljc#L805) to the other.

> and this one does not:

When you say "does not" [work], you mean the server never receives the request?

Could you maybe provide a minimal reproducible case?
