### ISSUE TITLE
Add support for WebSocket requestOptions

### ISSUE THREAD

**Issue by Deraen** [ptaoussanis/sente#325]
In Node (and React-native) the WebSocket constructor can take additional parameter which can set the HTTP request options for the initial request. This can be used to set headers etc.

https://github.com/theturtle32/WebSocket-Node/blob/master/docs/W3CWebSocket.md#constructor
https://github.com/facebook/react-native/blob/29fb2a8e90fa3811f9485d4b89d9dbcfffea93a6/Libraries/WebSocket/WebSocket.js#L97

Inconveniently `W3CWebSocket` and React-Native class take different parameters.

Maybe it would be best to add option to provide a function to create the WebSocket object?

Currently I'm using workaround to replace global WebSocket object:

```clj
(defonce orig-websocket (.-WebSocket goog/global))
(defonce new-websocket
  ;; Note React-native 0.49 changes headers parameters to options
  ;; and headers is property inside options.
  (set! (.-WebSocket goog/global) (fn [url & [protocols headers]]
                                    (let [headers (or headers #js {})]
                                      (gobj/set headers "X-Access-Key" config/api-access-key)
                                      (new orig-websocket url protocols headers)))))
```

**Comment by ptaoussanis** [comment]
@Deraen Hi Juho, apologies for the long delay replying!
An option for this will be included in forthcoming v1.18 release.

Cheers!
