### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by lw1990** [ptaoussanis/sente#328]
The main/official example compiles/runs successfully according to the command prompt, but in the browser, nothing shows up in the text-area for the client output. Also, I have no idea what you mean by 'observe std-out', but there's no such file named 'std-out' on my machine, and the command prompt shows only "broadcasting server>user: 0 uids" messages 

Basically it doesn't work, firefox and chrome tested

**Comment by alexakarpov** [comment]
^ Describes my experience too.
Though std-out most likely refers to the console after executing `lein run` =) but the only output present, after the startup, is:

DEBUG [example.server:149] - Broadcasting server>user: 0 uids

, and on the webpage, all buttons appear to do nothing.

**Comment by ptaoussanis** [comment]
Hello! Sorry for the confusion.

By `std-out` I meant [Standard Out](https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)). In this case: wherever your server logging is being directed.

> and on the webpage, all buttons appear to do nothing.

Do you see any output in the browser's developer console?

**Comment by alexakarpov** [comment]
> Do you see any output in the browser's developer console?

Hello mate,
Very sorry for dropping the ball and not checking for the responses. Things started to work. Rather mysteriously, too - output is dumped into the text box, which didn't have anything appearing in it before. I did notice leiningen also re-fetched a few dependencies, makes me wonder of something was broken in there.

**Comment by ptaoussanis** [comment]
No problem, thanks for the follow-up 👍

**Comment by endrebak** [comment]
I have the same problem: nothing registers in the text area or js console, and the developer console looks like this:

![Screenshot 2020-01-30 at 12 13 32](https://user-images.githubusercontent.com/17778898/73445143-56c39f80-435a-11ea-9a14-dba527f6c829.png)

The lein run has a few warnings before the server starts to run:

```
Reflection warning, cemerick/austin.clj:50:3 - call to method stop can't be resolved (target class is unknown).
Reflection warning, cemerick/austin.clj:72:3 - reference to field getAddress can't be resolved.
Reflection warning, cemerick/austin.clj:72:3 - reference to field getPort can't be resolved.
Reflection warning, cemerick/austin.clj:77:14 - call to method getBytes can't be resolved (target class is unknown).
Reflection warning, cemerick/austin.clj:82:34 - call to method write on java.io.OutputStream can't be resolved (argument types: unknown).
Reflection warning, cemerick/austin.clj:168:47 - reference to field getRequestHeaders can't be resolved.
Reflection warning, cemerick/austin.clj:191:21 - call to method endsWith can't be resolved (target class is unknown).
Reflection warning, cemerick/austin.clj:439:23 - call to method exec on java.lang.Runtime can't be resolved (argument types: unknown).
Reflection warning, cemerick/austin.clj:449:5 - reference to field destroy on java.lang.Object can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/load_file.clj:87:38 - reference to field recv on java.lang.Object can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/load_file.clj:88:46 - call to method recv on java.lang.Object can't be resolved (no such method).
Reflection warning, clojure/tools/nrepl/middleware/load_file.clj:93:27 - call to method send on java.lang.Object can't be resolved (no such method).
Reflection warning, clojure/tools/nrepl/server.clj:143:33 - call to java.net.InetSocketAddress ctor can't be resolved.
Reflection warning, clojure/tools/nrepl/server.clj:145:25 - call to java.net.InetSocketAddress ctor can't be resolved.
Reflection warning, cemerick/piggieback.clj:54:3 - call to static method putProperty on org.mozilla.javascript.ScriptableObject can't be resolved (argument types: unknown, java.lang.String, java.lang.Object).
Reflection warning, /private/var/folders/ld/dnys24ds0612rkybkfyhcsnm0000gn/T/form-init350797095687159204.clj:1:1040 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
Reflection warning, ring/util/codec.clj:95:5 - call to static method encode on java.net.URLEncoder can't be resolved (argument types: java.lang.String, unknown).
Reflection warning, ring/util/codec.clj:130:6 - call to static method decode on java.net.URLDecoder can't be resolved (argument types: java.lang.String, unknown).
Reflection warning, instaparse/util.clj:5:3 - call to java.lang.RuntimeException ctor can't be resolved.
Reflection warning, instaparse/util.clj:11:3 - call to java.lang.IllegalArgumentException ctor can't be resolved.
Reflection warning, hiccup/util.clj:78:19 - call to static method encode on java.net.URLEncoder can't be resolved (argument types: java.lang.String, unknown).
20-01-30 11:13:10 eduans-10-20-181-242.stolav.ntnu.no INFO [example.server:240] - Web server is running at `http://localhost:51581/`
```

**Comment by endrebak** [comment]
Tried it in safari too btw.

**Comment by endrebak** [comment]
The problem: I was using `lein run` not `lein start` 😳 😆
