### ISSUE TITLE
detecting the state of chsk

### ISSUE THREAD

**Issue by WIZARDELF** [ptaoussanis/sente#331]
before i do server>client chsk-send!, is it possible to check whether chsk for that client-id is open or not? and how?

**Comment by Kejia** [comment]
i investigated the code and tried some options i'd found. it seems that utilizing _connected-uids_ is a reasonable solution. please correct me if there is a better way.

**Comment by ptaoussanis** [comment]
Your current approach is reasonable, apologies for the long delay replying.
