### ISSUE TITLE
Sente is incompatible with http-kit 2.4.0-alpha3

### ISSUE THREAD

**Issue by arttuka** [ptaoussanis/sente#336]
[As described here](https://github.com/http-kit/http-kit/issues/318#issuecomment-454212919), the handling of new WebSocket connections has been changed in http-kit version 2.4.0-alpha3. Calling `send!` inside the body of `org.httpkit.server/with-channel` is no longer allowed, but the http-kit adapter tries to do that in [http_kit.clj:30](https://github.com/ptaoussanis/sente/blob/0268f93d98bd21788c3e36b5d6f7e778897882ff/src/taoensso/sente/server_adapters/http_kit.clj#L30). This causes the WebSocket connection to fail.

**Comment by ptaoussanis** [comment]
Will be addressed in the next release, which I'll be pushing in the next hour. Closing!
