### ISSUE TITLE
Impossible to pass custom settings to the XHR pool 

### ISSUE THREAD

**Issue by p-himik** [ptaoussanis/sente#342]
The client side of my app tries to get all kinds of data upon the first connection - it works perfectly with WS and fails some requests with long polling because `:xhr-pool-depleted` (default pool size is 10).

I'm not sure if being able to increase the pool size is the correct solution here. Maybe a better way to handle it would be to somehow make Sente wait till there's a free connection.
What do you think?

**Comment by ptaoussanis** [comment]
@p-himik Hi Eugene, apologies for the long delay replying.
This will be addressed in the forthcoming Sente v1.18:

- Support will be added for a custom XHR pool.
- Support will be added to wait for an available XHR from pool.

Thanks for pinging about this, and again apologies for the delay.
