### ISSUE TITLE
trying to upgrade boot-sente

### ISSUE THREAD

**Issue by laforge49** [ptaoussanis/sente#344]
Been working on upgrading the boot-sente example at 
https://github.com/laforge49/sente-boot/blob/master/build.boot
but I keep getting hung up on http-kit.

Any thoughts? Thanks in advance. Bill

      clojure.lang.ExceptionInfo: clojure/lang/IFn
    data: {:file "org\\httpkit\\server.clj", :line 66}
  java.lang.NoClassDefFoundError: clojure/lang/IFn
java.lang.ClassNotFoundException: clojure.lang.IFn
                                   ...
                  clojure.core/load/fn                          core.clj: 6007
        clojure.core/load/invokeStatic                          core.clj: 6006
                     clojure.core/load                          core.clj: 5990
                                   ...

**Comment by ptaoussanis** [comment]
@laforge49 Hi Bill, apologies for the long delay replying.
Is this issue still relevant?

Is it possible you have a dependency conflict of some sort? I'm not familiar with boot, but with Lein you could run something like `lein :deps tree` to check.

**Comment by ptaoussanis** [comment]
Closing this so long as part of issue triage, but please feel free to re-open if this is still relevant!
