### ISSUE TITLE
Add support for specifying :port when connecting from the client

### ISSUE THREAD

**Issue by pieterbreed** [ptaoussanis/sente#348]
In our environment, we want to connect to a WS host on a different port than what the (dev) HTML/CSS/cljs assets are being server from.

Currently, the port value is read from the browser window.

# Requirement

```
(let [wss-uri (url "http://localhost:8000")]
  (sente/make-channel-socket! (:path wss-uri)
                                        nil ; CSRF...
                                        {:type :auto
                                         :port (:port wss-uri) ; override
                                         :host (:host wss-uri)}))
```

I did this work locally and have a merge request available for it.

**Comment by ptaoussanis** [comment]
Thanks Pieter, merging your PR now.
