### ISSUE TITLE
Switch to encore v2.117.0

### ISSUE THREAD

**Issue by jwr** [ptaoussanis/sente#355]
Encore v2.117.0 contains a fix for the deprecation of `goog.structs/Map`, while sente still depends on v2.116.0, which causes problems:

```
WARNING: Use of undeclared Var goog.structs/Map at line 2870 app/web/js/out/taoensso/encore.cljs
```

Perhaps the encore dependency could be bumped to v2.117.0 and a new sente tagged/released?

**Comment by ptaoussanis** [comment]
Hi Jan! Will get back to you about this tonight 👍

**Comment by ptaoussanis** [comment]
Addressed in https://github.com/ptaoussanis/sente/releases/tag/v1.15.0, now on Clojars 👍
