### ISSUE TITLE
                         ;; Firefox calls "onclose" while unloading,                         ;; Ref. http://goo.gl/G5BYbn:                         (if (:clean? last-ws-close)                           (do                             (debugf "Clean WebSocket close, will not attempt reconnect")                             (swap-chsk-state! chsk                               #(assoc % :last-ws-close last-ws-close)))                           (do

### ISSUE THREAD

**Issue by Aatranquyen150397** [ptaoussanis/sente#384]
;; Firefox calls "onclose" while unloading,
                        ;; Ref. http://goo.gl/G5BYbn:
                        (if (:clean? last-ws-close)
                          (do
                            (debugf "Clean WebSocket close, will not attempt reconnect")
                            (swap-chsk-state! chsk
                              #(assoc % :last-ws-close last-ws-close)))
                          (do

**Comment by Aatranquyen150397** [comment]
;; Firefox calls "onclose" while unloading,
                        ;; Ref. http://goo.gl/G5BYbn:
                        (if (:clean? last-ws-close)
                          (do
                            (debugf "Clean WebSocket close, will not attempt reconnect")
                            (swap-chsk-state! chsk
                              #(assoc % :last-ws-close last-ws-close)))
                          (do

**Comment by ptaoussanis** [comment]
Hi there!

I'm afraid that it isn't clear what the purpose of this issue is - would you please clarify?

Thanks
