### ISSUE TITLE
`generic-node-adapter` not working on node v14.18.0

### ISSUE THREAD

**Issue by lane-s** [ptaoussanis/sente#392]
It seems like at some point, the type of the data passed to the we socket "message" event callback changed from string to `Buffer`, which needs to be handled by the adapter (probably by simply doing `(.toString data)` when passing the data on to sente). Otherwise the invariant at `taoensso.sente:208` is violated and no message can be received without crashing the server.

**Comment by ptaoussanis** [comment]
Note to self: is this report perhaps obsolete due to #398, #404?

**Comment by ptaoussanis** [comment]
Closing as part of issue triage since I believe this may already be resolved on master.
Please feel free to re-open if this issue is still relevant!
