### ISSUE TITLE
Example of what to pass for CSRF client argument for node.js

### ISSUE THREAD

**Issue by dmg46664** [ptaoussanis/sente#406]
The node js example is from 1.11.0
https://github.com/theasp/sente-nodejs-example/blob/master/project.clj#L20

The API now insists on a CSRF argument for the client:
https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente.cljc#L1670

What are you supposed to pass here? nil? I'm getting other errors and unsure if this is the issue.
I am migrating client code from https://www.npmjs.com/package/ws (their api and core.async) and they don't insist on passing any equivalent argument.

Thanks.

**Comment by ptaoussanis** [comment]
@dmg46664 Hi Daniel,

Please see the README [Getting Started](https://github.com/ptaoussanis/sente#getting-started) section - it includes info on CSRF. Would suggest searching the README in general for "csrf" - since there's a few different places that CSRF is discussed.

Hope that helps! Cheers :-)

**Comment by dmg46664** [comment]
@ptaoussanis 

I looked at the example on the readme.
```(def ?csrf-token
  (when-let [el (.getElementById js/document "sente-csrf-token")]
    (.getAttribute el "data-csrf-token")))
```

This code will fail for node.js as there is no DOM for `node.js`
`ReferenceError: document is not defined`

Anything on the page relating to CSRF and middleware isn't relevant for me as I'm not running a server.
I.e. the following isn't relevant.
```
Security: CSRF protection?
This is important. Sente has support, and use is strongly recommended. You'll need to use middleware like [ring-anti-forgery](https://github.com/ring-clojure/ring-anti-forgery) or [ring-defaults](https://github.com/ring-clojure/ring-defaults) to generate and check CSRF codes. The ring-ajax-post handler should be covered (i.e. protected).
```

Please suggest where else I'm supposed to look?

**Comment by dmg46664** [comment]
CSRF is only related to interaction in the browser based on my understanding.
Therefore my expectation is if connecting from an app outside the browser (node.js or java), I would be able to ignore this argument.
Hopefully you can point out where I've made a mistake.

**Comment by ptaoussanis** [comment]
Hi Daniel, can you explain in a little more detail exactly what you're doing and what error you're seeing?

> Anything on the page relating to CSRF and middleware isn't relevant for me as I'm not running a server.

What is your Sente client meant to connect to?

If CSRF isn't relevant for your use-case, it _should_ be possible to disable the CSRF checks as per the API docs [here](http://ptaoussanis.github.io/sente/taoensso.sente.html#var-make-channel-socket-client.21) and [here](http://ptaoussanis.github.io/sente/taoensso.sente.html#var-make-channel-socket-server.21), i.e.:

  - Provide a `nil` `:csrf-token-fn` option to your **server** constructor.
  - Provide a `nil` `?csrf-token-or-fn` argument to your **client** constructor.

It's very possible I'm misunderstanding something about your use case though.

**Comment by dmg46664** [comment]
@ptaoussanis I can't see where it states you can pass a `nil` to `?csrf-token-or-fn` in the link you've shared.
If it said that I'd be happy and therefore my error is somewhere else.
Please can we update the docs?

<img width="710" alt="image" src="https://user-images.githubusercontent.com/1296603/180816044-c9cd5ca1-8ffb-4e9b-a053-6c50e69ea8d8.png">

**Comment by ptaoussanis** [comment]
Just [updated](https://github.com/ptaoussanis/sente/commit/841b33e1c7e27839bf0fadee6551fbafaea29b06) docstrings on master, hope that's better?

**Comment by dmg46664** [comment]
Great! Clear! Thanks 👍
