### ISSUE TITLE
Triggering :chsk/uidport-close event only 5 seconds after a WebSocket channel is closed

### ISSUE THREAD

**Issue by khmelevskii** [ptaoussanis/sente#414]
Can I configure this 5 second? For example I'm going to use 1500ms. In case that I will be able to change this value it will influence to something?

**Comment by ptaoussanis** [comment]
@khmelevskii Hi Yurii. No, currently this isn't configurable.

Should be easy to make this configurable [here](https://github.com/ptaoussanis/sente/blob/841b33e1c7e27839bf0fadee6551fbafaea29b06/src/taoensso/sente.cljc#L845), PR welcome. Would suggest this value be separately configurable for WebSockets and Ajax, both defaulting to 5000 msecs: e.g. `:msecs-allow-reconnect-before-close-ws`, `:msecs-allow-reconnect-before-close-ajax`.

Just curious - what's your motivation in wanting a shorter timeout here?

**Comment by khmelevskii** [comment]
@ptaoussanis great, I will create PR.

About motivation. In my app I have user online/offline status on UI. To show this I'm using `:chsk/uidport-open` and `:chsk/uidport-close` events. When `:chsk/uidport-close` triggered I'm checking connected-uid and if user doen't exist (doesn't have connected other clients)I set status of this user to "offline".

**Comment by ptaoussanis** [comment]
> When :chsk/uidport-close triggered I'm checking connected-uid and if user doen't exist (doesn't have connected other clients)I set status of this user to "offline".

So that's a typical use case, but what's your motivation for reducing the timeout specifically? Note that there's tradeoffs with a lower timeout - you'll get more false-positive `:chsk/uidport-close` events with a lower timeout. I.e. could make your online/offline status UI more noisy.

**Comment by khmelevskii** [comment]
I think this is totally fine to be more noisy here. For example I can see that status in Slack updates immediately (when user refresh slack page I can see that his status blink).

**Comment by ptaoussanis** [comment]
Great, thanks for the confirmation. PR welcome 👍

**Comment by ptaoussanis** [comment]
Closing, this will be included in forthcoming v1.18 👍
