### ISSUE TITLE
After upgrading to 1.18 event :chsk/uidport-close desn't work

### ISSUE THREAD

**Issue by khmelevskii** [ptaoussanis/sente#430]

**Comment by ptaoussanis** [comment]
@khmelevskii Hi Yuri, can you please explain in some more detail what you mean by "doesn't work"?

Is the behaviour reproducible with the [reference example](https://github.com/ptaoussanis/sente/tree/master/example-project)?

**Comment by khmelevskii** [comment]
@ptaoussanis this example dosn't use event `:chsk/uidport-close`.

So, I've just recognized that after upgrading to 1.18 my handler `:chsk/uidport-close` doesn't trigger when user close connection. The same code works well in 1.17

I'm doing somethings like this
```
[taoensso.sente.server-adapters.http-kit :refer [get-sch-adapter]]
...

(defonce ^:private ws-channel
  (sente/make-channel-socket-server!
   (get-sch-adapter)
   {:packer        :edn
    :csrf-token-fn nil}))

(def ^:private ws-handshake
  (:ajax-get-or-ws-handshake-fn ws-channel))

(def ^:private ws-send!
  (:send-fn ws-channel))

(def ^:private ws-recv
  (:ch-recv ws-channel))

(def ^:private connected-uids
  (:connected-uids ws-channel))

(defmulti -event-msg-handler
  "Multimethod to handle Sente `event-msg`s
   Dispatch on event-id"
  :id)

(defmethod -event-msg-handler
  :default ; Default/fallback case (no other matching handler)
  [_]
  nil)

(defmethod -event-msg-handler :chsk/uidport-open
  [_]
  (println "Works"))

(defmethod -event-msg-handler :chsk/uidport-close
  [_]
  (println "Not triggering"))

(defn event-msg-handler
  "Wraps `-event-msg-handler` with logging, error catching, etc."
  [ev-msg]
  (-event-msg-handler ev-msg))

(sente/start-server-chsk-router!
   ws-recv event-msg-handler)
```
Checked migration instruction and can't see any related to this issue things.

**Comment by khmelevskii** [comment]
When I enabled :debug log level I can see that this server closed ws
```
DEBUG [taoensso.sente:896] - [ws/on-close] Server sch closed for 
```

But method `:chsk/uidport-close` didn't trigger

**Comment by ptaoussanis** [comment]
Thanks for the context 👍

> this example dosn't use event :chsk/uidport-close.

The reference example logs every event, [here](https://github.com/ptaoussanis/sente/blob/5feac776c5ad73059b08df4b69bab3a6c5d97f7f/example-project/src/example/server.clj#L204).

Am investigating right now, will come back to you 👍

**Comment by khmelevskii** [comment]
Hi Peter, I've just checked 1.8.1 and everything works great! Thank you for a quick fix and great library.

**Comment by ptaoussanis** [comment]
You're very welcome Yuri, cheers! :-)
