### ISSUE TITLE
Why does sente restrict ws communication to same-domain?

### ISSUE THREAD

**Issue by nodename** [ptaoussanis/sente#50]
I was hoping to use sente to provide web-socket access to a server from arbitrary external domains, not obviously an unreasonable use case (chat server for example). Could there be a workaround?

**Comment by danielcompton** [comment]
I'm not 100% clear on how to use this extension. Do we have to implement our own `chsk-url-fn`, or can we pass a map of the things we want somewhere?

**Comment by ptaoussanis** [comment]
Hi Daniel,

You can use the `:chsk-url-fn` option to override the default default chsk url fn:
```clojure
(def default-chsk-url-fn
  "(ƒ [path window-location websocket?]) -> server-side chsk route URL string.

    * path       - As provided to client-side `make-channel-socket!` fn
                   (usu. \"/chsk\").
    * websocket? - True for WebSocket connections, false for Ajax (long-polling)
                   connections.
    * window-location - Map with keys:
      :href     ; \"http://www.example.org:80/foo/bar?q=baz#bang\"
      :protocol ; \"http:\" ; Note the :
      :hostname ; \"example.org\"
      :host     ; \"example.org:80\"
      :pathname ; \"/foo/bar\"
      :search   ; \"?q=baz\"
      :hash     ; \"#bang\"

  Note that the *same* URL is used for: WebSockets, POSTs, GETs. Server-side
  routes should be configured accordingly."
  (fn [path {:as window-location :keys [protocol host pathname]} websocket?]
    (str (if-not websocket? protocol (if (= protocol "https:") "wss:" "ws:"))
         "//" host (or path pathname))))
```

I.e. you can replace that function with your own function of the same arguments that produces URLs of the form you prefer. Does that make sense?

**Comment by luposlip** [comment]
@danielcompton I'm using it with Sente 1.5.0-beta2 (https://clojars.org/com.taoensso/sente).

My code looks like this:
```
(sente/make-channel-socket! "/chsk"
   {:type :auto :packer packer
    :chsk-url-fn (constantly "ws://host:port/chsk")})
```
In this case the first parameter - "/chsk" in the above example - doesn't make much sense though, since it seems to be ignored completely and replaced by the :chsk-url-fn.

@ptaoussanis perhaps it would make sense to have  a :chsk-host-fn instead, and then concatenate the first url param and the host (if present)?

**Comment by ptaoussanis** [comment]
Hi Henrik, thanks for the example.

> In this case the first parameter - "/chsk" in the above example - doesn't make much sense though, since it seems to be ignored completely and replaced by the :chsk-url-fn.

It is ignored completely in your case (it's only purpose is to be sent to :chsk-url-fn for use by that fn). In your case I might suggest eliminating the "/chsk" to avoid confusion `(sente/make-channel-socket! nil <...>`.

> @ptaoussanis perhaps it would make sense to have a :chsk-host-fn instead, and then concatenate the first url param and the host (if present)?

Not sure I follow. What problem are you trying to solve exactly?

**Comment by danielcompton** [comment]
@ptaoussanis the issue I was trying to solve, and I suspect the most common one is that I am running my server and client on different hosts. Being able to specify a different host when creating the web socket would I suspect solve 95+% of uses where people need to change this.

**Comment by ptaoussanis** [comment]
Hi Daniel,

> @ptaoussanis the issue I was trying to solve, and I suspect the most common one is that I am running my server and client on different hosts. Being able to specify a different host when creating the web socket would I suspect solve 95+% of uses where people need to change this.

So, sorry - the :chsk-url-fn does or doesn't accommodate your use-case? If not, I'm still a little unclear why? You can change the host (or anything else) with the `:chsk-url-fn`.

**Comment by danielcompton** [comment]
Sorry that wasn't very clear. Providing a `:chsk-url-fn` does accommodate my specific (and presumably common) use case of different client and server hosts. I was suggesting (and I think @luposlip was implying) that it would be handy to have a second function alongside `default-chsk-url-fn`.

This function, say `chsk-host-fn-generator` would take a host parameter and return a `chsk-url-fn`. I imagine 90+% of people wanting a custom chsk-url-fn only need to change the host, and so don't need access to all of the other parameters available to them.

Does that make sense?

**Comment by ptaoussanis** [comment]
> Does that make sense/did I explain that ok?

Yes, I follow now - thanks for clarifying.

> it would be handy to have a second function alongside default-chsk-url-fn

I'm not too keen on that tbh; I tend to prefer fewer, more flexible extension points. In this case, I believe you need only a 1 line fn:
```clojure
(fn my-chsk-url-fn [path loc ws?] (default-chsk-url-fn path (assoc loc :host "my-host") ws?))
```

There's room for you to write a complex fn, but no need; you can certainly keep it simple (as in @luposlip's example).

Hope that helps?

**Comment by danielcompton** [comment]
I'm not sure if I was totally clear, I didn't need more extension points, I would still use `:chsk-url-fn` (I too prefer fewer extension points). I was just recommending that something like the function you just shared be added to Sente as a factory function that would fit the 90% case. So when someone comes to the common problem of "I have a client and server on different hosts", that there was this function available for them. Looking at `default-chsk-url-fn`, it wasn't immediately obvious to me what I needed to do to override the host.

**Comment by luposlip** [comment]
@ptaoussanis to clarify what I meant:

When you use :chsk-url-fn the first param to make-channel-socket! is ignored. This may be a bit confusing at first. I agree - it would be best to pass nil when using :chsk-url-fn to avoid confusion in the example.

But API wise I'd suggest to eliminate the first param completely when using the :chsk-url-fn.

One way could be to move the :chsk-url-fn in as the first param:

```
(sente/make-channel-socket!  (constantly "ws://host:port/chsk")
   {:type :auto :packer packer})
```

And still support the old form for backwards compatibility?

```
(sente/make-channel-socket!  "/chsk"
   {:type :auto :packer packer})
```

It would mean checking the "type" of the first param, which not everybody would like in an implementation, but for me it would make sense API wise.

**Comment by ptaoussanis** [comment]
> But API wise I'd suggest to eliminate the first param completely when using the :chsk-url-fn

The two are not mutually exclusive. You'll often want to mod the chsk-url-fn independently of the path. Path's just an input to chsk-url-fn; if you happen to mod chsk-url-fn to ignore the path, that's okay - but not typical.

As an example, if one's using multiple sockets - you may want different paths for different sockets, but the same url logic underneath which decides how a path translates to a URL.

**Comment by ptaoussanis** [comment]
@danielcompton:

> Looking at default-chsk-url-fn, it wasn't immediately obvious to me what I needed to do to override the host.

Understood. Think this might be something we could try address through documentation/examples?

**Comment by luposlip** [comment]
@ptaoussanis makes sense, got it!

**Comment by danielcompton** [comment]
@ptaoussanis sure, documentation + giving that fn as a sample would be great.
