### ISSUE TITLE
[Perf] Investigate experimental compression IPacker implementations

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/sente#73]
E.g. https://github.com/nodeca/pako, https://news.ycombinator.com/item?id=8314749, http://pieroxy.net/blog/pages/lz-string/index.html, etc.

Experimenting with this would be easy so **PRs and comments welcome**. See [here](https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/interfaces.cljx) for the IPacker interface and [here](https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/packers/transit.cljx) for an example implementation.

**Comment by xfeep** [comment]
Hi, If messages are sent by SSEs/long pollings they can be compressed by web server, e.g.  gzip on most of modern web servers
If messages are sent by websocket they maybe also can be compressed by web server, e.g. perframe-compression, at least jetty 9 and tomcat 8 support it. I 'm also plan to make nginx-clojure support perframe-compression.
So maybe there will be less and less need for the feature about compression IPacker implementations.

**Comment by ptaoussanis** [comment]
Hi Zhang,

Thanks for your input! I don't have any strong feelings about this.

Packer-level compression _may_ be nice to have for cases where client/server compression isn't available. It might also allow more flexibility - e.g. compression caching based on information only available at an application (not server) level. Known-keyword minification and other data structure-aware compression may also be handy.

Would it be worth the effort? I'm not sure, haven't looked into it closely. If it's easy to add support, does bring some benefits, and someone felt like doing the work - I'd be happy to take a look at a PR.

I'd definitely call this low-priority though :-)

**Comment by whodidthis** [comment]
Out of interest, in light of BREACH(?), looking at the [TLS 1.3 spec](https://tlswg.github.io/tls13-spec/#rfc.section.1.2) mentions removal of support for compression.

**Comment by ptaoussanis** [comment]
Thanks @whodidthis, that's a useful data point.

**Comment by ptaoussanis** [comment]
Closing as part of issue triage due to apparent lack of community interest
