### ISSUE TITLE
Clojure / JVM client for Sente

### ISSUE THREAD

**Issue by mikera** [ptaoussanis/sente#80]
There are several cases where is may be useful to have a Sente client in Clojure on the JVM, e.g.

 - Testing Sente Client <-> Server communications in a single JVM process
 - Server <-> Server communications
 - JVM based clients (e.g. using Swing)

The Clojure client should operate like the ClojureScript client as far as possible.

**Comment by ptaoussanis** [comment]
This issue has become unblocked with the release of https://github.com/ptaoussanis/sente/releases/tag/v1.4.0-alpha1.

Will have no time to investigate this further myself near-term, but ideas/PRs would be welcome!

**Comment by devth** [comment]
I am looking at libs for an upcoming project, and one of my requirements is supporting both service-to-service and service-to-browser socket comms.

Is it possible as-is to use any old websocket client to connect to a sente-served ws? If so I could imagine using something like https://github.com/stylefruits/gniazdo.

**Comment by tvanhens** [comment]
Has anyone made any progress on this issue? Looking to start to test some of our sente comms code but I haven't been able to come up with a good strategy yet. An all server-side option would be really convenient for testing purposes.

**Comment by ptaoussanis** [comment]
Closing to merge with #102
