### ISSUE TITLE
Server, user and client - current socket communication scheme problem

### ISSUE THREAD

**Issue by valichek** [ptaoussanis/sente#82]
Hi, I would like proceed with https://github.com/ptaoussanis/sente/issues/65 discussion.
Server cannot push message to specific client connected by websocket, only to user.
Filtering messages on client side is not good, because it uses necessary server resources to send all messages to all user clients and for high loaded apps it is critical.
I don't understand why the current scheme when server sends messages by uid is preferable. Maybe for common use apps it is OK, but in general case it is highly objectionable.
I've investigated the code and don't see big problem to give server a little more control on clients.

So here is the changes I propose.
0) generate uuids by server (to guarantee uuids uniqueness), so move from client-uuid to uuid to distinct it
1) store channels by uuid
current ` {<uid> <#{hk-chs}>}`
proposed `{<uid>  {<uuid>  <hk-chs>}}`,
2) add send-uuid-fn or change send-fn definition to `fn [user-id uuid ev & [{:as opts :keys [flush?]}]]` and set uuid to nil by default to leave active current scheme
3) add client related events `:chsk/uuidport-close` and `:chsk/uuidport-open`

It is just common solution and it won't break current communication scheme while adding possibility to build more flexible apps.

**Comment by sritchie** [comment]
Hmm. As I mentioned in the other issue I posted, in the latest snapshots my clients aren't receiving messages sent via UUID. Has some change come in since the first `:client-uuid` impl of this?

**Comment by ptaoussanis** [comment]
>  Has some change come in since the first :client-uuid impl of this?

Nothing intentional that I recall. My first guess would be that you're build or build environment have somehow gone bad. Since these may be related, let's keep the discussion at issue #105 for now.

Going to follow up with some questions at #105 now.

**Comment by ptaoussanis** [comment]
Closing for now as it's likely I won't be able to assist with this in at least the short/medium term.

Might be something to investigate again some time in future if someone can provide a clear + updated summary of specific motivations + can address how the current user-id based recommendations are inadequate.

Appreciate all the input given so far! Cheers :-)
