### ISSUE TITLE
Support Binary streams?

### ISSUE THREAD

**Issue by jsa-aerial** [ptaoussanis/sente#91]
This looks very good and should be a great thing to use for my needs.  But I couldn't tell for sure if it supports binary data.  Is that available?

**Comment by ptaoussanis** [comment]
Hey Jon,

Sorry for the delay getting back to you. Would need to spend some time looking into this (i.e. what interface http-kit & other async servers expose, how we could use it, etc.).

In the middle of a product launch atm so realistically won't have time to look into this myself anytime soon. If you (or someone else) were able to do the research + lay out a plan, I'd be happy to assist there where I can.

Will leave the issue open if you (or someone else) has any thoughts.

Sorry I couldn't be of more immediate help. Best of luck, cheers! :-)

**Comment by jsa-aerial** [comment]
Hi Peter,

Thanks for the update.  I think this (at least the variation I want to use)
will be straightforward by simply extending the packer interface to handle
straight (unprocessed) binary data.  Basically just slurp it and spit it to
stdin of a program (via Conch - which is very nice).  Will let you know how
that goes via this issue.

Thanks!

/Jon

**Comment by ptaoussanis** [comment]
Sounds good! I'll leave it to you to work out the details :-)

**Comment by jsa-aerial** [comment]
Hi Peter,

Well, it turns out that in the process of making the necessary changes it became clear that what is really needed is a separation of message protocol from the core facilities.  Put another way, message protocol should be abstracted out as an explicit entity. From what I can tell this complection occurs in every 'higher level' communication package I've looked at - irrespective of language. Several things (especially in Clojure) do abstract out the line data protocol (like Chord's formatter and Sente's IPacker), but the message protocol.

All client / server (or pier to pier as well) communication involves three different protocols:

* The line data protocol - the encoding and decoding of all transmission information to and from sockets (or other 'port' artefacts).

* The message packet protocol - the protocol defining the 'envelope' and meta structure carrying the data payload and meta data of the message.

* The data payload structure.

The first of these is what line 'packer' protocols cover - such as the IPacker protocol in Sente or the ChordFormatter protocol in Chord. 

The last of these is application dependent - the what and how the data being used at the semantic level of the application.

The second is what I mean by the message protocol. By defining the second as an explicit protocol, libs and frameworks are freed from complecting together the other two.

So, I have a protocol defined and incorporated it into Sente. To do this, I removed all the message protocol aspects from Sente 'core' and inserted appropriate protocol method invocations. Now you can implement different message protocols drive them from Sente.  I implemented both the original Sente ('standard') message protocol and the binaryJS(1) protocol with this and both work fine. Message protocols are orthogonal to line data protocols so you can use them with various packers/formatters. Sente no longer knows about line data protocols; instead make-channel-socket! now has a 'msgpacket' option which takes a message protocol implementation or defaults to senteEdnMsg.

The message protocol likely needs refinement and trial in some other systems to enssure it covers what is needed, but only what is needed and doesn't make Sente assumptions that are not applicable to other packages(I know it does still make some of these wrt expected return values from some methods). Chord would be an obvious test case.  Also, I only implemented this for Sented server (Clojure) not yet the client (ClojureScript).  Mostly because I am not as familiar with CLJS.

/Jon
1. binaryJS uses 'binaryPack' which is an obsolete version of msgpack which is a binary line data protocol that handles binary data in the payloads. Yes, it should use a  current version of msgpack, but that is another story.

Why binaryJS? Well, because a boatload of JS apps use this and a Clojure/http-kit/Sente|Chord server has a variety of very large advantages over JavaScript/node.js servers and with this you can swap implementations of the latter with the former without affecting clients. Specifically, I am working on a project that uses binaryJS and there is too much client code for those involved to agree to dumping - but changing the server would afford a lot of benefits (and with less code!!)

**Comment by jsa-aerial** [comment]
After all that I failed to include two important things:

1. I don't know if you are interested in moving forward to roll this into the official Sente release, but if so, what would you think is the best way (fork and pull??)

2. I believe this would also basically take care of issue #80 as you could implement a msg protocol that handles those requirements.  In fact, the binaryJS msg protocol already provides this capability.

**Comment by ptaoussanis** [comment]
Hey there,

First step getting your work in would be some code I can see. That'll give me a better idea of what we're talking about and put me in a better position to comment.

Thanks a lot for your efforts on this! :-)

**Comment by jsa-aerial** [comment]
OK, I'm thinking that a fork of Sente would be the simplest way to get that
base covered.  I will look to do that ASAP.

/Jon

On Tue, May 19, 2015 at 10:09 PM, Peter Taoussanis <notifications@github.com

**Comment by ptaoussanis** [comment]
Great, thanks Jon

**Comment by jsa-aerial** [comment]
Hi Peter,

Finally got some time to put something together.  Decided against a fork at
this time and just have a gist and the msgpacket repo for you to look at.
Sadly not yet much documentation on these, but with luck enough to give the
picture.

Gist has the modified sente server using msgpacket, the new iobio server
core using the binaryjs msg protocol, and a modified my_app using the
default sente msg protocol.

msgpacket repo has the sente and binaryjs protocol implementations

gist:
https://gist.github.com/jsa-aerial/829ba949f5e62c84e8ef

msgpacket:

**Comment by jsa-aerial** [comment]
gmail sends msg when you go to paste????  Anyway, here is the msgpacket url
(I hope...)

https://github.com/jsa-aerial/msgpacket

**Comment by ptaoussanis** [comment]
Hi there,

Sorry for taking so long to reply to this!

To be honest, I'm a little overloaded with work at the moment. Your fork's looking pretty far-reaching; it's going to take a fair bit of time to go through and properly evaluate.

I really appreciate the work you've put in but, realistically, I just don't expect to be able to get back to you about this for at _least_ a couple weeks.

Are you able to use your own fork in the meantime to meet your objectives?

As far as getting this (/other work) into Sente, remember that I'm most likely to be able to offer quick feedback/assistance when:
1. There's a clear, short description of exactly what kind of problem you're trying to solve.
2. There's a clear, short description of exactly what specific limitations you're running into w/ the current version of Sente.
3. There's a clear, short description of any suggested changes and how they specifically address the first 2 points.

In the case of your fork, the most helpful things to get this rolling quicker would be a short, clear summary of what specific changes were necessary, where, and why.

Does that help at all / make sense?

Again, appreciate your time + efforts! Cheers :-)

**Comment by jsa-aerial** [comment]
Hi Peter,

Yes, the fork I have works great. It is simple to build and run an uberjar
from this with the new iobio server functionality. So, that is no problem
from my end.

I too am quite swamped with various work stuff as well (including this new
server, but several other things). Even so, I will try to put together a
summary. As noted before, the basic change was to refactor the msg protocol
aspects out of Sente and into the msgpacket lib, with the two current
implementations - Sente's original user based clients and string based
envelopes and binaryjs's connection based clients with multiple streams and
binary envelopes.

/Jon

**Comment by ptaoussanis** [comment]
Closing this for now. Please feel free to reopen with a follow up to https://github.com/ptaoussanis/sente/issues/91#issuecomment-124335251 if you or anyone else is interested again in future.

Cheers! :-)
