### ISSUE TITLE
start-chsk-router loop question

### ISSUE THREAD

**Issue by hellonico** [ptaoussanis/sente#96]
I am using a slightly modified version of the default router loop::

         (if-not (sente/event-msg? event-msg)
                      ;; Shouldn't be possible here, but we're being cautious:
                      (do 
                       (errorf "Bad event: %s %s" event ch-ctrl) ; Log 'n drop
                       (if (nil? event) 
                            (do 
                              (errorf "Closing channel on null event") 
                              (async/close! ch-ctrl))))
                      (event-msg-handler event-msg))

This plays well with the component workflow, and allows to restart the websocket when needed.
Question was if there was any side effect that could be seen with such a change ?
If not, can we merge it here ? 

1. Without the fix above, the code just keeps on looping and the whole becomes unusable. 
2. When the server side is up again, reconnection on the client side works as expected.

**Comment by ptaoussanis** [comment]
Hi Nicolas,

I believe a number of folks use Sente with a lifecycle management approach, unmodified. Have you checked the docs [here](https://github.com/ptaoussanis/sente#lifecycle-management-component-managementshutdown-etc)?

@danielsz has some code [here](https://github.com/danielsz/system/blob/master/src/system/components/sente.clj) for example that may be helpful?
