### ISSUE TITLE
Fail with :elide-asserts true

### ISSUE THREAD

**Issue by ul** [ptaoussanis/sente#98]
```
Bad package: e[:chsk/handshake ["ece832ab-b449-40cb-b127-1afad4820b92" "knCFUtBDCPMUk8rvWvw2mA7k7Iv1Z46yDznyy8XLSCrDLb45nwStDMGhIbMYn+3PIaTbkIYOqPSKjaDR"]] (Error: false is not ISeqable)
```

**Comment by ptaoussanis** [comment]
Hi Ruslan, thanks for bringing this to my attention. Will try take a look at this w/in the next couple days.

* Could you confirm that this occurs with Sente v1.3.0?
* Any difference if you add a `[com.taoensso/encore "1.20.0"]` dependency to the top of your project.clj deps?

If you're still seeing the error with `[com.taoensso/encore "1.20.0"]`, could I see the contents of your `lein deps :tree`?

Cheers! :-)

**Comment by ul** [comment]
Yes, I've used Sente v1.3.0 with Encore v1.19.1. Updating to Encore v.1.20.0 solves the issue, thank you!

But I had another problem: #99 :-(
